### ISSUE TITLE
I got an error when I installed PCL and tried to run the program

### ISSUE THREAD

**Issue by BoBoINVICTUS** [PointCloudLibrary/pcl#6124] opened 2024-09-03 08:28 UTC
When I run the example program, I get an error:PCL can not be found on this machine，as shown here:
![image](https://github.com/user-attachments/assets/d38d409c-c9d7-4926-affe-5831e45c7213)
My CMakeLists.txt file has the following contents:
![image](https://github.com/user-attachments/assets/fd3afb89-e464-4148-b35f-790c98f29b1a)
I tried to set PCL_ROOT and PCL_DIR, but it didn't work.
My system is Windows 11
cmake version is 3.24.2
PCL version is 1.14.1
I also set the system environment variables:
![image](https://github.com/user-attachments/assets/73b9699f-b3ae-4b56-b055-a6edf6c55ae1)

Can you tell me what the problem is?

**Comment by larshg** [comment] 2024-09-03 11:11
Try add `message(FATAL_ERROR "PCL_ROOT is ${PCL_ROOT} and ENV PCL_ROOT is $ENV{PCL_ROOT}")` right before the find_package.

Also see if `...\PCL1.14.1\include\pcl-1.14\pcl\pcl_config.h` is present?

**Comment by larshg** [comment] 2024-09-03 11:12
Do have PCL_ROOT as a system variable - what is it set to?

**Comment by BoBoINVICTUS** [comment] 2024-09-03 11:26
> Do have PCL_ROOT as a system variable (the installer seems to set it) - what is it set to?
![image](https://github.com/user-attachments/assets/cc7ef83b-c44b-45ed-8039-c7e70904d21b)
![image](https://github.com/user-attachments/assets/457bc406-0911-4409-b184-611cd0829741)
![image](https://github.com/user-attachments/assets/a71b457d-ca71-4cb3-a866-99d1260d9bad)
![image](https://github.com/user-attachments/assets/c5199b84-a534-4a52-8f88-d8ef8350429c)

**Comment by larshg** [comment] 2024-09-03 11:44
Try add:
`message("  Looking for ${PCL_ROOT}/include/pcl-${PCL_VERSION_MAJOR}.${PCL_VERSION_MINOR}/pcl/pcl_config.h")`
to D:\PCL1.14.1\cmake\PCLConfig.cmake below line 433 - ie just before it looks for the pcl_config.h file.

Seems it doesn't support having it installed on D or there are something about the paths and perhaps character settings, that makes cmake unable to verify that the file does exists.

**Comment by BoBoINVICTUS** [comment] 2024-09-03 11:55
> Try add: `message(" Looking for ${PCL_ROOT}/include/pcl-${PCL_VERSION_MAJOR}.${PCL_VERSION_MINOR}/pcl/pcl_config.h")` to D:\PCL1.14.1\cmake\PCLConfig.cmake below line 433 - ie just before it looks for the pcl_config.h file.
> 
> Seems it doesn't support having it installed on D or there are something about the paths and perhaps character settings, that makes cmake unable to verify that the file does exists.

![image](https://github.com/user-attachments/assets/af84fe49-ac3b-4b8e-b7e0-ebc58d41a6df)

**Comment by larshg** [comment] 2024-09-03 12:10
Do you supply any arugments to the cmake call - it seems that PCL_ROOT is only set to D:\.

**Comment by BoBoINVICTUS** [comment] 2024-09-03 12:50
> Do you supply any arguments to the cmake call - it seems that PCL_ROOT is only set to `D:\`.
I use VSCode to write the program, how do I write the command line, add arguments?
![image](https://github.com/user-attachments/assets/f17ff666-6030-45e1-b4a4-3d9e3e39148e)

**Comment by larshg** [comment] 2024-09-03 14:31
Can you show the full output from vscode in text?

**Comment by BoBoINVICTUS** [comment] 2024-09-03 14:40
> Can you show the full output from vscode in text?
![image](https://github.com/user-attachments/assets/29c7ee9c-eaf6-456f-94e7-37bd97131d33)
[main] Configuring project: 点云配准_代码初稿1.0 
[proc] Executing command: D:\cmake-3.24.2-windows-x86_64\bin\cmake.EXE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=D:\MinGw\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:\MinGw\bin\g++.exe --no-warn-unused-cli "-SD:/learning/Robotic-learning/机械臂控制书籍/点云配准从入门到精通/点云配准_代码初稿1.0/3.2 ISS关键点提取" -Bd:/learning/Robotic-learning/机械臂控制书籍/点云配准从入门到精通/点云配准_代码初稿1.0/build -G "MinGW Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake]   Looking for D://include/pcl-1.14/pcl/pcl_config.h
[cmake] CMake Error at D:/PCL1.14.1/cmake/PCLConfig.cmake:59 (message):
[cmake]   PCL can not be found on this machine
[cmake] Call Stack (most recent call first):
[cmake]   D:/PCL1.14.1/cmake/PCLConfig.cmake:453 (pcl_report_not_found)
[cmake]   CMakeLists.txt:10 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/learning/Robotic-learning/机械臂控制书籍/点云配准从入门到精通/点云配准_代码初稿1.0/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "D:/learning/Robotic-learning/机械臂控制书籍/点云配准从入门到精通/点云配准_代码初稿1.0/build/CMakeFiles/CMakeError.log".
[proc] The command: D:\cmake-3.24.2-windows-x86_64\bin\cmake.EXE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=D:\MinGw\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:\MinGw\bin\g++.exe --no-warn-unused-cli "-SD:/learning/Robotic-learning/机械臂控制书籍/点云配准从入门到精通/点云配准_代码初稿1.0/3.2 ISS关键点提取" -Bd:/learning/Robotic-learning/机械臂控制书籍/点云配准从入门到精通/点云配准_代码初稿1.0/build -G "MinGW Makefiles" exited with code: 1

![image](https://github.com/user-attachments/assets/c0ed30cc-8ce2-49c2-8a75-98ca17f76af7)
(base) PS D:\learning\Robotic-learning\机械臂控制书籍\点云配准从入门到精通\点云配准_代码初稿1.0\3.2 ISS关键点提取> cmake -D PCL_ROOT=D:/PCL1.14.1 .
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   系统找不到指定的文件。


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "D:/learning/Robotic-learning/机械臂控制书籍/点云配准从入门到精通/点云配准_代码初稿1.0/3.2 ISS关键点提取/CMakeFiles/CMakeOutput.log

**Comment by larshg** [comment] 2024-09-04 06:44
Mine looks like this:
Executing command: `"C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SC:/dev/iss_keypoints_extract -Bc:/dev/iss_keypoints_extract/build -G "Visual Studio 17 2022" -T host=x64 -A x64`
And I just tried with VSCode and it works as well. I don't have MinGW, so that might be the reason.

**Comment by BoBoINVICTUS** [comment] 2024-09-04 07:09
> Mine looks like this: Executing command: `"C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SC:/dev/iss_keypoints_extract -Bc:/dev/iss_keypoints_extract/build -G "Visual Studio 17 2022" -T host=x64 -A x64` And I just tried with VSCode and it works as well. I don't have MinGW, so that might be the reason.
I don't have Visual Studio installed on my computer. Is that why I can't compile?

**Comment by larshg** [comment] 2024-09-04 07:18
No, its not. You should be able to do it with MinGW/GCC as well. I'm just not familiar with it or if it has any relevance.
Somehow your PCL_ROOT gets changed or not set - can you try run, when you set it in your CmakeLists?

**Comment by BoBoINVICTUS** [comment] 2024-09-04 07:41
> No, its not. You should be able to do it with MinGW/GCC as well. I'm just not familiar with it or if it has any relevance. Somehow your PCL_ROOT gets changed or not set - can you try run, when you set it in your CmakeLists?
![image](https://github.com/user-attachments/assets/13286b46-8952-4a83-88eb-feeb565ecbd8)
![image](https://github.com/user-attachments/assets/3ef48105-d3ce-48b5-805a-7ff9ac387560)
I set the PCL_ROOT in CMakeLists.txt, but it doesn't work.

**Comment by BoBoINVICTUS** [comment] 2024-09-04 08:11
> No, its not. You should be able to do it with MinGW/GCC as well. I'm just not familiar with it or if it has any relevance. Somehow your PCL_ROOT gets changed or not set - can you try run, when you set it in your CmakeLists?

Maybe my PCL download is wrong? Instead of downloading "PCL-1.14.1-AllInOne-msvc2022-win64.exe", I should have installed it from source?

**Comment by larshg** [comment] 2024-09-04 08:12
Do you use 
![image](https://github.com/user-attachments/assets/7c28826c-3275-4028-b7bd-c9b36c5785a0)
?

Also try open Cmake Cache editor and look if there is a PCL_ROOT variable?
![image](https://github.com/user-attachments/assets/6d4b7fa8-5c29-4891-bd9d-12e915060c89)

**Comment by BoBoINVICTUS** [comment] 2024-09-04 08:28
> Do you use ![image](https://private-user-images.githubusercontent.com/1165340/364283274-7c28826c-3275-4028-b7bd-c9b36c5785a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0Mzc4MzMsIm5iZiI6MTcyNTQzNzUzMywicGF0aCI6Ii8xMTY1MzQwLzM2NDI4MzI3NC03YzI4ODI2Yy0zMjc1LTQwMjgtYjdiZC1jOWIzNmM1Nzg1YTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDgxMjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDcyNmZkN2ZmM2FlMGRhMzQ5YzAzZjEwYTA1NTEwM2M5M2IyMzI5ZDdlZWY0ZjQwNTJkZjA1ODcxMWZkNTBhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LnbwUSQSR24C6ilMAFCNzQsGkgv7LtTcebYh6TEbEqg) ?
> 
> Also try open Cmake Cache editor and look if there is a PCL_ROOT variable? ![image](https://private-user-images.githubusercontent.com/1165340/364283529-6d4b7fa8-5c29-4891-bd9d-12e915060c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0Mzc4MzMsIm5iZiI6MTcyNTQzNzUzMywicGF0aCI6Ii8xMTY1MzQwLzM2NDI4MzUyOS02ZDRiN2ZhOC01YzI5LTQ4OTEtYmQ5ZC0xMmU5MTUwNjBjODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDgxMjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFjYzA1YzI2YWRiOTdjOGQ4MjhmNTVhMDVmNjAzNjg2ZTQ1N2I0ZjVmMTlhMzJjODg5ZjNhOGYyYWQ4ZDc3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c-8e16RQzKt0PQVeAhp4wbEBn8_XIztBdKq5pLn-2j4)
I used delete cache and reconfigure, but the result is the same as before
![image](https://github.com/user-attachments/assets/90ab1f35-5b25-4f5e-a7ab-bc7945c2b9e9)

There is no PCL_ROOT variable in CmakeCache.txt, but there is a PCL_DIR variable.
![image](https://github.com/user-attachments/assets/390498c4-4696-48f1-9a26-23c948507d72)

**Comment by larshg** [comment] 2024-09-04 09:05
I think its this code that fails in the PCLConfig.cmake:
```
if(WIN32 AND NOT MINGW)
# PCLConfig.cmake is installed to PCL_ROOT/cmake
  get_filename_component(PCL_ROOT "${PCL_DIR}" PATH)
  if(EXISTS "${PCL_ROOT}/3rdParty")
    set(PCL_ALL_IN_ONE_INSTALLER ON)
  endif()
else()
# PCLConfig.cmake is installed to PCL_ROOT/share/pcl-x.y
  get_filename_component(PCL_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()
```

Try remove the `AND NOT MINGW`

**Comment by BoBoINVICTUS** [comment] 2024-09-04 11:42
> I think its this code that fails in the PCLConfig.cmake:
> 
> ```
> if(WIN32 AND NOT MINGW)
> # PCLConfig.cmake is installed to PCL_ROOT/cmake
>   get_filename_component(PCL_ROOT "${PCL_DIR}" PATH)
>   if(EXISTS "${PCL_ROOT}/3rdParty")
>     set(PCL_ALL_IN_ONE_INSTALLER ON)
>   endif()
> else()
> # PCLConfig.cmake is installed to PCL_ROOT/share/pcl-x.y
>   get_filename_component(PCL_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
> endif()
> ```
> 
> Try remove the `AND NOT MINGW`

When I remove the AND NOT MINGW, I get a new error：
![image](https://github.com/user-attachments/assets/487ffb40-7984-4feb-acb0-0c44eed11c51)
I followed the same approach，remove the `AND NOT MINGW` in PCLConfig.cmake：
# if(WIN32 AND NOT MINGW AND NOT "${BOOST_DEFINITIONS}" MATCHES "BOOST_ALL_NO_LIB")
  if(WIN32 AND NOT "${BOOST_DEFINITIONS}" MATCHES "BOOST_ALL_NO_LIB")
    string(APPEND BOOST_DEFINITIONS -DBOOST_ALL_NO_LIB)
  endif()

That mistake still hasn't gone away.

**Comment by larshg** [comment] 2024-09-04 12:07
Try add `set(Boost_DEBUG ON)` in your cmake and clear cache and rerun. Odd that it doesn't find the libraries, when it does find the boostConfig.

**Comment by BoBoINVICTUS** [comment] 2024-09-04 12:12
> Try add `set(Boost_DEBUG ON)` in your cmake and clear cache and rerun. Odd that it doesn't find the libraries, when it does find the boostConfig.

It's the same error, I look at the relevant path, it seems to find it, but it's still an error, I don't understand
![image](https://github.com/user-attachments/assets/b7318813-0237-4715-93ab-370a580c8518)

**Comment by larshg** [comment] 2024-09-04 12:23
Can you post the cmake output?

**Comment by BoBoINVICTUS** [comment] 2024-09-04 12:33
> Which MinGW do you use - then I can try to replicate.

The cmake output is as follows:
CMake Warning (dev) at CMakeLists.txt:3 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable PCL_ROOT is set to:

    D:\PCL1.14.1\

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

  Looking for D:/PCL1.14.1/include/pcl-1.14/pcl/pcl_config.h
Could NOT find Boost: missing: system iostreams filesystem serialization (found D:/PCL1.14.1/3rdParty/Boost/lib/cmake/Boost-1.84.0/BoostConfig.cmake (found suitable version "1.84.0", minimum required is "1.65.0"))
CMake Error at D:/PCL1.14.1/cmake/PCLConfig.cmake:59 (message):
  common is required but boost was not found
Call Stack (most recent call first):
  D:/PCL1.14.1/cmake/PCLConfig.cmake:371 (pcl_report_not_found)
  D:/PCL1.14.1/cmake/PCLConfig.cmake:563 (find_external_library)
  CMakeLists.txt:3 (find_package)

MinGW version is:
gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

**Comment by larshg** [comment] 2024-09-04 13:07
Ahh
The all-in-one installer is build using Visual studio, but you try to use MinGW, which is not supporting the usage of Visual studio build libraries.
![image](https://github.com/user-attachments/assets/ba64c0df-4d6c-4e62-b631-41745932cad9)

You would need to build all dependencies from source, to make it work properly. Or use Visual studio community edition instead.

You could try to use VCPKG with MinGW - there all dependencies will be build using your local compiler.

**Comment by larshg** [comment] 2024-09-04 13:07
![image](https://github.com/user-attachments/assets/8efeb4bf-f913-4b70-85dd-242340a6f9b3)

**Comment by larshg** [comment] 2024-09-04 13:08
Closing as it is not a bug in PCL per se - but a compiler / mixing of tools issue.

**Comment by larshg** [comment] 2024-09-04 13:08
Feel free to add comments though 😄

**Closed by larshg** 2024-09-04 13:08 UTC
Labels: platform: windows

**Comment by larshg** [comment] 2024-09-04 14:02
https://pcl.readthedocs.io/projects/tutorials/en/latest/compiling_pcl_dependencies_windows.html#compiling-pcl-dependencies-windows but its quite old.
I would go with vcpkg first:
https://pcl.readthedocs.io/projects/tutorials/en/latest/pcl_vcpkg_windows.html#pcl-vcpkg-windows
