### ISSUE TITLE
VS build PCL with CUDA project Error: compiler is out of heap space OR A single input file is required for a non-link phase when an outputfile is specified

### ISSUE THREAD

**Issue by miaoyanlearningcode** [PointCloudLibrary/pcl#3450] opened 2019-11-06 09:43 UTC
I am trying a simple example with pcl 1.9 and cuda 10.1. But when I built the project, Visual Studio(2019) shows an error: compiler is out of heap space and error file points to point_types.h. I googled it and tried /Zm to increase the heap. But still now I could not find a solution. Any one met this before?
## Your Environment

* Operating System and version: Windows 10
* Compiler: Visual Studio 2019 (vs 142) + Cuda 10.1 + Cudnn 7.5
* PCL Version: 1.9

## Current Behavior

In my cu file, if I add #include<point_types.h>, there will be an error "compiler is out off heap". If I comment out this line, the project will be built successfully.

**Comment by miaoyanlearningcode** [comment] 2019-11-06 09:52
OK. I figure out, .cu is using nvidia compiler, so just add /Zm to project->options->cuda c/c++ ->Command Line->/Zm1000 and done!

**Comment by miaoyanlearningcode** [comment] 2019-11-07 06:15
Actually, after I add /Zm1000, new error happened,   "A single input file is required for a non-link phase when an outputfile is specified". If I change back without /Zm1000, the heap space error happened again. Still no solution found yet.

**Comment by kunaltyagi** [comment] 2020-06-24 03:49
Is it worth it to have CUDA on the MSVC CI? (one of them at least) @shrijitsingh99 @larshg @PointCloudLibrary/maintainers

**Comment by larshg** [comment] 2020-06-24 08:46
I don't think its easy to get CUDA on the CI. Running the cuda/nvidia-driver installer would probably reject the system because no compatible GPU will be found.

I have however considered to manually copy the "CUDA" directory from an installation on another PC to the CI/windows docker image. So the header/library files can be found. Then maybe we can get compiling working.

**Comment by larshg** [comment] 2020-06-24 08:58
And this issue might be closed as searching for "A single input file is required for a non-link phase when an outputfile is specified" tends to give lots of hits about passing wrong arguments to NVCC.

Not a bug in PCL per se.

**Closed** 2020-06-24 09:53 UTC
