### ISSUE TITLE
[cmake] Prevent compiler warnings on PCL header files when using find_package() 

### ISSUE THREAD

**Issue by vebjornjr** [PointCloudLibrary/pcl#5238] opened 2022-04-26 09:32 UTC
I would be useful to not get compiler warnings on the header files included from PCL when used in another project.

**Context**

I installed PCL with vcpkg on arm64-linux and used `find_package(PCL CONFIG REQUIRED)` in CMake.

**Describe the solution you'd like**

[Here](https://www.foonathan.net/2018/10/cmake-warnings/) is a resource how libraries may structure their CMakeLists.txt to prevent projects linking to the library getting compiler warnings on includes. In short, the key is to make project include library headers as system includes.

**Comment by mvieth** [comment] 2022-04-26 16:54
Yes, there are for sure ways that PCL can be improved or modernized, CMake-wise. If you are interested, feel free to open a pull request.
Could you specify which warnings you get, and from which header files? Best would be a short program with CMakeLists.txt to fully reproduce your case.
Ideally, we would fix the warnings in PCL of course.
It might also be possible to turn off the warnings in your CMakeLists.txt for the PCL headers only, as a fast solution for your case.

**Comment by mvieth** [comment] 2022-05-03 08:38
@vebjornjr Which warnings do you get, and from which header files?
Can you provide a short program with a CMakeLists.txt so I can reproduce your case?

**Comment by mvieth** [comment] 2022-05-17 12:53
@vebjornjr I am closing this issue, since I don't know which warnings or header files you are talking about, or how to reproduce the problem. Even if I tried to fix the problem, I wouldn't know what the best solution is or whether my fix actually solves the problem. If you provide the necessary information, I can look into it

**Closed by mvieth** 2022-05-17 12:53 UTC
Labels: kind: request, status: triage
