### ISSUE TITLE
 an illegal memory access was encountered in gpu/octree/src/cuda/octree_builder.cu:403 

### ISSUE THREAD

**Issue by ada-hs** [PointCloudLibrary/pcl#2589] opened 2018-10-29 08:43 UTC
I tried to use pcl::gpu::Octree. my card is nvidia gt 710, win10. I get error: 
Error: an illegal memory access was encountered /usr/PointCloudLab/pcl-trunk/gpu/octree/src/cuda/octree_builder.cu:403 

did there anybody meet  this error?

**Comment by taketwo** [comment] 2018-11-05 11:47
Seems to be a duplicate of #2371, please reopen if not.

**Closed by taketwo** 2018-11-05 11:47 UTC
