### ISSUE TITLE
PCLConfig.cmake unable to find pcl 1.12.1 on macOS

### ISSUE THREAD

**Issue by fspindle** [PointCloudLibrary/pcl#5129] opened 2022-01-08 17:41 UTC
- OS: macOS Big Sur 11.6.2
- PCL version: 1.12.1 installed using Homebrew: `brew install pcl`
- CMake version 3.22.1

The following `CMakeLists.txt` is unable to find pcl 1.12.1

```
project(test-pcl)

cmake_minimum_required(VERSION 3.0)

find_package(PCL)
if(PCL_FOUND)
  message("PCL_INCLUDE_DIRS: ${PCL_INCLUDE_DIRS}")
  message("PCL_LIBRARY_DIRS: ${PCL_LIBRARY_DIRS}")
  message("PCL_LIBRARIES: ${PCL_LIBRARIES}")
  message("PCL_COMPONENTS: ${PCL_COMPONENTS}")
  message("PCL_VERSION: ${PCL_VERSION}")
else()
  message("pcl not found")
endif()
```
It produces the following output:
```
$ cmake .
...
PCL_INCLUDE_DIRS: 
PCL_LIBRARY_DIRS: 
PCL_LIBRARIES: 
PCL_COMPONENTS: 
PCL_VERSION: 1.12.1
-- Configuring done
-- Generating done
```

Now when I modify the `CMakeLists.txt` using `find_package(PCL COMPONENTS common io kdtree)`
it gives:
```
PCL_INCLUDE_DIRS: /usr/local/include/pcl-1.12;/usr/local/include/eigen3;/usr/local/include
PCL_LIBRARY_DIRS: /usr/local/lib
PCL_LIBRARIES: pcl_common;pcl_octree;pcl_io;pcl_kdtree;Boost::system;Boost::filesystem;Boost::date_time;Boost::iostreams;Boost::serialization;FLANN::FLANN
PCL_COMPONENTS: pcl_common;pcl_octree;pcl_io;pcl_kdtree
PCL_VERSION: 1.12.1
```
which is better but not satisfactory.

How to get `PCL_INCLUDE_DIRS` and `PCL_LIBRARIES` updated with all the components without specifying them?
This behavior was available with pcl 1.11.1

**Comment by mvieth** [comment] 2022-01-09 10:13
I just tested your original CMakeLists.txt (without specifying components) under Ubuntu, CMake 3.22.1, current PCL master branch (roughly equivalent to the 1.12.1 release). All `PCL_*` variables contain what you would expect.
So this behaviour seems to be macOS or homebrew specific.

> This behavior was available with pcl 1.11.1

Also installed via homebrew? Do you know which CMake version you used then?
I can't think of any changes inside PCL that would explain why this behaviour changed compared to 1.11.1. It might be that the homebrew maintainers apply any patches which cause this?

> which is better but not satisfactory.

Why is this not satisfactory? I would recommend to only ask for those components you actually need (keeps the build lighter and potentially faster)

**Comment by fspindle** [comment] 2022-01-09 10:51
> > This behavior was available with pcl 1.11.1

> Also installed via homebrew? Do you know which CMake version you used then?

Yes with homebrew also. 
- In February 2020, it worked with pcl 1.9.1 and cmake 3.16.4 both installed with homebrew
- In February 2021, it worked with pcl 1.11.1 and cmake 3.19.4 both installed with homebrew

> I can't think of any changes inside PCL that would explain why this behaviour changed compared to 1.11.1. It might be that the homebrew maintainers apply any patches which cause this?

Homebrew formula is available [here](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pcl.rb). I don't see any patch and the test that is done to validate the formula installation is quite similar to mine! I suspect that something goes wrong with cmake 3.22.1

 > Why is this not satisfactory? I would recommend to only ask for those components you actually need (keeps the build lighter and potentially faster)

Yes you are right, but currently a project that was working with the previous version is no more working. Upwards compatility is broken.

**Comment by fspindle** [comment] 2022-01-09 11:57
> I suspect that something goes wrong with cmake 3.22.1

Uninstalling cmake 3.22.1 by `brew uninstall cmake` and installing cmake 3.19.4 from source shows the same behavior.

```
$ cmake --version
cmake version 3.19.4
$ cmake .
PCL_INCLUDE_DIRS: 
PCL_LIBRARY_DIRS: 
PCL_LIBRARIES: 
PCL_COMPONENTS: 
PCL_VERSION: 1.12.1
```

Same test with cmake 3.16.1 installe from source and same results.

```
$ cmake --version
cmake version 3.16.4
$ cmake .
PCL_INCLUDE_DIRS: 
PCL_LIBRARY_DIRS: 
PCL_LIBRARIES: 
PCL_COMPONENTS: 
PCL_VERSION: 1.12.1
``

**Comment by fspindle** [comment] 2022-01-09 17:48
I found that `visualization` component is not found betcause VTK is unable to found Qt5.

```
-- Could not find the VTK package due to a missing dependency: Qt5
CMake Warning at /usr/local/share/pcl-1.12/PCLConfig.cmake:270 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/vtk-9.1/vtk-config.cmake

  but it set VTK_FOUND to FALSE so package "VTK" is considered to be NOT
  FOUND.  Reason given by package:

  Could not find the VTK package with the following required components:
  GUISupportQt.

Call Stack (most recent call first):
  /usr/local/share/pcl-1.12/PCLConfig.cmake:321 (find_VTK)
  /usr/local/share/pcl-1.12/PCLConfig.cmake:545 (find_external_library)
  CMakeLists.txt:12 (find_package)
```

When I modify my `CMakeLists.txt` to set `Qt5_DIR`

```
set(Qt5_DIR /usr/local/Cellar/qt@5/5.15.2_1/lib/cmake/Qt5)
find_package(PCL)
```

It works
```
-- Found PCL: pcl_common;pcl_kdtree;pcl_octree;pcl_search;pcl_sample_consensus;pcl_filters;pcl_io;pcl_features;pcl_ml;pcl_segmentation;pcl_visualization;pcl_surface;pcl_registration;pcl_keypoints;pcl_tracking;pcl_recognition;pcl_stereo;pcl_apps;pcl_outofcore;pcl_people;pcl_simulation;Boost::system;Boost::filesystem;Boost::date_time;Boost::iostreams;Boost::serialization;VTK::ChartsCore;VTK::CommonColor;VTK::CommonComputationalGeometry;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMath;VTK::CommonMisc;VTK::CommonTransforms;VTK::FiltersCore;VTK::FiltersExtraction;VTK::FiltersGeneral;VTK::FiltersGeometry;VTK::FiltersModeling;VTK::FiltersSources;VTK::ImagingCore;VTK::ImagingSources;VTK::InteractionImage;VTK::InteractionStyle;VTK::InteractionWidgets;VTK::IOCore;VTK::IOGeometry;VTK::IOImage;VTK::IOLegacy;VTK::IOPLY;VTK::RenderingAnnotation;VTK::RenderingCore;VTK::RenderingContext2D;VTK::RenderingLOD;VTK::RenderingFreeType;VTK::ViewsCore;VTK::ViewsContext2D;VTK::RenderingOpenGL2;VTK::GUISupportQt;FLANN::FLANN;QHULL::QHULL  
PCL_INCLUDE_DIRS: /usr/local/include/pcl-1.12;/usr/local/include/eigen3;/usr/local/include;/Library/Frameworks/Mono.framework/Headers;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include
PCL_LIBRARY_DIRS: /usr/local/lib
PCL_LIBRARIES: pcl_common;pcl_kdtree;pcl_octree;pcl_search;pcl_sample_consensus;pcl_filters;pcl_io;pcl_features;pcl_ml;pcl_segmentation;pcl_visualization;pcl_surface;pcl_registration;pcl_keypoints;pcl_tracking;pcl_recognition;pcl_stereo;pcl_apps;pcl_outofcore;pcl_people;pcl_simulation;Boost::system;Boost::filesystem;Boost::date_time;Boost::iostreams;Boost::serialization;VTK::ChartsCore;VTK::CommonColor;VTK::CommonComputationalGeometry;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMath;VTK::CommonMisc;VTK::CommonTransforms;VTK::FiltersCore;VTK::FiltersExtraction;VTK::FiltersGeneral;VTK::FiltersGeometry;VTK::FiltersModeling;VTK::FiltersSources;VTK::ImagingCore;VTK::ImagingSources;VTK::InteractionImage;VTK::InteractionStyle;VTK::InteractionWidgets;VTK::IOCore;VTK::IOGeometry;VTK::IOImage;VTK::IOLegacy;VTK::IOPLY;VTK::RenderingAnnotation;VTK::RenderingCore;VTK::RenderingContext2D;VTK::RenderingLOD;VTK::RenderingFreeType;VTK::ViewsCore;VTK::ViewsContext2D;VTK::RenderingOpenGL2;VTK::GUISupportQt;FLANN::FLANN;QHULL::QHULL
PCL_COMPONENTS: pcl_common;pcl_kdtree;pcl_octree;pcl_search;pcl_sample_consensus;pcl_filters;pcl_io;pcl_features;pcl_ml;pcl_segmentation;pcl_visualization;pcl_surface;pcl_registration;pcl_keypoints;pcl_tracking;pcl_recognition;pcl_stereo;pcl_apps;pcl_outofcore;pcl_people;pcl_simulation
PCL_VERSION: 1.12.1
```

The question is why Qt5 is not found ?

**Comment by mvieth** [comment] 2022-01-11 16:07
Thank you that you are investigating this! So if I understand correctly, this problem is caused by homebrew?

**Comment by mvieth** [comment] 2022-01-14 07:45
@fspindle I saw that the issue you linked above is closed now. So can this issue also be closed then? Or is there something inside PCL we can/should fix so this doesn't happen again?

**Comment by fspindle** [comment] 2022-01-14 08:56
I think that you should have a trial on your side installing pcl dependencies (eigen, vtk...) using brew and then trying a pcl build from source on macOS to see if these dependencies are detected. If I'm right, you should see that vtk and qt5 are not detected.

The solution I found forcing qt5 link is one solution. I don't know if it is the good solution. If you think that it is a good workaround, it should be mentioned somewhere in the pcl installation documentation.

On my side, this issue can be closed.

**Comment by larshg** [comment] 2022-01-14 17:33
Our CIs does install the dependencies using brew: https://github.com/PointCloudLibrary/pcl/blob/8f2aad741d1ec6925e82dafee5c399da200889e5/.ci/azure-pipelines/build/macos.yaml#L6

Which builds from source ofc. Maybe you can have a look in the CI settings to see if there is a difference in how you do it?

**Comment by larshg** [comment] 2022-01-14 17:36
And seen in the cmake output log, it does find both vtk(which also finds qt5) as well as qt5.
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=20834&view=logs&j=8042da28-3549-5cef-c93d-1a000d12f42a&t=fece401d-112c-54c6-d591-56921a9f56a6&l=93

**Comment by larshg** [comment] 2022-01-14 17:38
Just looked quick myself and it does get path to qt5 as an argument:
https://github.com/PointCloudLibrary/pcl/blob/8f2aad741d1ec6925e82dafee5c399da200889e5/.ci/azure-pipelines/build/macos.yaml#L19
Almost similiar to what you mentioned earlier?

**Comment by fspindle** [comment] 2022-01-15 08:31
Yes this is similar and maybe better than forcing the link

**Comment by kunaltyagi** [comment] 2022-02-23 11:02
Closing since issue solved (I guess). If not, reopening is easy as well

**Closed by kunaltyagi** 2022-02-23 11:02 UTC
Labels: kind: bug, platform: macos

**Comment by preethamam** [comment] 2022-08-27 16:20
> The solution I found is to link qt5
> 
> ```
> $ brew link --force qt5
> $ sudo ln -s $(brew --prefix qt5)/mkspecs /usr/local/mkspecs
> $ sudo ln -s $(brew --prefix qt5)/plugins /usr/local/plugins
> ```

I do have the same issue with `PCL 1.12.1` installed using the `homebrew`. However, the link did not work for me. I get the following error:

```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for module 'eigen3'
--   Found eigen3, version 3.4.0
-- Found Eigen: /opt/homebrew/include/eigen3 (Required is at least version "3.1") 
-- Eigen found (include: /opt/homebrew/include/eigen3, version: 3.4.0)
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.79.0/BoostConfig.cmake (found suitable version "1.79.0", minimum required is "1.65.0") found components: system filesystem date_time iostreams serialization 
-- Checking for module 'flann'
--   Found flann, version 1.9.1
-- Found FLANN: /opt/homebrew/lib/libflann_cpp.dylib  
-- FLANN found (include: /opt/homebrew/include, lib: /opt/homebrew/lib/libflann_cpp.dylib)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found GLEW: /opt/homebrew/lib/libGLEW.dylib  
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework  found components: OpenGL 
-- Found JsonCpp: /opt/homebrew/lib/libjsoncpp.dylib (found suitable version "1.9.5", minimum required is "0.7.0") 
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd (found version "1.2.11") 
-- Found PNG: /opt/homebrew/lib/libpng.dylib (found version "1.6.37") 
CMake Error at /opt/homebrew/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:14 (message):
  The imported target "Qt5::Core" references the file

     "/opt/homebrew/.//mkspecs/macx-clang-arm64"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/opt/homebrew/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /opt/homebrew/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake:56 (_qt5_Core_check_file_exists)
  /opt/homebrew/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:227 (include)
  /opt/homebrew/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:93 (find_package)
  /opt/homebrew/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:93 (find_package)
  /opt/homebrew/lib/cmake/Qt5OpenGL/Qt5OpenGLConfig.cmake:93 (find_package)
  /opt/homebrew/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /opt/homebrew/lib/cmake/vtk-9.1/VTK-vtk-module-find-packages.cmake:1243 (find_package)
  /opt/homebrew/lib/cmake/vtk-9.1/vtk-config.cmake:150 (include)
  /opt/homebrew/share/pcl-1.12/PCLConfig.cmake:270 (find_package)
  /opt/homebrew/share/pcl-1.12/PCLConfig.cmake:319 (find_VTK)
  /opt/homebrew/share/pcl-1.12/PCLConfig.cmake:543 (find_external_library)
  CMakeLists.txt:19 (find_package)
```

**Comment by mvieth** [comment] 2022-08-28 14:33
@preethamam Have you tried the suggestion with `Qt5_DIR`?
Either in your CMakeLists.txt before trying to find PCL: `set(Qt5_DIR /usr/local/Cellar/qt@5/5.15.2_1/lib/cmake/Qt5)`
Or adding to the `cmake` call: `-DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5`
In both cases, the path should be where `Qt5Config.cmake` or `qt5-config.cmake` is located.
(And maybe undo the link first?)

**Comment by preethamam** [comment] 2022-08-29 17:05
@mvieth, thanks, yes your suggestion works! I wonder why `cmake` doesn't find the `Qt5_DIR` by default?

**Comment by mvieth** [comment] 2022-08-29 19:11
> I wonder why `cmake` doesn't find the `Qt5_DIR` by default?

I am not super familiar with macOS and homebrew, but as I understood it, Qt5 is "keg-only" which apparently means that it is in a specific directory, where `cmake` normally does not look for config files. Not sure who is to blame for this (homebrew? cmake? qt? vtk?)

**Comment by lichengqi0805** [comment] 2022-09-07 04:01
> @preethamam Have you tried the suggestion with `Qt5_DIR`? Either in your CMakeLists.txt before trying to find PCL: `set(Qt5_DIR /usr/local/Cellar/qt@5/5.15.2_1/lib/cmake/Qt5)` Or adding to the `cmake` call: `-DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5` In both cases, the path should be where `Qt5Config.cmake` or `qt5-config.cmake` is located. (And maybe undo the link first?)

for me it is `set(Qt5_DIR /opt/homebrew/Cellar/qt@5/5.15.5_1/lib/cmake/Qt5)`

**Comment by fspindle** [comment] 2022-09-22 08:33
For me running cmake with `-DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5` was working

**Comment by LordonCN** [comment] 2023-02-05 02:55
After install pcl 1.12.1 use `brew install homwbrew`, add `set(Qt5_DIR /opt/homebrew/Cellar/qt@5/5.15.5/lib/cmake/Qt5)` to cmakelists.txt can fix.

**Comment by moonmoonmoonmoon** [comment] 2023-08-03 21:30
> $ brew link --force qt5
> $ sudo ln -s $(brew --prefix qt5)/mkspecs /usr/local/mkspecs
> $ sudo ln -s $(brew --prefix qt5)/plugins /usr/local/plugins
I have worse problems after using this solution. In the past, I can pass q5 test, can't pass vtk test, now I both can't pass. Who knows how to delete the soft link?
