### ISSUE TITLE
OBJReader() wrong texture from MTL file

### ISSUE THREAD

**Issue by samarth-robo** [PointCloudLibrary/pcl#1615] opened 2016-05-31 21:23 UTC
I am not too familiar with OBJ and MTL files, so if I have made a n00b mistake, apologies!

I am using `OBJReader` and  `PCLVisualizer::addTextureMesh()` to visualize this OBJ + MTL file : https://www.dropbox.com/sh/v8ewrwjcmul4a9g/AAByKii1fB8_bvfslqNKxFWea/6%20%E2%80%93%20Example%20of%20We%20Get%20Around%20FloorMe%20.obj%20file/fb0f76d24b2f4145bb5ba9cae86a0f46

Here is my code:

```
// program to show an OBJ file with MTL texture
#include <iostream>

#include <pcl/conversions.h>
#include <pcl/io/obj_io.h>
#include <pcl/visualization/pcl_visualizer.h>

using namespace std;
using namespace pcl;
using namespace Eigen;

typedef PointCloud<PointXYZ> PC; 

boost::shared_ptr<visualization::PCLVisualizer> simpleVis() {
  boost::shared_ptr<visualization::PCLVisualizer> viewer(new visualization::PCLVisualizer("3D Viewer"));
  viewer->setBackgroundColor(0, 0, 0); 
  viewer->addCoordinateSystem(1.0);
  viewer->setShowFPS(false);
  return viewer;
}

int main(int argc, char **argv) {
  if(argc != 2) {
    cout << "Usage: ./show_obj_file <obj_filename>";
    return -1; 
  }

  // read polygon mesh
  PC::Ptr cloud(new PC);
  TextureMesh::Ptr mesh(new TextureMesh);
  OBJReader obj;
  if(obj.read(argv[1], *mesh) == -1) {
    cout << "Could not read " << argv[1];
    return -1; 
  }

  // convert polygon mesh to point cloud
  fromPCLPointCloud2(mesh->cloud, *cloud);

  boost::shared_ptr<visualization::PCLVisualizer> viewer(simpleVis());
  viewer->addTextureMesh(*mesh);
  while(!viewer->wasStopped()) {
    viewer->spinOnce(100);
    pcl_sleep(0.5);
  }
  return 0;
}
```

The visualizations in `PCLVisualizer` and Meshlab are quite different:
![screenshot-1464729663](https://cloud.githubusercontent.com/assets/2848070/15690947/15cda85c-2754-11e6-86a0-de48b4bd3bfa.png)
`PCLVisualizer` (wrong texture)

![matterport](https://cloud.githubusercontent.com/assets/2848070/15691006/548560c6-2754-11e6-8cb1-4ac76e86cdd5.png)
Meshlab (correct texture)

I can't be sure that both the snapshots were from the same viewpoint, but the entire `PCLVisualizer` visualization seems to have the same repeating texture.

**Comment by SergioRAgostinho** [comment] 2016-06-01 12:26
Looks like a duplicate of this #1592. 

Can't really dig into it until the Hackfest is done.

**Comment by taketwo** [comment] 2018-03-14 12:03
This is certainly a duplicate of #1592.

**Closed by taketwo** 2018-03-14 12:03 UTC
