### ISSUE TITLE
[pointclouds.org] Outdated content, malicious redirection

### ISSUE THREAD

**Issue by jackjansen** [PointCloudLibrary/pcl#2864] opened 2019-02-15 23:39 UTC
I'm reporting this issue here because this seems to be where the active community is.

The website <http://pointclouds.org> is seriously outdated and has a lot of incorrect information. References to PCL 1.6, dead links for Windows installers on shady-looking URLs, 6 year old Mac links, etc.

Unfortunately it is still the top hit with search engines, so when I started with PCL a few months ago I was under the impression that pcl was an orphaned project on its way to forgetfulness. When I finally came across the GitHub presence I was very pleasantly surprised that pcl is anything but moribund, but thriving. And with decent installers, CI/CD, version management and all other open source goodies.

It might be a good idea to either update the website, or even take it offline if that is too much work or otherwise difficult, because the readme here provides a lot better information...

Regards,
Jack

**Comment by SergioRAgostinho** [comment] 2019-02-18 11:29
I'll try to provide some justification behind things, while adding the disclaimer that this is my sole perception of how things reached the current state.

Since this project is mostly driven by volunteer time, much like any other open source project, the contributors and maintainers tend to invest time on things they consider useful but above all entertaining. It's volunteer time after all.

The website and mailing list, simply extended beyond an effort threshold, that the current wave of maintainers are willing to commit. So in some sense, both the website and the (non functioning) mailing list, do represent a artifacts from a time the community was much vibrant. Despite that, among all the chaos and potential misinformation, there's still some valuable info on the website and that's why it is still lying around.

To finalize, our current focus is migrating the code base to C++14 for the next release. After that we will still need to pick up another focus, but I feel the current motivation to touch the website is close to none.

**Comment by jackjansen** [comment] 2019-02-20 12:16
I fully understand:-)

I only raised the issue to make sure that you _are_ aware of the fact that currently the website is doing more harm in growing your community than good (in my opinion).

**Comment by tangbao** [comment] 2019-04-11 00:30
But could we make contributions to that website?

**Comment by SergioRAgostinho** [comment] 2019-04-11 07:59
> But could we make contributions to that website?

That would be the ideal case. But at the moment, I don't believe we want to invest more time and effort on the current framework which is supporting the website, so a migration is necessary. For that to be achievable, @PointCloudLibrary/maintainers need to set first the guiding lines on how to handle it:
- what we want to maintain and what to leave behind;
- the desired degree of maintenance, autonomy and functionality.

Hopefully we'll have people following up first with suggestions and guidance, and then taking on some of the migration tasks. I have to admit I'm not really aware on how much people actually realistically follow this project. In general, we just interact with a  few limited number of contributors, so there's a chance the topic doesn't gain that much traction.

**Comment by taketwo** [comment] 2019-04-11 11:10
In my ideal world there would be a single Sphinx-generated documentation website that includes a) API reference; b) tutorials; c) misc pages (style guide, faq, etc). But unfortunately, no time to implement this.

**Comment by andre-nguyen** [comment] 2019-06-11 15:32
@SergioRAgostinho How can we help on this issue? I was under the same impression as @jackjansen and I was ready to recommend my team to drop PCL. Some google links to the docs website even redirect to ad pages.

**Comment by SergioRAgostinho** [comment] 2019-06-11 18:13
At the moment, I am somewhat stuck in getting the release out (see progress [here](https://github.com/PointCloudLibrary/pcl/issues/2772)), which will keep me busy till early-mid July in terms of time investment. We agreed to go through the website issue after the release. That being said, the community is not bound by the same deadlines as us and there are indeed things it can do in advance.

Here's the list of currently desired features by both me and Sergey:
- some static (or close to) page technology
- something easy for our users to modify if they see a bug on the page. 
- needs to host: api reference, tutorials
- api reference is done in doxygen. Doxygen generates its own htlm so not much to say here. I would like expose some sort of dropdown selector to allow selecting for different versions easily.
- something which parses rst files, which is the format of all our tutorials and random blog post related to old GSOC initiatives. I have to say that I would like to have our tutorials tagged to specific versions. What I'm noticing that is happening is that when we apply changes on master, some of them are immediately reflected on the tutorials page and we end up with tutorials there which only work with master and not the current stable release. In my ideal world, tutorials are also bound to specific pcl versions.

Everyone can contribute at this stage by:
1. scrutinize these proposals and I'll update things based on the discussion.
2. start identifying potential technologies and frameworks that meet these criteria
3. come up with proofs of concept incorporating the item we've discussed.

Let me know in case you feel like I missed anything.

**Comment by andre-nguyen** [comment] 2019-06-11 19:10
Most if not all of these requirements sound like they could be addressed by a chain of Github + [Breathe](https://github.com/michaeljones/breathe)  + [Sphinx](http://www.sphinx-doc.org/en/master/). The Sphinx website itself is built using sphinx and you can see the version selector on the bottom right. The only point I'm not entirely sure of is your last one about tutorials. But I am guessing you could have .rst tutorials in a docs folder.

**Comment by SergioRAgostinho** [comment] 2019-06-12 07:24
> But I am guessing you could have .rst tutorials in a docs folder.

That is currently the case. https://github.com/PointCloudLibrary/pcl/tree/master/doc/tutorials/content

**Comment by markuspi** [comment] 2019-11-21 11:47
The website is still redirecting to shady ad websites at least once a day (maybe per IP?). This is extremely concerning.

Request:
`$ curl 'http://pointclouds.org/' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' --compressed -H 'Referer: https://www.google.com/' -H 'Connection: keep-alive'`

Response:
```
<html>
<head>
    <META http-equiv="refresh" content="1;URL=http://sweeps9082.nonamecurl84.live/?utm_campaign=bKMuT7EMVXU5Z6UvvSHONGlfu-yV43iC8T8uYixAFxs1&t=main9_3c060f031c165b180a6e2a3b">
    <script>
        window.location = "http://sweeps9082.nonamecurl84.live/?utm_campaign=bKMuT7EMVXU5Z6UvvSHONGlfu-yV43iC8T8uYixAFxs1&t=main9_3c060f031c165b180a6e2a3b";
    </script>
</head>
<body>
    To the new location please <a href="http://sweeps9082.nonamecurl84.live/?utm_campaign=bKMuT7EMVXU5Z6UvvSHONGlfu-yV43iC8T8uYixAFxs1&t=main9_3c060f031c165b180a6e2a3b"><b>click here.</b></a>
</body>
</html>
```

**Comment by SergioRAgostinho** [comment] 2019-11-21 12:54
Ping @rbrusu .

**Comment by rbrusu** [comment] 2019-11-21 17:02
unfortunately i have no time to update modx (which has been a complete nightmare of a CMS in general), so we'd need to start with a fresh new page instead. If someone can volunteer to build one, i can simply point pointclouds.org to it.

**Comment by tangbao** [comment] 2019-11-21 17:11
> unfortunately i have no time to update modx (which has been a complete nightmare of a CMS in general), so we'd need to start with a fresh new page instead. If someone can volunteer to build one, i can simply point pointclouds.org to it.

How about a website like [readthedocs](https://readthedocs.org/)? It is good for tutorials and documentation, but not good for a nice-looking front page for presentation. Also, the source files of the website can be stored on github and the website can be hosted by readthedocs, then we don't need to worry about the server things.

**Comment by jackjansen** [comment] 2019-11-21 23:06
As the OP, let me once more stress the fact that pointclouds.org as it is today does _much_ more harm than good. If it was taken down then a search for "pcl pointclouds" would direct people to the GitHub homepage. 

I fully understand that everyone is busy (I'm in quite a few open source projects myself, I know how it goes:-), but simply taking down the site or having it redirect to https://github.com/PointCloudLibrary/pcl shouldn't be too much work....

**Comment by SergioRAgostinho** [comment] 2019-11-27 08:53
I intend to pick up on the issue once this next release complete.

**Comment by schaten** [comment] 2020-02-17 10:44
I have just discovered this library.
At the moment you google point cloud library, happy that you found it on Wikipedia, and the first result randomly directs you to a generic scam website. And from what I read here this has been going on for _months_.

I do understand that writing code is more fun. But from my point of view, more important than any release now is that someone having a hold on this project pulls the brake _now_ and fixes the website and more important the underlying organizational problems having led to this situation.

Guys, seriously! Who has the credentials for the webhosting/-server?
That is beyond careless considering whatever malware might come with that scam page. Shut it down now! Please.
No one new to this will trust the code if the website isn't even under control!

It's really sad! Because this seems like a great project and obviously a lot of time has been invested.
I hope you can sort this out together.

**Comment by taketwo** [comment] 2020-02-17 10:55
> Shut it down now! Please.

Documentation and tutorials are hosted there, we can not just shut it down.

**Comment by kunaltyagi** [comment] 2020-02-17 10:56
> we can not just shut it down.

Can we use HTTPS? That might help.. a bit

**Comment by schaten** [comment] 2020-02-17 11:14
I'd suggest to create a (dead simple, plain html) page e.g. with github pages which just consists of:
- A link to a recent, hopefully spam-free archive.org capture, e.g. https://web.archive.org/web/20191126111900/http://pointclouds.org/ .
- A short note stating that the new website is being developed, and whom to contact for donations / contributions / ...
- In the future: A link to the yet-to-come development version of the page.

I have to say I'm wondering this is even a debate.
So whoever hijacked the page left it in a half-working fashion. Only the first two attempts to visit the page from a given IP seem to get redirected.
So it looks like this is still acceptable. You forget the problem after pressing F5 a few times.
But it really isn't! The page is hijacked, and who knows what else is going on on that webserver!

And apparently this idea works out fabulously because pointclouds.org os still redirecting people to that scam site even after months! :/

**Comment by JoeNatan30** [comment] 2020-03-05 18:19
> I'd suggest to create a (dead simple, plain html) page e.g. with github pages which just consists of:
> 
> * A link to a recent, hopefully spam-free archive.org capture, e.g. https://web.archive.org/web/20191126111900/http://pointclouds.org/ .
> * A short note stating that the new website is being developed, and whom to contact for donations / contributions / ...
> * In the future: A link to the yet-to-come development version of the page.
> 
> I have to say I'm wondering this is even a debate.
> So whoever hijacked the page left it in a half-working fashion. Only the first two attempts to visit the page from a given IP seem to get redirected.
> So it looks like this is still acceptable. You forget the problem after pressing F5 a few times.
> But it really isn't! The page is hijacked, and who knows what else is going on on that webserver!
> 
> And apparently this idea works out fabulously because pointclouds.org os still redirecting people to that scam site even after months! :/

In general, when I want to access a hijacked website, I click on "translate this page" button (google option). This step avoids this annoying redirection. Then click on Original language option.

**Comment by wz18207** [comment] 2020-03-14 17:40
If possible, I would like to try to fix this site.
But unfortunately, I am now located in Xi'an. Due to the limitation of the regional network, it will be difficult for me to check the URL and try to fix it. I'm currently trying my best to support this.

**Comment by AugmentedGeoBae** [comment] 2020-04-05 17:52
I was looking at how to do it as a site on Github Pages. The main pages would be built with Jekyll as static content and the documentation similarly built from their RST/ Doxygen components as static elements, to be then bundled together and served from a gh-pages repository branch.
Updates to "News", "Tutorial", "Blog", "Media", "Jobs" would be conducted like writing blog posts from local machine as a draft then built in Jekyll and pushed to the server.

**Comment by SergioRAgostinho** [comment] 2020-05-03 17:17
New webpage at https://pointcloudlibrary.github.io/, eventually it should move to pointclouds.org just like before.  The issue is "technically fixed" since the older website is no more.

**Closed** 2020-05-03 17:17 UTC
Labels: kind: todo
