### ISSUE TITLE
ApproximateProgressiveMorphologicalFilter: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed

### ISSUE THREAD

**Issue by JereKnuutinen** [PointCloudLibrary/pcl#5728] opened 2023-05-29 05:47 UTC
For some reason I get:

/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:364: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index, Eigen::Index) [with Derived = Eigen::Matrix<float, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = float; Eigen::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
while using ApproximateProgressiveMorphologicalFilter.
my code is following:

    // Concatenate point clouds
    //pcl::PointCloud<pcl::PointXYZRGB>::Ptr merged_pc(new pcl::PointCloud<pcl::PointXYZRGB>);
    pcl::PointCloud<pcl::PointXYZ>::Ptr merged_pc(new pcl::PointCloud<pcl::PointXYZ>);

    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered (new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PointIndicesPtr ground (new pcl::PointIndices);

    pcl::concatenate(*pcl_pc1, *pcl_pc2_transformed, *merged_pc);

    pcl::ApproximateProgressiveMorphologicalFilter<pcl::PointXYZ> pmf;
    pcl::ExtractIndices<pcl::PointXYZ> extract;
    pmf.setInputCloud (merged_pc);
    pmf.setMaxWindowSize (10);
    pmf.setSlope (1.0f);
    pmf.setInitialDistance (0.5f);
    pmf.setMaxDistance (3.0f);
    pmf.extract (ground->indices);

    extract.setInputCloud (merged_pc);
    extract.setIndices (ground);
    extract.filter (*cloud_filtered);
    
  This error happens in     pmf.extract (ground->indices); line. Normal progressive_morphological_filter works fine but I need to use approximate version since it is much faster.

**Comment by mvieth** [comment] 2023-05-29 08:18
@JereKnuutinen Hi, I tried to reproduce the error but was unable to do so. Please either post the point cloud `merged_pc` as a PCD or PLY file, or post a backtrace from gdb, valgrind, or similar.

**Comment by JereKnuutinen** [comment] 2023-06-06 05:24
Apparently, the problem was solved by removing NaN values.

**Comment by mvieth** [comment] 2023-06-06 11:37
> Apparently, the problem was solved by removing NaN values.

Thanks for the follow-up. Then I have an idea where the problem is and will try to push a fix sometime.

**Closed** 2023-07-07 12:09 UTC
Labels: kind: bug, module: segmentation
