### ISSUE TITLE
[compile error] error LNK2019: unresolved external symbol of QVTKWidget

### ISSUE THREAD

**Issue by WangZP10969** [PointCloudLibrary/pcl#3810] opened 2020-03-27 03:08 UTC
Hi, Sir
I am using PCL + QT for development. In the previous PCL1.9.1+VTK8.1, the test routine qt_visualizer was normal, and in the new PCL1.10.1+VTK8.2, the compilation routine produced the following error prompt:
```
1>------ Build started: Project: pcl_visualizer, Configuration: Debug x64 ------
1>Automatic MOC and UIC for target pcl_visualizer
1>pclviewer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QVTKWidget::QVTKWidget(class QWidget *,class QFlags<enum Qt::WindowType>)" (__imp_??0QVTKWidget@@QEAA@PEAVQWidget@@V?$QFlags@W4WindowType@Qt@@@@@Z) referenced in function "public: void __cdecl Ui_PCLViewer::setupUi(class QMainWindow *)" (?setupUi@Ui_PCLViewer@@QEAAXPEAVQMainWindow@@@Z)
1>pclviewer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl QVTKWidget::~QVTKWidget(void)" (__imp_??1QVTKWidget@@UEAA@XZ) referenced in function "public: virtual void * __cdecl QVTKWidget::`scalar deleting destructor'(unsigned int)" (??_GQVTKWidget@@UEAAPEAXI@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual class QVTKInteractor * __cdecl QVTKWidget::GetInteractor(void)" (?GetInteractor@QVTKWidget@@UEAAPEAVQVTKInteractor@@XZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual class vtkRenderWindow * __cdecl QVTKWidget::GetRenderWindow(void)" (?GetRenderWindow@QVTKWidget@@UEAAPEAVvtkRenderWindow@@XZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl QVTKWidget::SetRenderWindow(class vtkRenderWindow *)" (?SetRenderWindow@QVTKWidget@@UEAAXPEAVvtkRenderWindow@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual class vtkImageData * __cdecl QVTKWidget::cachedImage(void)" (?cachedImage@QVTKWidget@@UEAAPEAVvtkImageData@@XZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::contextMenuEvent(class QContextMenuEvent *)" (?contextMenuEvent@QVTKWidget@@MEAAXPEAVQContextMenuEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::deferRender(void)" (?deferRender@QVTKWidget@@MEAAXXZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::doDeferredRender(void)" (?doDeferredRender@QVTKWidget@@MEAAXXZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::dragEnterEvent(class QDragEnterEvent *)" (?dragEnterEvent@QVTKWidget@@MEAAXPEAVQDragEnterEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::dragLeaveEvent(class QDragLeaveEvent *)" (?dragLeaveEvent@QVTKWidget@@MEAAXPEAVQDragLeaveEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::dragMoveEvent(class QDragMoveEvent *)" (?dragMoveEvent@QVTKWidget@@MEAAXPEAVQDragMoveEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::dropEvent(class QDropEvent *)" (?dropEvent@QVTKWidget@@MEAAXPEAVQDropEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::enterEvent(class QEvent *)" (?enterEvent@QVTKWidget@@MEAAXPEAVQEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual bool __cdecl QVTKWidget::event(class QEvent *)" (?event@QVTKWidget@@MEAA_NPEAVQEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::focusInEvent(class QFocusEvent *)" (?focusInEvent@QVTKWidget@@MEAAXPEAVQFocusEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::focusOutEvent(class QFocusEvent *)" (?focusOutEvent@QVTKWidget@@MEAAXPEAVQFocusEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl QVTKWidget::isAutomaticImageCacheEnabled(void)const " (?isAutomaticImageCacheEnabled@QVTKWidget@@UEBA_NXZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::keyPressEvent(class QKeyEvent *)" (?keyPressEvent@QVTKWidget@@MEAAXPEAVQKeyEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::keyReleaseEvent(class QKeyEvent *)" (?keyReleaseEvent@QVTKWidget@@MEAAXPEAVQKeyEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::leaveEvent(class QEvent *)" (?leaveEvent@QVTKWidget@@MEAAXPEAVQEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual double __cdecl QVTKWidget::maxRenderRateForImageCache(void)const " (?maxRenderRateForImageCache@QVTKWidget@@UEBANXZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __cdecl QVTKWidget::metaObject(void)const " (?metaObject@QVTKWidget@@UEBAPEBUQMetaObject@@XZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::mouseMoveEvent(class QMouseEvent *)" (?mouseMoveEvent@QVTKWidget@@MEAAXPEAVQMouseEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::mousePressEvent(class QMouseEvent *)" (?mousePressEvent@QVTKWidget@@MEAAXPEAVQMouseEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::mouseReleaseEvent(class QMouseEvent *)" (?mouseReleaseEvent@QVTKWidget@@MEAAXPEAVQMouseEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::moveEvent(class QMoveEvent *)" (?moveEvent@QVTKWidget@@MEAAXPEAVQMoveEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual bool __cdecl QVTKWidget::nativeEvent(class QByteArray const &,void *,long *)" (?nativeEvent@QVTKWidget@@MEAA_NAEBVQByteArray@@PEAXPEAJ@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual bool __cdecl QVTKWidget::paintCachedImage(void)" (?paintCachedImage@QVTKWidget@@MEAA_NXZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual class QPaintEngine * __cdecl QVTKWidget::paintEngine(void)const " (?paintEngine@QVTKWidget@@UEBAPEAVQPaintEngine@@XZ)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::paintEvent(class QPaintEvent *)" (?paintEvent@QVTKWidget@@MEAAXPEAVQPaintEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual int __cdecl QVTKWidget::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@QVTKWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual void * __cdecl QVTKWidget::qt_metacast(char const *)" (?qt_metacast@QVTKWidget@@UEAAPEAXPEBD@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::resizeEvent(class QResizeEvent *)" (?resizeEvent@QVTKWidget@@MEAAXPEAVQResizeEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl QVTKWidget::setAutomaticImageCacheEnabled(bool)" (?setAutomaticImageCacheEnabled@QVTKWidget@@UEAAX_N@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl QVTKWidget::setMaxRenderRateForImageCache(double)" (?setMaxRenderRateForImageCache@QVTKWidget@@UEAAXN@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl QVTKWidget::showEvent(class QShowEvent *)" (?showEvent@QVTKWidget@@UEAAXPEAVQShowEvent@@@Z)
1>pclviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl QVTKWidget::wheelEvent(class QWheelEvent *)" (?wheelEvent@QVTKWidget@@MEAAXPEAVQWheelEvent@@@Z)
1>C:\FILE\qt_visualizer\Build\Debug\pcl_visualizer.exe : fatal error LNK1120: 38 unresolved externals
1>Done building project "pcl_visualizer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
Later, I tried to change back to PCL1.9.1 + VTK8.1, and the routine became normal again.
I configured the two versions in the same way:
1. Install PCL
2. Compile VTK and select VTK_Group_Qt
3. Replace the pre-compiled VTK folder in PCL with the compiled VTK
4. Put the compiled QVTK dynamic library into the plugin folder of QT
5. Use cmake build the project and use visual studio to test

QT is 5.14.1, cmake is 3.17.0, visual studio is 16.3.3(2019)

Would help me to slove this problem?I don't know how to proceed 
Thank you very much！

**Comment by WangZP10969** [comment] 2020-04-02 08:56
I tried cross-testing PCL1.9.1, PCL1.10.1 and VTK8.1, VTK8.2, QT platforms are all 5.14.1
1. PCL1.10.1 + VTK8.1 and PCL1.10.1 + VTK8.2 will prompt the problem that QVTK unresolved external symbol
2. PCL1.9.1 + VTK8.1 runs normally
3. PCL1.9.1 + VTK8.2, error C2039: "ImmediateModeRenderingOff": Not a member of "vtkMapper"

I think PCL1.9.1 does not support VTK8.2, but PCL1.10.1 may not support VTK8.1 & 8.1 due to some features.

**Comment by kunaltyagi** [comment] 2020-04-02 11:45
Thanks for testing @WangZP10969 . Can you reproduce this in Linux also (eg: using the docker `pointcloudlibrary/env:16.04`)

**Comment by WangZP10969** [comment] 2020-04-07 02:08
> Thanks for testing @WangZP10969 . Can you reproduce this in Linux also (eg: using the docker `pointcloudlibrary/env:16.04`)? Just to ensure that MSVC isn't an outlier.

I'm sorry, I don't understand development under linux, I have never used this system before.

**Comment by WangZP10969** [comment] 2020-05-02 13:00
> Thanks for testing @WangZP10969 . Can you reproduce this in Linux also (eg: using the docker `pointcloudlibrary/env:16.04`)? Just to ensure that MSVC isn't an outlier.

I have spent a lot of time on this, and still no success. I do n’t think I can continue to spend time. I think it may be necessary to transition from QVTKWidget to QVTKNativeOpenGLWidget. This is the way VTK respects. Perhaps we need a PCL example to achieve this, and the libraries required by QT are recommended to be added to the PCL binary installation package by default to reduce the configuration difficulty.

**Comment by jafrado** [comment] 2020-05-03 22:48
It works fine. You have to build VTK with the defines:
```
   -DVTK_Group_Qt=ON  -DvtkGUISupportQtOpenGL=ON -DModule_vtkGUISupportQtOpenGL=ON -DVTK_QT_VERSION=5
```
Here's a test app : https://github.com/jafrado/QVTKOpenGLWidget

And here's a pending fix for vcpkg, please vote on it and try it out.
https://github.com/microsoft/vcpkg/issues/10027

FYI, this is not a PCL issue, but one with VTK.

**Comment by jafrado** [comment] 2020-05-03 22:49
And yes, you can also use a QVTKNativeOpenGLWidget (and will be required if you want an MDI or Docking QT window), however, you will need to build VTK as above regardless to pick up that module.

**Comment by jafrado** [comment] 2020-05-03 22:53
I see, Windows, older VS tools. yech. Use VS 2019, try vcpkg (with my patch), and you're off to the races.

**Comment by WangZP10969** [comment] 2020-05-04 04:20
> 它工作正常。您必须使用以下定义来构建VTK：
> 
> ```
>    -DVTK_Group_Qt=ON  -DvtkGUISupportQtOpenGL=ON -DModule_vtkGUISupportQtOpenGL=ON -DVTK_QT_VERSION=5
> ```
> 
> 这是一个测试应用程序：[https](https://github.com/jafrado/QVTKOpenGLWidget) : [//github.com/jafrado/QVTKOpenGLWidget](https://github.com/jafrado/QVTKOpenGLWidget)
> 
> 这是vcpkg的待解决方法，请对其投票并尝试一下。
> [微软/ vcpkg＃10027](https://github.com/microsoft/vcpkg/issues/10027)
> 
> 仅供参考，这不是PCL问题，而是VTK问题。

Thank you very much for your reply, I will try your compilation method for testing.
In the previous QVTKWidget test, I tried to use VTK's QtEvents example, which is an example of VTK using QVTKWidget. When I refer to my own compiled VTK in the PCL path, it works normally. When the PCL reference dependency is added to the CMakelists file, it suddenly becomes unusable. I don't understand this, it may be a conflict between VTK and PCL, but I don't know how to solve it.

**Comment by jafrado** [comment] 2020-05-04 07:09
If you're using Linux, it's much easier. Here's an excerpt from an old Makefile:

```

all:
	mkdir -p build && cd build && \
	cmake ../VTK-8.2.0 \
	-DCMAKE_PREFIX_PATH:PATH=/home/jfd/Qt5.12/5.12.5/gcc_64/lib/cmake \
	-G "Unix Makefiles"  \
	-DBUILD_EXAMPLES:BOOL=ON \
	-DVTK_USE_X:BOOL=ON \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
	-DVTK_OPENGL_HAS_OSMESA:BOOL=ON \
	-DOSMESA_INCLUDE_DIR=/usr/include/GL\
	-DOSMESA_LIB_DIR=/usr/lib/x86_64-linux-gnu/mesa\
	-DVTK_Group_Qt:BOOL=ON \
	-DModule_vtkGUISupportQt:BOOL=ON \
	-DModule_vtkGUISupportQtOpenGL:BOOL=ON \
	-DModule_vtkRenderingQt:BOOL=ON \
	-DModule_vtkRenderingSceneGraph:BOOL=ON \
	-DModule_vtkImagingOpenGL2:BOOL=ON \
	-DModule_vtkViewsQt:BOOL=ON \
	-DVTK_USE_SYSTEM_HDF5:BOOL=ON \
	-DVTK_USE_SYSTEM_PNG:BOOL=ON

clean:
	rm -fr build
```

If you're on Windows, you'll want to run cmake-gui and input these by hand. I strongly urge you to use vcpkg and the patch I sent, it will make your life so much easier.

**Comment by WangZP10969** [comment] 2020-05-04 07:22
@kunaltyagi @jafrado 
Thank you very much for your suggestions and inspiration, I found a solution, I only need to modify CMakeLists

find_package (VTK REQUIRED)
find_package (PCL 1.7.1 REQUIRED)
...
target_link_libraries ($ {PROJECT_NAME} $ {PCL_LIBRARIES} Qt5 :: Widgets)

Change to

find_package (PCL 1.7.1 REQUIRED)
find_package (VTK REQUIRED)
...
target_link_libraries ($ {PROJECT_NAME} $ {PCL_LIBRARIES} $ {VTK_LIBRARIES} Qt5 :: Widgets)

This change will re-find VTK after searching for PCL, and add the link library to the project. In previous versions, such as PCL1.9.1 + VTK8.1.0, this is not necessary.
I don't know what has changed in the reference of the link library for PCL1.10.1 + VTK8.2.0, but it seems that this will make the program work properly.

**Comment by WangZP10969** [comment] 2020-05-04 07:32
> If you're using Linux, it's much easier. Here's an excerpt from an old Makefile:
> 
> ```
> 
> all:
> 	mkdir -p build && cd build && \
> 	cmake ../VTK-8.2.0 \
> 	-DCMAKE_PREFIX_PATH:PATH=/home/jfd/Qt5.12/5.12.5/gcc_64/lib/cmake \
> 	-G "Unix Makefiles"  \
> 	-DBUILD_EXAMPLES:BOOL=ON \
> 	-DVTK_USE_X:BOOL=ON \
>         -DCMAKE_INSTALL_PREFIX=/usr/local \
> 	-DVTK_OPENGL_HAS_OSMESA:BOOL=ON \
> 	-DOSMESA_INCLUDE_DIR=/usr/include/GL\
> 	-DOSMESA_LIB_DIR=/usr/lib/x86_64-linux-gnu/mesa\
> 	-DVTK_Group_Qt:BOOL=ON \
> 	-DModule_vtkGUISupportQt:BOOL=ON \
> 	-DModule_vtkGUISupportQtOpenGL:BOOL=ON \
> 	-DModule_vtkRenderingQt:BOOL=ON \
> 	-DModule_vtkRenderingSceneGraph:BOOL=ON \
> 	-DModule_vtkImagingOpenGL2:BOOL=ON \
> 	-DModule_vtkViewsQt:BOOL=ON \
> 	-DVTK_USE_SYSTEM_HDF5:BOOL=ON \
> 	-DVTK_USE_SYSTEM_PNG:BOOL=ON
> 
> clean:
> 	rm -fr build
> ```
> 
> If you're on Windows, you'll want to run cmake-gui and input these by hand. I strongly urge you to use vcpkg and the patch I sent, it will make your life so much easier.

Thank you very much, I will test. Although QVTKWidget can work normally now, after all, QVTKOpenGLWidget and QVTKNativeOpenGLWidget may do better. Your information is very valuable for me.

**Comment by kunaltyagi** [comment] 2020-05-04 07:56
> I don't know what has changed in the reference of the link library for PCL1.10.1 + VTK8.2.0, but modifying the CMakelist seems to make the program work normally.

@PointCloudLibrary/maintainers flagging a potential issue in CMake here.

**Comment by larshg** [comment] 2020-05-16 08:02
It seems that VTK wasn't correctly build with QVTK, so the appropriate library was not added to linking.

I highly doubt its the order of FindLibrary PCL / VTK as PCL should point to the same VTK as findLibrary wold find.

**Comment by Yourbee** [comment] 2021-03-16 07:12
> @kunaltyagi @jafrado
> Thank you very much for your suggestions and inspiration, I found a solution, I only need to modify CMakeLists
> 
> find_package (VTK REQUIRED)
> find_package (PCL 1.7.1 REQUIRED)
> ...
> target_link_libraries ($ {PROJECT_NAME} $ {PCL_LIBRARIES} Qt5 :: Widgets)
> 
> Change to
> 
> find_package (PCL 1.7.1 REQUIRED)
> find_package (VTK REQUIRED)
> ...
> target_link_libraries ($ {PROJECT_NAME} $ {PCL_LIBRARIES} $ {VTK_LIBRARIES} Qt5 :: Widgets)
> 
> This change will re-find VTK after searching for PCL, and add the link library to the project. In previous versions, such as PCL1.9.1 + VTK8.1.0, this is not necessary.
> I don't know what has changed in the reference of the link library for PCL1.10.1 + VTK8.2.0, but modifying the CMakelist seems to make the program work normally.

works for me.
PCL 1.11.1 All-in-one, VTK-8.2.0 5.9.9

**Comment by larshg** [comment] 2021-05-26 14:26
Closing as I don't think its a bug in PCL.

**Closed by larshg** 2021-05-26 14:26 UTC
Labels: kind: compile error, module: cmake, needs: feedback, platform: windows
