### ISSUE TITLE
boost 1.73.0 breaks PCLPointCloud2 due to change in location of endian header

### ISSUE THREAD

**Issue by crissallan** [PointCloudLibrary/pcl#4302] opened 2020-08-03 08:41 UTC
**Describe the bug**
Since there is no endian.hpp file in boost/include/detail/ in boost1.73.0(installed by homebrew on MacOS)
So most of the PCL api will raise an error. 

**Your Environment (please complete the following information):**

 - OS: [MacOS Catalina]
 - Compiler: [g++]
 - PCL Version [e.g. 1.9.1, HEAD] which is also intalled by homebrew

How should I solve this problem

**Comment by kunaltyagi** [comment] 2020-08-03 09:04
This should be handled by brew. Else you should install PCL or boost manually.

Closing as not a bug

**Comment by hsawano** [comment] 2020-08-06 23:18
I confirmed this problem in MacOS.
In PCLPointCloud2.h, the including location of endian.hpp in boost is written as follows.
`#include <boost/detail/endian.hpp>`

The actual location is written as follows.
`#include <boost/endian.hpp>`

However, if I changed the location, the compile cannot be completed because ENDIAN of boost is not clear.
The following error is written.
`#error "unable to determine system endianness"`
The error code is written in the PCLPointCloud2.h.

Is this brew issue?

**Comment by hsawano** [comment] 2020-08-07 00:07
In the original boost source, the endian.hpp is moved.
https://www.boost.org

Therefore, PCLPointCloud2.h has bugs, right?

**Comment by kunaltyagi** [comment] 2020-08-07 00:16
PCL has already updated the header and now includes `boost/predef/other/endian.h` instead of `boost/endian.hpp`

As a result, it's upto the distributors to keep PCL patched if they don't update PCL to more recent versions.

Speaking of which, Homebrew might release 1.11 soon, so the problem should go away. :crossed_fingers:

**Comment by hsawano** [comment] 2020-08-07 01:07
Oh, it's nice answer!

**Comment by hsawano** [comment] 2020-08-07 01:20
@kunaltyagi 
Do you know when homebrew will be updated?

**Comment by hsawano** [comment] 2020-08-07 04:24
I installed PCL from source without homebrew.
However, the same problem exists.

How can I get the patch of PCL?

**Comment by kunaltyagi** [comment] 2020-08-07 05:21
I'm unable to get boost 1.73

This issue is not present on boost 1.72

**Comment by hsawano** [comment] 2020-08-07 07:45
I installed PCL 1.11 and boost 1.72 from sources in MacOS.
I can compile them without errors, and sample codes are also compiled.

**Comment by SergioRAgostinho** [comment] 2020-08-07 07:50
> @kunaltyagi
> Do you know when homebrew will be updated?

You can track this pr https://github.com/Homebrew/homebrew-core/pull/59146 to keep yourself up to date

**Comment by crissallan** [comment] 2020-08-07 07:50
> I installed PCL 1.11 and boost 1.72 from sources in MacOS.
> I can compile them without errors, and sample codes are also compiled.

cool! Could you please share the installization tutorial? Besides, I also would like to know that whether this PCL which built from source could be detected by Hombrew(by entering "brew info pcl")?

**Comment by hsawano** [comment] 2020-08-07 08:03
@crissallan 
First, PCL and boost must be uninstalled in Homebrew.
```
brew uninstall pcl
brew uninstall brew
```

After that, boost 1.72 will be download and installed from the following URL.
https://www.boost.org/users/history/version_1_72_0.html
The install commands are written as follows.
```
./bootstrap.sh
./b2 install -j2 --prefix=/usr/local
```

After installing boost, you can download PCL 1.11 from the Web.
https://github.com/PointCloudLibrary/pcl
How to the installization is written.
https://pcl-tutorials.readthedocs.io/en/latest/compiling_pcl_macosx.html
The item Building PCL.

Thank you

**Closed** 2020-08-07 08:18 UTC
Labels: kind: bug, module: common, needs: testing

**Comment by mdemirst** [comment] 2020-08-13 23:28
If you don't need to install from source, you can follow this link to install older version brew packages  https://itnext.io/how-to-install-an-older-brew-package-add141e58d32

I installed PCL 1.8.1 and Boost 1.72 and had no issues

**Comment by kunaltyagi** [comment] 2020-08-14 02:24
PS: No issues with PCL 1.11 an Boost 1.72
