### ISSUE TITLE
shared_ptr is not a template while building pcl 1.10.0

### ISSUE THREAD

**Issue by ken012git** [PointCloudLibrary/pcl#3728] opened 2020-03-10 11:20 UTC
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc-7
* PCL Version: pcl-1.10.0
* GPU: GeForce RTX 2060
* GPU Driver Version: 418.87.00
* CUDA Version: 10.1
* CUDA Capability Major/Minor version number:    7.5

## Context
Fail to build PCL 1.10.0

```
/home/hyc-pc/software/pcl/cuda/common/include/pcl/cuda/point_cloud.h(199): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/common/include/pcl/cuda/point_cloud.h(200): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/common/include/pcl/cuda/point_cloud.h(280): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/common/include/pcl/cuda/point_cloud.h(281): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/segmentation/src/connected_components.cu(85): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/segmentation/src/connected_components.cu(178): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/segmentation/src/connected_components.cu(179): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/common/include/pcl/cuda/point_cloud.h(199): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/common/include/pcl/cuda/point_cloud.h(200): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/common/include/pcl/cuda/point_cloud.h(280): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/common/include/pcl/cuda/point_cloud.h(281): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(53): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(54): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(70): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(91): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(119): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(119): error: invalid explicit instantiation declaration

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(119): error: expected a ";"

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(125): warning: parsing restarts here after previous syntax error

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(127): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(127): error: invalid explicit instantiation declaration

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(127): error: expected a ";"

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(133): warning: parsing restarts here after previous syntax error

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(144): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(144): error: invalid explicit instantiation declaration

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(144): error: expected a ";"

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(147): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(147): error: invalid explicit instantiation declaration

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(147): error: expected a ";"

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(169): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(169): error: invalid explicit instantiation declaration

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(169): error: expected a ";"

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(175): warning: parsing restarts here after previous syntax error

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(177): error: shared_ptr is not a template

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(177): error: invalid explicit instantiation declaration

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(177): error: expected a ";"

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(183): warning: parsing restarts here after previous syntax error

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(66): error: no instance of overloaded function "thrust::transform" matches the argument list
            argument types are: (thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, <error-type>, thrust::detail::normal_iterator<thrust::device_ptr<float4>>, pcl::cuda::FastNormalEstimationKernel<pcl::cuda::Device>)
          detected during instantiation of "void pcl::cuda::computeFastPointNormals<OutputIteratorT,Storage>(OutputIteratorT, const pcl::cuda::PointCloudAOS<Storage>::ConstPtr &) [with OutputIteratorT=thrust::detail::normal_iterator<thrust::device_ptr<float4>>, Storage=pcl::cuda::Device]" 
(136): here

/home/hyc-pc/software/pcl/cuda/features/src/normal_3d.cu(66): error: no instance of overloaded function "thrust::transform" matches the argument list
            argument types are: (thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, <error-type>, thrust::detail::normal_iterator<float4 *>, pcl::cuda::FastNormalEstimationKernel<pcl::cuda::Host>)
          detected during instantiation of "void pcl::cuda::computeFastPointNormals<OutputIteratorT,Storage>(OutputIteratorT, const pcl::cuda::PointCloudAOS<Storage>::ConstPtr &) [with OutputIteratorT=thrust::detail::normal_iterator<float4 *>, Storage=pcl::cuda::Host]" 
(140): here

28 errors detected in the compilation of "/tmp/tmpxft_00002035_00000000-15_normal_3d.compute_75.cpp1.ii".
CMake Error at pcl_cuda_features_generated_normal_3d.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/hyc-pc/software/pcl/build/cuda/features/CMakeFiles/pcl_cuda_features.dir/src/./pcl_cuda_features_generated_normal_3d.cu.o


cuda/features/CMakeFiles/pcl_cuda_features.dir/build.make:63: recipe for target 'cuda/features/CMakeFiles/pcl_cuda_features.dir/src/pcl_cuda_features_generated_normal_3d.cu.o' failed
make[2]: *** [cuda/features/CMakeFiles/pcl_cuda_features.dir/src/pcl_cuda_features_generated_normal_3d.cu.o] Error 1
CMakeFiles/Makefile2:2368: recipe for target 'cuda/features/CMakeFiles/pcl_cuda_features.dir/all' failed
make[1]: *** [cuda/features/CMakeFiles/pcl_cuda_features.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

Any help is going to be appreciated. 
Thanks!

**Comment by kunaltyagi** [comment] 2020-03-10 13:15
Resolved by f5a73dc472ebcf99aa472a4706f352e1ea72cc7b #3576. Duplicate of #3703 

Please wait for 1.10.1 if you don't want to use `HEAD@master`

**Closed by kunaltyagi** 2020-03-10 13:15 UTC
