### ISSUE TITLE
VoxelGrid::filter crash in VS2017

### ISSUE THREAD

**Issue by feliwir** [PointCloudLibrary/pcl#1949] opened 2017-07-24 13:23 UTC
Hey, PCL 1.8.1rc2 is crashing for me with VS2017 Win64 Debug. It doesn't happen in Release
The crash seems to occur in filter.h when the output_temp variable goes out of scope:
``` c++
        if (input_.get () == &output)  // cloud_in = cloud_out
        {
          PointCloud output_temp;
          applyFilter (output_temp);
          output_temp.header = input_->header;
          output_temp.sensor_origin_ = input_->sensor_origin_;
          output_temp.sensor_orientation_ = input_->sensor_orientation_;
          pcl::copyPointCloud (output_temp, output);
        }
```
When diving deeper into the code it seems that std::free is crashing somewhere in Memory.h

The code to reproduce this issue is the following:
``` c++
  pcl::PointCloud<pcl::PointNormal>::Ptr cloud(new  pcl::PointCloud<pcl::PointNormal>());
  cloud->push_back(pcl::PointNormal());
  pcl::VoxelGrid<pcl::PointNormal> grid;
  grid.setLeafSize(0.005, 0.005, 0.005);
  grid.setInputCloud(cloud);
  grid.filter(*cloud);
```

Maybe someone can test that code and confirm that it crashes in the same configuration. Thanks

**Comment by feliwir** [comment] 2017-07-24 13:52
this seems somewhat related to pcl::copyPointCloud and smart pointers i also get a crash with that when not using filter

**Comment by SergioRAgostinho** [comment] 2017-07-24 18:05
Can you provide a self contained final stripped down example?

**Comment by feliwir** [comment] 2017-07-25 07:54
The sample code i gave in the first example is a minimal example of a crash

**Comment by SergioRAgostinho** [comment] 2017-07-25 17:32
What is `PointNT` on that snippet?

**Comment by feliwir** [comment] 2017-07-25 18:07
Ah forgot to replace that. Its a typedef to pcl::PointNormal

**Comment by UnaNancyOwen** [comment] 2017-07-27 13:45
Can you provide full source code and input data for reproduce this problem? I will test it.

**Comment by SergioRAgostinho** [comment] 2017-07-27 16:21
The second code snippet should be enough @UnaNancyOwen. It's self contained.

**Comment by UnaNancyOwen** [comment] 2017-07-27 16:49
I tried it, but it ran successfully. It didn't crash on my environment.
@feliwir Please tell me your compiler version. I confirmed it at 19.10.25019.0.

**Comment by feliwir** [comment] 2017-07-28 12:21
@UnaNancyOwen as mentioned in the first post i use: Visual Studio 2017 in x64 with Debug. That's also the only configuration i'm crashing with.  I am using pcl 1.8.1 rc2, Binaries were download here from github releases

**Comment by UnaNancyOwen** [comment] 2017-07-28 13:41
@feliwir Sorry, my question was insufficient.
I suspect a bug in the compiler of old version.
Visual Studio 2017 has been published several updates.
(The latest version is Update 2.)
If your compiler version is old, Please update and retry.

https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio

Please check the C++ compiler version of Visual Studio 2017.
It will be displayed on output area when first time configure using CMake.
```
The CXX compiler identification is MSVC 19.10.25019.0
```
Or, Please tell me the IDE version of Visual Studio 2017.
You can check it from [Help]>[About Microsoft Visual Studio].
```
Microsoft Visual Studio Enterprise 2017
Version 15.2 (26430.6) Release
```

**Comment by feliwir** [comment] 2017-07-28 14:22
Here is my version: 
```
Microsoft Visual Studio Community 2017
Version 15.2 (26430.16) Release
```

**Comment by UnaNancyOwen** [comment] 2017-07-28 15:06
@feliwir I updated to the same version as you. And I was retry it, but it works successfully.
Can you reconfigure the development environments and try it again? (from regenerate your own project using CMake.)

**Comment by SergioRAgostinho** [comment] 2017-08-02 23:58
It's been almost a week since the last ping. I propose ignore this for now and move with the release.

@feliwir  if you have any more feedback to provide, now it's definitely the time, otherwise this will be moved to another release milestone.

**Comment by UnaNancyOwen** [comment] 2017-08-03 01:16
@SergioRAgostinho I think that's fine.

**Comment by UnaNancyOwen** [comment] 2017-08-07 10:40
@feliwir We change milestone of this pull request to pcl-1.9.0 in order to release PCL 1.8.1.
We ask for your continued report. Thanks,

**Comment by SergioRAgostinho** [comment] 2017-11-26 16:46
I'm closing this for now. I have the impression it might be another manifestation of incorrect SSE flags being passed between the compiled PCL and the downstream target.

**Closed by SergioRAgostinho** 2017-11-26 16:46 UTC
Labels: platform: windows
