### ISSUE TITLE
pcl::NormalRobustEstimation - computing robust normals at the origin

### ISSUE THREAD

**Issue by pmdifran** [PointCloudLibrary/pcl#4965] opened 2021-09-30 16:56 UTC
This has been covered in the following issue, and PR, but changes were never merged:
#2403 
#3169 

**Context**

Contrary to most point clouds for robotics applications, in point clouds from topographic scanning, we often find ourselves very far from the origin. Either: (1) the target is far away from the scanner (i.e. scanner=origin), or (2) the datasets are immensely large, where some parts of the point cloud will be far enough from the origin. 

The issue with the current point-normal estimations, is that they do not transfer the point cloud to the origin, prior to demeaning the neighborhood during the mean & covariance matrix computation. This, as shown in the figure later, has been shown to cause catastrophic cancellation, resulting in poor normals (on large datasets, or datasets far from the origin, or both). 

I think supporting robust normal calculations will make pcl more open for topographic applications. Some of these users, like myself, work with huge datasets and are also motivated to add more HPC functionality into pcl!

Refer to #2403 to see images showing this behavior.

**Expected behavior**

We get proper normal calculations.

**Current Behavior**
Far from the origin, we don't!

@msy22 diagnosed the issue and created this image:
![PCLcovarianceCancellation](https://user-images.githubusercontent.com/64287741/135484315-10023dd9-2389-42a6-aee1-b580c899eb24.jpeg)

There is a fix to do transfer the neighborhood to the origin prior to `pcl::computeNormal`, however it will be best if we can do this in place in `pcl::computeMeanAndCovariance`.

**The solution**

Create the underlying `computeMeanAndRobustCovariance` function, which will be used to to transform the neighborhood to the origin in place.

Methods:
`pcl::NormalRobustEstimation`
and
`pcl::NormalRobustEstimationOMP` 

will employ `computeMeanAndRobustCovariance` to estimate the normals, in a similar fashion to `pcl::NormalEstimation`; `pcl::NormalEstimationOMP`.

**Alternatives you've considered**

Create a more hacky solution, which manually transforms neighborhoods to the origin, and just provide this under pcl examples.

**Comment by pmdifran** [comment] 2021-10-05 21:47
@mvieth that sounds great. Let me know how I can help once we figure out the best course of action :)

**Comment by mvieth** [comment] 2021-10-12 20:10
Okay, here are my thoughts about the problem.
The issue is that normals are not correctly calculated and that the optimization function of the sample consensus plane model produces bad results, when the point cloud is far away from the origin. In both cases, the function `computeMeanAndCovarianceMatrix` from centroid.h(pp) is the root of the problem. The returned covariance matrix is more and more inaccurate, the further away the point cloud is from the origin. Although there are to my knowledge no issues documenting this, every function or class that uses `computeMeanAndCovarianceMatrix` may give bad results (e.g. `OrganizedMultiPlaneSegmentation`, `SampleConsensusModelRegistration`, `GridProjection`, and others).
So, how to solve this? Possible solutions:
1. replace the implementation of `computeMeanAndCovarianceMatrix` with a more accurate one. But which algorithm? It should be considered that this implementation was chosen initially because it is very fast. In PR #1407 it is replaced with a two-pass algorithm.
2. create individual solutions for each class that uses `computeMeanAndCovarianceMatrix`. PR #3169 proposes a covariance computation function that shifts the data, but only for the normal estimation, the other classes still have the problem.
3. use double precision instead of single precision (float) when calling `computeMeanAndCovarianceMatrix`. This will likely be slower, but by how much?
4. shift the whole cloud to the origin at the start of each class, e.g. at the start of `NormalEstimation`. This is IMO rather inelegant, uses more memory, and would likely not work for large clouds (in contrast to small clouds that are only far away from the origin).

We need some experiments ([code on my branch as mentioned above](https://github.com/mvieth/pcl/tree/better_cov_testing)) ...

# Tests and benchmarks
I considered 4 algorithms, in detail also explained on [Wikipedia](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance):
1. Naive. This is the current implementation. Wikipedia warns that it "should not be used in practice"
2. Two-pass. First compute the mean, then compute the covariance while subtracting the mean from each point.
3. Shifted (also called "With estimate of the mean"). This uses only a single pass, but subtracts an estimate of the mean from each point. The better the estimate, the better the results, but even using any of the sample points makes the result good enough.
4. Welford's online algorithm. Single pass, updates an estimate of the current mean and covariance with each sample.

For accuracy tests, I created 3 scenarios:
1. varying number of points in the cloud
2. varying the distance of the cloud to the origin - this is probably the most interesting one, and the one described in the issues
3. varying the spread/covariance of the cloud

The input cloud is randomly generated from a normal distribution with the given parameters, the accuracy is the norm of the computed mean and covariance to a ground truth (which is computed by a two-pass algorithm with double precision). Here are the six plots (3 scenarios x mean and covariance accuracy each), careful, y-axes are logarithmic!:
![1](https://user-images.githubusercontent.com/39675748/137016330-91455566-a320-4952-83e8-41448a96d3a0.png)
![2](https://user-images.githubusercontent.com/39675748/137016338-5150f866-5036-4f86-8d3b-d62e8de0ee30.png)
![3](https://user-images.githubusercontent.com/39675748/137016350-664c171a-d871-4547-9106-28620166871f.png)
![4](https://user-images.githubusercontent.com/39675748/137016357-2a9da210-5ec4-4781-8a3e-17e2f5bcceb6.png)
![5](https://user-images.githubusercontent.com/39675748/137016371-6348d3a7-004e-4b2e-a610-c796b37fd8a4.png)
![6](https://user-images.githubusercontent.com/39675748/137016395-a4f62749-5ec6-44d8-8cdb-8e725457d6c9.png)

Interpretation:
1. this shows how bad the results from the naive algorithm can become. Especially in scenario 2.
2. the covariance results from twopass can also be quite bad, likely because the computed mean is not very good either.
3. shifted is often the best, or relatively close to the best.
4. welford is also quite good, but e.g. much worse when the cloud is far from the origin (scenario 2).

## Benchmarks
I benchmarked the algorithms with two large clouds (mug and milk), and smaller clouds with 50, 100, and 200 points, both when the clouds were marked as dense=true and dense=false (important for the `isFinite` check). Here are the results:
![7](https://user-images.githubusercontent.com/39675748/137016407-be31af7b-cfa2-4f1c-a5cd-bae0aa9792ab.png)
Dense cloud:
![8](https://user-images.githubusercontent.com/39675748/137016412-ebd77d28-b5ed-4b1a-8330-0f836b9e6ee5.png)
Non-dense cloud:
![9](https://user-images.githubusercontent.com/39675748/137016422-efbb3e47-9a52-41e6-9671-63ff656f3550.png)

Interpretation:
1. naive is indeed the fastest, but shifted is only a bit slower
2. twopass is slow, likely because it needs two passes (who would have thought :laughing: )
3. welford is slowest, likely because of the more complex operations for each point
4. note that the benchmark results are in microseconds (per call of `computeMeanAndCovarianceMatrix`)

Conclusion: shifted is a good candidate to replace the naive algorithm, it is much more accurate and only slightly slower (and still so fast that it probably does not matter, e.g. the search in the normal estimation takes much more time).

I have some more thoughts, but this is already quite long, I will continue probably tomorrow :wink: If you have questions/ideas/opinions, I look forward to hear them!

**Comment by mvieth** [comment] 2021-10-13 20:09
Thank you for your comments!
I also tested the accuracy of the naive algorithm (current implementation) in double precision (instead of float/single), compared to my ground truth (two-pass algorithm in double precision): The difference (error of the naive algorithm in double precision) is up to 10893.3 in scenario 2 (mean is far from origin). So I would say that simply switching the naive algorithm to double precision is still not accurate enough.
Regarding speed, the naive algorithm with double takes roughly twice as much time (sometimes a bit more, like 2.3 times as much) as the naive algorithm with single precision/float (compiled with march=native, which enables all SSE and AVX instructions on my computer). So definitely slower than the shifted algorithm with float/single precision.

> Would it be possible to have a benchmark with larger number of points foe the last 2 bar graps?

Is that not equivalent to the first benchmark with the clouds table_scene_mug_stereo_textured.pcd and milk_cartoon_all_small_clorox.pcd, each around 300,000 points? But anyway, here are naive and shifted again in direct benchmark comparison (mean +- std dev):
|                | naive (in us)  | shifted (in us) | factor
|-------------|----------------|-----------------|-------
| mug        | 703 +- 78      | 811 +- 16       | 1.15
| milk        | 699 +- 43      | 832 +- 11       | 1.19
| dense 50    | 0.098 +- 0.002 | 0.124 +- 0.001  | 1.27
| dense 100   | 0.183 +- 0.003 | 0.234 +- 0.002  | 1.28
| dense 200   | 0.349 +- 0.002 | 0.457 +- 0.004  | 1.31
| dense 1000  | 1.72 +- 0.019  | 2.25 +- 0.028   | 1.31
| !dense 50   | 0.122 +- 0.003 | 0.165 +- 0.001  | 1.35
| !dense 100  | 0.226 +- 0.004 | 0.317 +- 0.005  | 1.40
| !dense 200  | 0.434 +- 0.007 | 0.616 +- 0.004  | 1.42
| !dense 1000 | 2.24 +- 0.097  | 3.07 +- 0.059   | 1.37

So shifted is not _that_ much slower, only ~ 30%. And this is in the order of microseconds. So switching e.g. from naive to shifted for the NormalEstimation makes the computation take maybe 10-15 milliseconds longer, but the whole computation takes at least 800 milliseconds (single thread, 50 neighbors, more neighbors=longer). So this is IMO really negligible.

So yes, changing the algorithm of `computeMeanAndCovarianceMatrix` to work on the shifted data with an estimate of the mean is definitely something I would do. Unless you have any objections, I would create a pull request in a few days.

Other things we can/should do/could look into:
1. Is the [calculation of the curvature](https://github.com/PointCloudLibrary/pcl/blob/00a55faaa332c6ca1ebb7619ef6139e993464826/features/include/pcl/features/impl/feature.hpp#L86) correct? I think it should be the smallest eigenvalue, divided by the sum of all eigenvalues, but those are not the eigenvalues that are summed up?
2. The computed covariance matrix of `computeMeanAndCovarianceMatrix` is often given to `eigen33` (decomposition) to get the eigenvector corresponding to the smallest eigenvalue (not just normal estimation, but the other usages as well). I feel like there could be a more efficient solution where it is not necessary to explicitly compute the covariance matrix
3. We should put more warnings in eigen.hpp, [e.g. here](https://github.com/PointCloudLibrary/pcl/blob/00a55faaa332c6ca1ebb7619ef6139e993464826/common/include/pcl/common/impl/eigen.hpp#L58), when an eigenvalue is actually negative but set to zero
4. PR #3169 proposed the idea that in NormalEstimation, the points that are given to `computeMeanAndCovarianceMatrix` are always finite because they come from a NN search. Then the `isFinite` check for each point can be skipped, accelerating the computation. This can be done by setting `is_dense` of the cloud to true before passing it to `computeMeanAndCovarianceMatrix`, and restoring the original value afterwards.

**Comment by mvieth** [comment] 2021-12-02 13:33
Fixed by pull request #4983

**Closed by mvieth** 2021-12-02 13:33 UTC
Labels: module: features, kind: request, module: common

**Comment by extr15** [comment] 2022-04-25 07:50
Hi @mvieth , thanks for your work.
It seems you only modified the `computeMeanAndCovarianceMatrix`, while kept `computeCovarianceMatrix`. If I understand right, there are still some errors if we use `computeCovarianceMatrix` with float.
e.g. `sac_model_line.hpp`, 
```
  Eigen::Vector4f centroid;
  if (0 == compute3DCentroid (*input_, inliers, centroid))
  {
    PCL_WARN ("[pcl::SampleConsensusModelLine::optimizeModelCoefficients] compute3DCentroid failed (returned 0) because there are no valid inliers.\n");
    optimized_coefficients = model_coefficients;
    return;
  }
  Eigen::Matrix3f covariance_matrix;
  computeCovarianceMatrix (*input_, inliers, centroid, covariance_matrix);
```
Should this also be fixed?

And e.g. `gicp.hpp` has another `computeCovariances`, which also needs to be fixed?

**Comment by mvieth** [comment] 2022-04-25 12:23
@extr15 For `computeCovarianceMatrix`, I don't think there is still a problem. In one variant of `computeCovarianceMatrix` (the variant also used in sac_model_line), the function receives an estimated centroid and subtracts that from each point (demeaning the cloud before computing the covariance matrix). In [a second variant](https://github.com/PointCloudLibrary/pcl/blob/3f3038a473a9d97a117822aafe6841b0a9c8612e/common/include/pcl/common/centroid.h#L497-L510) of `computeCovarianceMatrix`, the documentation clearly states that the cloud has to be an "already demeaned point cloud". Using it with a cloud that does not have a mean of zero would be a misuse of the function. So it seems that `computeCovarianceMatrix` does not have this problem. However, if you have an example program which demonstrates an error, I would of course be interested to see that.
In gicp.hpp, we should indeed check whether the same fix has to be applied as I used in `computeMeanAndCovarianceMatrix`. I am not sure how big the problem is there, because in gicp.hpp, double is used, while `computeMeanAndCovarianceMatrix` is mostly used with float. But it might still improve accuracy to simply subtract the `query_point` from `pt`.

**Comment by mvieth** [comment] 2022-04-26 19:09
After thinking about it, I think it would indeed be good to apply the same fix to gicp.hpp (by subtracting `query_point` as an estimate of the mean from `pt`). My analysis above has shown that this is only very slightly slower (negligibly so), and that there can still be a large error with the naive algorithm (without shifting the data) if the cloud is far from the origin, even with double precision.
@extr15 Would you be interested in doing this and opening a pull request?

**Comment by extr15** [comment] 2022-04-29 10:34
@mvieth Thanks for your reply. IMO in the `computeCovarianceMatrix(in sac_model_line.hpp)`, the float centroid is not that accurate. Let `m1` be the estimated float centroid, `m2` be the real centroid, and in the `Two-pass` method, there are still about `sum(m1-m2)^2` errors left, so I think maybe it's not accurate enough. However, I don't verify it yet.
I'd like to add a PR for `gicp` later when I have more time... and I also need to learn how to do some unit tests before I push.

**Comment by mvieth** [comment] 2022-05-06 12:21
@extr15 I don't really get your point. What would you define as the "real centroid"? How could you get a more accurate centroid than computing the arithmetic mean of the points (which is what compute3DCentroid does)?

**Comment by extr15** [comment] 2022-05-11 07:12
@mvieth , we can't :). But in `sac_model_line.hpp`'s `compute3DCentroid`, it uses a float centroid instead of a double centroid. I mean we should use a double centroid here, what do you think?

**Comment by extr15** [comment] 2022-05-14 14:52
@mvieth, I only have some intuition now. There may be thousands of points, error of each one is 1e-5, so the accumulated error may be large. Maybe I can do some experiments later, and thanks for your reply.
