### ISSUE TITLE
segmentation fault while intiating pcl visualizer in code

### ISSUE THREAD

**Issue by MohamadHalwani** [PointCloudLibrary/pcl#4638] opened 2021-03-07 12:58 UTC
I'm trying to visualize a point cloud and bounding box using pcl library.
The code runs well but when it reaches 

    std::cout << "5" << std::endl;
      // final transform
      const Eigen::Quaternionf qfinal(eigDx);
      const Eigen::Vector3f tfinal = eigDx*mean_diag + centroid.head<3>();
      std::cout << "6" << std::endl;
      // draw the cloud and the box
      pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer")); 
      //pcl::visualization::PCLVisualizer viewer;
      std::cout << "7" << std::endl;
      viewer->addPointCloud<pcl::PointXYZI>(point_cloud_ptr);

this error appears 

```
    5
    6
    *** Aborted at 1615119616 (unix time) try "date -d @1615119616" if you are using GNU date ***
    PC: @     0x7f4895b9e3e3 vtkAlgorithm::SetExecutive()
    *** SIGSEGV (@0x1) received by PID 23164 (TID 0x7f48a4af1840) from PID 1; stack trace: ***
        @     0x7f489b56e390 (unknown)
        @     0x7f4895b9e3e3 vtkAlgorithm::SetExecutive()
        @     0x7f4895b9e390 vtkAlgorithm::GetExecutive()
        @     0x7f4895b9f88f vtkAlgorithm::SetInputConnection()
        @     0x7f4895b9f7f8 vtkAlgorithm::SetInputConnection()
        @     0x7f488ec1906f vtkInteractorStyle::vtkInteractorStyle()
        @     0x7f489c5d2869 vtkInteractorStyleTrackballCamera::vtkInteractorStyleTrackballCamera()
        @     0x7f489c5c12be vtkInteractorStyleRubberBandPick::vtkInteractorStyleRubberBandPick()
        @     0x7f488ccb9e0c pcl::visualization::PCLVisualizerInteractorStyle::PCLVisualizerInteractorStyle()
        @     0x7f488ccad0db pcl::visualization::PCLVisualizerInteractorStyle::New()
        @     0x7f488ccd8456 pcl::visualization::PCLVisualizer::PCLVisualizer()
        @           0x42ff92 main
        @     0x7f48997c9840 __libc_start_main
        @           0x430f09 _start
    Segmentation fault (core dumped)

```
Any help is appreciated

Ubuntu 16.04

**Comment by mvieth** [comment] 2021-03-07 14:36
I can't reproduce this bug (current master/1.11.1-dev).
What PCL version do you use and how did you install it?
What VTK version do you have installed?
How do you compile your own code? Any specific flags/options?

**Comment by MohamadHalwani** [comment] 2021-03-10 05:44
> I can't reproduce this bug (current master/1.11.1-dev).
> What PCL version do you use and how did you install it?
> What VTK version do you have installed?
> How do you compile your own code? Any specific flags/options?

PCL version 1.8
for VTK version I'm not sure how to check it. 
I'm compiling the code through ROS ("rosrun" command)

**Comment by mvieth** [comment] 2021-03-10 10:01
You can check the VTK version as shown [here](https://vtk.org/Wiki/VTK/Examples/Cxx/Utilities/CheckVTKVersion).
Can you test if the error still appears with a newer PCL version (e.g. 1.11.1, compiled from source)?

**Comment by mvieth** [comment] 2021-04-28 19:47
Closing this since it does not seem to be a PCL issue and is probably fixed by using a newer VTK version.

**Closed by mvieth** 2021-04-28 19:47 UTC
Labels: kind: bug, module: visualization, needs: feedback
