### ISSUE TITLE
[Source.obj] "unresolved external symbol "public: int __cdecl pcl::PCDWriter::writeASCII"

### ISSUE THREAD

**Issue by minhhieu14351997** [PointCloudLibrary/pcl#3751] opened 2020-03-15 10:53 UTC
*Your Environment
- Operating System: Windows 10
-PCL Version: PCL 1.10.0
*Context:
Hi everybody,
I get an error when building the program, the error appears as below. I think my error is missing something that I don't know about.
*Error:
![image](https://user-images.githubusercontent.com/40237041/76700038-cd87e280-66e5-11ea-9506-594aeae7254e.png)
Thanks for your time.

**Comment by kunaltyagi** [comment] 2020-03-15 11:58
Could you please provide:
* method of installation
* PCL dependency versions
* compiler version
* compile flags
* cmake configuration output

A Minimum Complete Verifiable Example (MCVE) to reproduce would be the best. Right now, the issue seems to be something with VTK (but it might not be)

**Comment by larshg** [comment] 2020-03-15 13:10
You probably haven't added the additional linker dependencies:

Under project properties -> linker -> input -> additional dependencies - add the following:

_fullpathtopcl_\lib\pcl_iod.lib in debug
_fullpathtopcl_\lib\pcl_io.lib in release

alternatively you should make it as a CMake project, which will add all dependencies for you.

If you have used VCPKG and done a integrate install, you might be able to just add the .libs without the full path. I haven't tried this my self, so I'm guessing now by what I have read.

**Comment by minhhieu14351997** [comment] 2020-03-16 03:21
>I didn't use CMake to build the project. I simply created the project with Visual studio 2019. I wonder if not using Cmake to build projects will affect the PCL library.

Thanks you.

**Comment by minhhieu14351997** [comment] 2020-03-16 03:24
> You probably haven't added the additional linker dependencies:
> 
> Under project properties -> linker -> input -> additional dependencies - add the following:
> 
> _fullpathtopcl_\lib\pcl_iod.lib in debug
> _fullpathtopcl_\lib\pcl_io.lib in release
> 
> alternatively you should make it as a CMake project, which will add all dependencies for you.
> 
> If you have used VCPKG and done a integrate install, you might be able to just add the .libs without the full path. I haven't tried this my self, so I'm guessing now by what I have read.

I tried adding pcl_iod.lib and pcl_io.lib but it still doesn't work.

Thanks @larshg

**Comment by minhhieu14351997** [comment] 2020-03-16 03:24
> Could you please provide:
> 
> * method of installation
> * PCL dependency versions
> * compiler version
> * compile flags
> * cmake configuration output
> 
> A Minimum Complete Verifiable Example (MCVE) to reproduce would be the best. Right now, the issue seems to be something with VTK (but it might not be)

I didn't use CMake to build the project. I simply created the project with Visual studio 2019. I wonder if not using Cmake to build projects will affect the PCL library.

Thanks @kunaltyagi

**Comment by larshg** [comment] 2020-05-14 21:22
@minhhieu14351997 is this still a problem?

**Comment by SergioRAgostinho** [comment] 2020-05-14 22:15
I'm tempted to close this because we require the use of CMake. As is, this is not really actionable form our side. Users can opt out of CMake but then issues related to compilation are their own responsibility.

**Comment by larshg** [comment] 2020-05-16 07:34
This is also 2 months old now...

**Closed** 2020-05-16 10:16 UTC
Labels: kind: compile error, module: io, platform: windows
