### ISSUE TITLE
GPU-based approxNearestSearch does not work properly

### ISSUE THREAD

**Issue by WenjieYan** [PointCloudLibrary/pcl#3649] opened 2020-02-15 20:51 UTC
I got some problem by using the gpu version of the approxNearestSearch in my project and just by trying with the provided unit test script (slightly modified) I see 
(1) results of the GPU  version (i.e. from octree_device.approxNearestSearch) does not match the results of the original CPU verison function (approxNearestSearch), and 
(2) the quality of the  results from approxNearestSearchHost is also worse than  the direct CPU solution from approxNearestSearch. 

## Your Environment

* Operating System and version: Linux yan-OMEN-by-HP-Laptop-15-dc1xxx 4.15.0-76-generic #86~16.04.1-Ubuntu SMP Mon Jan 20 11:02:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
* PCL Version: 1.9.1

## Context

The reason for using the GPU version is to accelerate the operation, but currently with the GPU version, the results are poor and cannot be used.
## Expected Behavior

At least the unit test "pcl-pcl-1.9.1/gpu/octree/test/test_approx_nearest.cpp" should be successful. And the results of the GPU version should be better than/at least the same as the CPU version. 

## Current Behavior

The unit test "pcl-pcl-1.9.1/gpu/octree/test/test_approx_nearest.cpp" fails and the result if worse than the CPU version. 

yan@yan-OMEN-by-HP-Laptop-15-dc1xxx: ./test_approx_nearest 
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from PCL_OctreeGPU
[ RUN      ] PCL_OctreeGPU.approxNearesSearch
Points number  = 871000
Queries number = 10000
Cube size      = 1024
Max radius     = 34.1333
Shared radius  = 34.1333
count_gpu_better: 3106
count_pcl_better: 6894
avg_diff_pcl_better: 13.8789
/home/yan/pcl_tracking_gpu_test/test_approx_nearest.cpp:146: Failure
Value of: true
Expected: ( downloaded == result_host_gpu )
Which is: false
[  FAILED  ] PCL_OctreeGPU.approxNearesSearch (1065 ms)
[----------] 1 test from PCL_OctreeGPU (1066 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1066 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] PCL_OctreeGPU.approxNearesSearch

 1 FAILED TEST

**Comment by WenjieYan** [comment] 2020-04-02 14:27
Hi all,

 any update regarding this issue?

Best wishes

Wenjie

**Comment by kunaltyagi** [comment] 2020-04-02 20:00
The good:
* We have some community members interested in the a few changes in the gpu module which will touch the root cause of this issue

The bad:
* No one is actively pursuing it for now

The ugly:
* We don't have a CI to test GPU based modules so it may bitrot. Many of the maintainers don't have a personal access to GPU either.

If it is urgent for you, we'd love a PR.

**Comment by haritha-j** [comment] 2020-08-20 08:37
Fixed by #4294 

> The ugly:
 We don't have a CI to test GPU based modules so it may bitrot. Many of the maintainers don't have a personal access to GPU  
 either.

We also have CI for GPU modules now, and while the tests aren't run on CI, they can be run by users, including the test mentioned in the issue.

**Closed** 2020-08-20 09:24 UTC
Labels: kind: bug, kind: todo, module: gpu, priority: gsoc
