### ISSUE TITLE
Boost linking problem

### ISSUE THREAD

**Issue by Algomorph** [PointCloudLibrary/pcl#1408] opened 2015-10-29 15:48 UTC
When trying to compile PCL master branch against boost 1.58, I'm getting the following linking error:

```
../../lib/libpcl_visualization.so.1.8.0: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
collect2: error: ld returned 1 exit status
```

This error does not occur while building 1.7.2.

**Comment by hoverpeter** [comment] 2015-11-09 22:43
I occasionally have the same issue, and I am still investigating now

**Comment by Algomorph** [comment] 2015-11-10 00:31
Likewise. For whatever reason (perhaps after a restart or upgrade) the problem went away.

**Comment by Algomorph** [comment] 2015-11-10 00:41
Try to make sure you don't have any lingering version of boost libraries alongside the new ones, then restart.

**Comment by hoverpeter** [comment] 2015-11-10 01:26
Same here. It happens occasionally when I try rebuild PCL.

**Comment by hoverpeter** [comment] 2015-11-10 01:26
You can close this issue now.

**Comment by pendar747** [comment] 2016-04-28 14:40
I have the same issue trying to build pcl 1.8 on ubuntu 16:
```
../lib/libpcl_recognition.so.1.8.0: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/pcl_match_linemod_template.dir/build.make:128: recipe for target 'bin/pcl_match_linemod_template' failed
make[2]: *** [bin/pcl_match_linemod_template] Error 1
CMakeFiles/Makefile2:3586: recipe for target 'tools/CMakeFiles/pcl_match_linemod_template.dir/all' failed
make[1]: *** [tools/CMakeFiles/pcl_match_linemod_template.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

**Comment by progham** [comment] 2016-06-15 22:55
Same issue with pcl 1.8 on ubuntu 16

**Comment by charlewander** [comment] 2016-06-23 00:40
Same issue with pcl 1.8 on ubuntu 16

**Comment by charlewander** [comment] 2016-06-23 00:46
@progham Hi,how could you solve this problem? I have also the same issue.

**Comment by jspricke** [comment] 2016-06-23 13:45
I can't reproduce this on Ubuntu 16.04. Note that compiling against VTK6 doesn't work because of this:
https://bugs.launchpad.net/ubuntu/+source/vtk6/+bug/1573234

**Comment by progham** [comment] 2016-06-23 18:19
@charlewander I'm not sure exactly how I fixed it because I ran a whole clean install of Ubuntu 16.04.  I think reinstalling all of the dependencies for Boost and then Boost might help.

**Comment by JavonneM** [comment] 2016-09-23 05:46
The default libboost from apt on ubuntu 14.04.2 worked perfect I updated to Ubuntu 16.04 and it produced that error. Seems it is boost 1.58 by default on 16.04 uninstalled it and installed boost 1.61 works now. I'm guessing that pcl is being built with 1.61.

**Comment by district10** [comment] 2017-01-12 04:03
Same here. Solved by switch off `WITH_VTK`.  (I use `ccmake ..` to do that.)

ubuntu 16.04, gcc 5.4, pcl 1.8.

**Comment by 87VN0** [comment] 2018-11-21 13:34
Worked here with boost 1.64. 1.68 didn't work. I am not sure if I had to reboot though.
Ubuntu 16.04, gcc 5.5.0, PCL 1.8.1.
Thanks

**Comment by taketwo** [comment] 2018-11-21 13:37
Please use latest PCL (1.9.0), there were some incompatible changes in Boost lately.

**Closed by taketwo** 2018-11-21 13:37 UTC
