### ISSUE TITLE
[compile error] pcl-1.12.1 not well used in ROS melodic

### ISSUE THREAD

**Issue by Aazwhy** [PointCloudLibrary/pcl#6076] opened 2024-07-03 05:22 UTC
I used KDtree in my code ，and I defined the variable as : "pcl::KdTreeFLANN<PointType>::Ptr kdtreeCornerLast(new pcl::KdTreeFLANN<PointType>())" , later when I ran the code , it went wrong:
process has died [pid 27205, exit code -11, cmd /home/l/AAlh/loamApply_ws/devel/lib/loam_apply/loam_apply_laserOdometry __name:=loam_apply_laserOdometry __log:=/home/l/.ros/log/a5bb3e24-38f9-11ef-9b72-7cb5665f0b77/loam_apply_laserOdometry-4.log].
log file: /home/l/.ros/log/a5bb3e24-38f9-11ef-9b72-7cb5665f0b77/loam_apply_laserOdometry-4*.log

then I defined the variable like:"pcl::KdTreeFLANN<PointType>::Ptr kdtreeCornerLast(new pcl::KdTreeFLANN<PointType>()); " ,but there was still something wrong,it noted me :
libgomp: Out of memory allocating 750987056064 bytes
[loam_apply_laserOdometry-4] process has died [pid 21998, exit code 1, cmd /home/l/AAlh/loamApply_ws/devel/lib/loam_apply/loam_apply_laserOdometry __name:=loam_apply_laserOdometry __log:=/home/l/.ros/log/eb56a94a-386e-11ef-9b72-7cb5665f0b77/loam_apply_laserOdometry-4.log].
log file: /home/l/.ros/log/eb56a94a-386e-11ef-9b72-7cb5665f0b77/loam_apply_laserOdometry-4*.log

this happened in the sentence "kdtreeCornerLast->nearestKSearch(pointSel, 1, pointSearchIndLast, pointSearchSqDisLast)",there's just a few point in the variable "pointSearchIndLast"。

then I tried to upgrade my pcl version to 1.12.1(the ROS version is melodic)，but i cannot compile successfully,here's some of the problem:
/usr/include/pcl-1.12.1/include/pcl-1.12/pcl/filters/voxel_grid.h:438:73: error: macro "PCL_DEPRECATED" passed 3 arguments, but takes just 1
       PCL_DEPRECATED(1, 16, "use bool getFilterLimitsNegative() instead")
                                                                         ^
/usr/include/pcl-1.12.1/include/pcl-1.12/pcl/filters/voxel_grid.h:787:73: error: macro "PCL_DEPRECATED" passed 3 arguments, but takes just 1
       PCL_DEPRECATED(1, 16, "use bool getFilterLimitsNegative() instead")
       
/usr/include/pcl-1.12.1/include/pcl-1.12/pcl/filters/voxel_grid.h:159:22: error: ‘Indices’ does not name a type; did you mean ‘IndicesPtr’?
                const Indices &indices,
                      ^~~~~~~
                      IndicesPtr
/usr/include/pcl-1.12.1/include/pcl-1.12/pcl/filters/voxel_grid.h:190:19: error: ‘shared_ptr’ does not name a type; did you mean ‘char16_t’?
       using Ptr = shared_ptr<VoxelGrid<PointT> >;
                   ^~~~~~~~~~
                   char16_t
/usr/include/pcl-1.12.1/include/pcl-1.12/pcl/filters/voxel_grid.h:191:24: error: ‘shared_ptr’ does not name a type; did you mean ‘char16_t’?
       using ConstPtr = shared_ptr<const VoxelGrid<PointT> >;
                        ^~~~~~~~~~
                        char16_t
/usr/include/pcl-1.12.1/include/pcl-1.12/pcl/filters/voxel_grid.h:438:7: error: ‘PCL_DEPRECATED’ does not name a type
       PCL_DEPRECATED(1, 16, "use bool getFilterLimitsNegative() instead")
       ^~~~~~~~~~~~~~
/usr/include/pcl-1.12.1/include/pcl-1.12/pcl/filters/voxel_grid.h:787:7: error: ‘PCL_DEPRECATED’ does not name a type
       PCL_DEPRECATED(1, 16, "use bool getFilterLimitsNegative() instead")
       ^~~~~~~~~~~~~~
In file included from /home/l/AAlh/loamApply_ws/src/loam_apply/src/laserOdometry.cpp:39:0:
/usr/include/pcl-1.12.1/include/pcl-1.12/pcl/kdtree/kdtree_flann.h:145:22: error: ‘shared_ptr’ does not name a type; did you mean ‘char16_t’?
   using IndicesPtr = shared_ptr<Indices>;
                      ^~~~~~~~~~

**Comment by mvieth** [comment] 2024-07-03 16:25
Regarding the program crash and the out-of-memory error: you would have to at least show some more of your code (from the point where you create the kdtree to where the error happens). Better yet, create a minimal reproducible example (a small, standalone program that I can use to reproduce the crash, including the data you use).

Regarding the compile errors: did you remove all other PCL versions installed on your system? You could try running `sudo apt remove libpcl*`. If you want to use a self-compiled PCL (not the one from apt), you will also have to compile pcl-ros and pcl-conversion (the ROS packages that depend on PCL) from source.

**Comment by mvieth** [comment] 2024-07-10 08:40
@Aazwhy If you don't reply soon to my last comment, I will assume that the problem is solved and close this issue

**Comment by Aazwhy** [comment] 2024-07-11 09:29
> Regarding the program crash and the out-of-memory error: you would have to at least show some more of your code (from the point where you create the kdtree to where the error happens). Better yet, create a minimal reproducible example (a small, standalone program that I can use to reproduce the crash, including the data you use).
> 
> Regarding the compile errors: did you remove all other PCL versions installed on your system? You could try running `sudo apt remove libpcl*`. If you want to use a self-compiled PCL (not the one from apt), you will also have to compile pcl-ros and pcl-conversion (the ROS packages that depend on PCL) from source.

thank you for replying me!I've solved the problem: I first compiled my code with pcl-1.8 and then again with pcl-1.12.1,then the problem is solved.However I do not know what the origin is of this problem,maybe it is caused by the differences in memory management between the two pcl versions.I'm sorry I can't provide a minimum replicable example,this project is related to SLAM, relies on data sets, and may take you too much effort to repeat line errors. 
Anyway, thanks for your answer!

**Comment by mvieth** [comment] 2024-07-11 09:58
Ok great, then I am closing this issue.

**Closed by mvieth** 2024-07-11 09:58 UTC
Labels: kind: compile error, status: triage
