### ISSUE TITLE
Cannot make successfully on ubuntu 14.04.1 

### ISSUE THREAD

**Issue by Yanzqing** [PointCloudLibrary/pcl#1341] opened 2015-09-19 03:19 UTC
When i make pcl-master , it comes up with the error
How can i solve this problem?
Linking CXX shared library ../lib/libpcl_io.so
[ 19%] Built target pcl_io
Scanning dependencies of target pcl_convert_pcd_ascii_binary
[ 20%] Building CXX object io/tools/CMakeFiles/pcl_convert_pcd_ascii_binary.dir/convert_pcd_ascii_binary.cpp.o
Linking CXX executable ../../bin/pcl_convert_pcd_ascii_binary
//usr/lib/libpq.so.5: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_CTX_get_cert_store@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_check_private_key@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `CRYPTO_num_locks@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `ENGINE_by_id@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `ERR_get_error@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `CRYPTO_set_locking_callback@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_use_certificate_file@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `ENGINE_free@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_new@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_load_error_strings@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `OPENSSL_config@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `X509_NAME_get_text_by_NID@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_write@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_use_PrivateKey_file@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `X509_STORE_load_locations@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `X509_free@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_free@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_set_ex_data@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_set_verify@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `ENGINE_init@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_set_fd@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_read@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `ERR_reason_error_string@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_connect@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_CTX_ctrl@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_use_PrivateKey@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `X509_STORE_set_flags@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_pending@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `ENGINE_finish@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSLv23_method@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `ENGINE_load_private_key@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_library_init@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `X509_get_subject_name@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `CRYPTO_set_id_callback@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_shutdown@OPENSSL_1.0.0'
//usr/lib/libpq.so.5: undefined reference to `SSL_get_peer_certificate@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/pcl_convert_pcd_ascii_binary] Error 1
make[1]: *** [io/tools/CMakeFiles/pcl_convert_pcd_ascii_binary.dir/all] Error 2
make: *** [all] Error 2

**Comment by jspricke** [comment] 2015-09-19 06:20
Looks like your libpq installation is broken. Try ``sudo apt-get install --reinstall libpq5``. Closing as it's not a PCL bug.

**Closed by jspricke** 2015-09-19 06:20 UTC

**Comment by AndreiBarsan** [comment] 2017-04-05 17:59
FWIW (this page was a top result when I was Googling this problem), this seems to often get caused by Anaconda, if it's installed (e.g., similar issue: https://stackoverflow.com/questions/40400274/linker-error-undefined-reference-to-ssl-get-peer-certificate-when-building-pos). Simply removing Anaconda from the PATH and restarting the build process should solve the problem.

**Comment by birhanuabera** [comment] 2018-03-30 13:38
I have solved by removing the libpq.so.* file using:
sudo apt-get remove libpq5
and reinstalled that can solve the problem
sudo apt-get install libpq-dev

**Comment by sara-eb** [comment] 2018-07-17 05:41
@birhanuabera @jspricke  I have compiled opencv 3.2.0 and after trying your solution, I am getting the following error once i want to build Caffe:

```
[ 83%] Linking CXX executable compute_image_mean
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_get_peer_certificate@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `CRYPTO_num_locks@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_get_current_compression@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_CTX_free@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_get_version@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `BIO_int_ctrl@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ENGINE_free@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `CRYPTO_get_id_callback@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ASN1_STRING_data@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `OPENSSL_config@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `X509_NAME_get_entry@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_use_PrivateKey_file@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `X509_STORE_load_locations@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ASN1_STRING_length@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_CIPHER_get_name@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `sk_num@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_set_ex_data@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_read@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `X509_STORE_set_flags@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSLv23_method@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ENGINE_load_private_key@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `BIO_new@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `BIO_set_flags@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `X509_get_subject_name@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `CRYPTO_get_locking_callback@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `X509_NAME_ENTRY_get_data@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `sk_value@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `CRYPTO_set_id_callback@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_CTX_get_cert_store@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_check_private_key@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ENGINE_by_id@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `BIO_s_socket@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ERR_put_error@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ERR_get_error@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `CRYPTO_set_locking_callback@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_load_error_strings@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_new@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_get_current_cipher@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `BIO_clear_flags@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_write@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `X509_free@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_free@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ERR_clear_error@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_set_verify@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ENGINE_init@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_CIPHER_get_bits@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_connect@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `X509_NAME_get_index_by_NID@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ERR_reason_error_string@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_set_bio@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_CTX_ctrl@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `sk_free@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_pending@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_use_PrivateKey@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `ENGINE_finish@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `X509_get_ext_d2i@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_library_init@OPENSSL_1.0.0'
//usr/lib/x86_64-linux-gnu/libpq.so.5: undefined reference to `SSL_shutdown@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/compute_image_mean.dir/build.make:130: recipe for target 'tools/compute_image_mean' failed
make[2]: *** [tools/compute_image_mean] Error 1
CMakeFiles/Makefile2:511: recipe for target 'tools/CMakeFiles/compute_image_mean.dir/all' failed
make[1]: *** [tools/CMakeFiles/compute_image_mean.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

What do you suggest? thank you

**Comment by nagu0011** [comment] 2018-12-01 17:07
[ 57%] Built target CsvImport
[ 58%] Built target QueryRunner
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_verify_mode@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_verify@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_num_locks@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_wbio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_peek@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_destroy_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_shutdown@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_get_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_locking_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_method@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_load_error_strings@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_get_entry@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_write@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `EVP_cleanup@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_verify_cert_error_string@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_length@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_use_PrivateKey_file@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_peek_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_free_strings@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_num@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_accept@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_remove_state@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_to_UTF8@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_clear_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_2_method@OPENSSL_1.0.1'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_rbio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_set_fd@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_cleanup_all_ex_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_s_mem@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_read@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_set_bio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `GENERAL_NAME_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_reason_error_string@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_connect@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_get_index_by_NID@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `RAND_poll@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_default_passwd_cb@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSLv23_method@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_library_init@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_get_subject_name@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_cipher_list@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_get_ext_d2i@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_ENTRY_get_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_1_method@OPENSSL_1.0.1'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_value@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_create_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_pop_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_lock_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_verify_result@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_shutdown@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_peer_certificate@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
Import/CMakeFiles/KafkaImporter.dir/build.make:108: recipe for target 'bin/KafkaImporter' failed
make[2]: *** [bin/KafkaImporter] Error 1
CMakeFiles/Makefile2:1354: recipe for target 'Import/CMakeFiles/KafkaImporter.dir/all' failed
make[1]: *** [Import/CMakeFiles/KafkaImporter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Configuring done
-- Generating done
-- Build files have been written to: /home/thickstat/Downloads/mapd-core/build
[ 58%] Built target rerun_cmake
[ 84%] Built target QueryEngine
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

how can i fix this
