### ISSUE TITLE
no member named 'posix_fallocate' in the global namespace

### ISSUE THREAD

**Issue by heartzwh** [PointCloudLibrary/pcl#2358] opened 2018-06-26 01:30 UTC
hi everyone,

i want to build pcl for android platform.
when i build **pcd_grabber.cpp** had a issue.
how to fix the error.
thanx.

### system and pcl version
* Operating System and version: Ubuntu 16.04
* PCL Version: 1.8.1 newest version cc7fe363c6463a0abc617b1e17e94ab4bd4169ef

[ 22%] Built target pcl_io_ply
[ 22%] Building CXX object io/CMakeFiles/pcl_io.dir/src/pcd_grabber.cpp.o
In file included from /home/sora/Desktop/pcl-for-android-master/build/pcl/io/src/pcd_grabber.cpp:39:
/home/sora/Desktop/pcl-for-android-master/build/pcl/io/include/pcl/io/low_level_io.h:138:16: error: 
      no member named 'posix_fallocate' in the global namespace
      return ::posix_fallocate(fd, 0, len);
             ~~^

**Comment by taketwo** [comment] 2018-06-26 01:41
Hi, this is caused by the recently merged #2325 that uses `posix_fallocate` function. We already had reports that this function is missing from MacOS, so a fallback implementation was added (#2341, #2354). Could you please try if this same fallback works on Android? I.e. change `ifdef` guards such that on Android the Apple branch is taken.

@de-vri-es that was such a small innocent PR, wasn't it? :laughing:

**Comment by heartzwh** [comment] 2018-06-26 11:09
@taketwo thanx for you reply. it works, i build complete without other issue.

**Comment by taketwo** [comment] 2018-06-26 11:50
Great. Please consider sending a PR.

**Comment by de-vri-es** [comment] 2018-06-26 13:51
> @de-vri-es that was such a small innocent PR, wasn't it?

It seemed that way back then >.< It's POSIX, it should work everywhere :[

I'm not convinced the OS X implementation will actually work correctly on Android. That specific fcntl only shows up in OS X man pages. I would actually expect compile errors on `::fstore_t` and `F_PREALLOCATE` and friends though. It would be good to test writing/reading a PCD on android with the patch to make sure.

Maybe a third fallback that does a seek+write would make sense. The `::posix_fallocate` version could be limited to Linux and *BSD. `ftruncate` is also a possible candidate as fallback. But it creates sparse files when possible (acceptable), and it isn't guaranteed to be able to make files bigger (problem) on all filesystems.

**Comment by taketwo** [comment] 2018-06-26 14:04
Hm, I found [this piece of code](https://android.googlesource.com/platform/bionic/+/master/libc/bionic/posix_fallocate.cpp), it simply forwards arguments to `fallocate`, which comes from "fcntl.h" apparently.

**Comment by de-vri-es** [comment] 2018-06-26 14:24
Interesting.. I went for `posix_fallocate` because it's from the POSIX.1-2001 standard while `fallocate` is Linux specific. Also, `posix_fallocate` has emulation for filesystems that don't support `fallocate` directly.

But it seems Andoird only has the Linux version, not the POSIX version.. Since `fallocate` can fail on unsupported filesystems (probably FAT and NTFS), it would need to have a fallback to either writing zeroes or seek+write.

**Comment by taketwo** [comment] 2018-06-26 14:48
I see. I wonder what would be the best way to approach this.

I've never used PCL on Android (and I am actually surprised someone does), so I don't have time/motivation to properly fix this. What if we just add an Android `ifdef` branch with `fallocate()` call? This will make sure the thing at least compiles. And then if someone shows up, reports failures and is committed to fix it, we guide him through adding a fallback?

Though to be honest I don't feel very good about this because we'd be leaving a self-inflicted regression in the codebase :(

**Comment by de-vri-es** [comment] 2018-06-26 14:58
For best portability we would have to try several things in order and fall back to the next option when one fails.

I think the logical order then would be: one of `posix_fallocate`/`fallocate`/`OSX fcntl` then `ftruncate` then `seek+write` with ifdefs to hide compile time unavailable options.

Quite a hassle, but at least there's a single definition now. I'm also willing to put it into a PR if you agree with that direction.

**Comment by taketwo** [comment] 2018-06-26 15:07
Sounds reasonable. But you know way more than me about these things, so ultimately please follow your own judging.

> I'm also willing to put it into a PR if you agree with that direction.

:+1:

We'll need an Apple and Android person to test that PR. @heartzwh  please stay tuned.

**Comment by taketwo** [comment] 2018-06-28 15:19
I'll reopen this because the issue is not solved upstream.

**Comment by de-vri-es** [comment] 2018-06-28 18:48
Initial PR at #2363 =]

**Closed** 2018-08-31 16:00 UTC
Labels: platform: android
