### ISSUE TITLE
[pcl::visualization] Adding vtkOrientationMarkerWidget in the initialization leads to crash

### ISSUE THREAD

**Issue by Asher-1** [PointCloudLibrary/pcl#3815] opened 2020-03-28 04:49 UTC
**Screenshots/Code snippets**
![image](https://user-images.githubusercontent.com/16451440/77815159-26e30f00-70f3-11ea-95ed-0970d7a5f5ed.png)

**Your Environment (please complete the following information):**

 - OS: [Windows 10]
 - Compiler: [MSVC 15]
 - PCL Version [1.9.1]

**Comment by larshg** [comment] 2022-03-04 21:40
Sorry for very late answer. I think the interactor is not created yet, hence you access nullptr. Either add the Widget later or create the interactor before adding the widget.
Closing as not a bug in PCL.

**Closed by larshg** 2022-03-04 21:40 UTC
Labels: kind: bug, platform: windows, module: visualization, needs: feedback
