### ISSUE TITLE
[custom] Don't use memcpy/memcpy/memset for non-POD types

### ISSUE THREAD

**Issue by gnawme** [PointCloudLibrary/pcl#4272] opened 2020-07-14 17:38 UTC
Per [C++ Coding Standards Item 96](https://www.oreilly.com/library/view/c-coding-standards/0321113586/ch97.html)

> `memcpy` and `memcmp` violate the type system. Using `memcpy` to copy objects is like making money using a photocopier. Using `memcmp` to compare objects is like comparing leopards by counting their spots. The tools and methods might appear to do the job, but they are too coarse to do it acceptably.

`memset` is [also considered harmful](https://hownot2code.com/2016/05/23/the-most-dangerous-function-in-the-cc-world/).

#3368

**Comment by kunaltyagi** [comment] 2020-07-14 17:40
Duplicate of #3368

**Closed by kunaltyagi** 2020-07-14 17:40 UTC
Labels: status: triage
