### ISSUE TITLE
Input of the function

### ISSUE THREAD

**Issue by martijnvwezel** [PointCloudLibrary/pcl#1360] opened 2015-10-07 10:52 UTC
There is no example or description how the input looks like. It cost me a day to understand that the error that I got has something to do with Normals.

**Comment by jspricke** [comment] 2015-10-07 11:09
Can you please stop open random bug reports? If you have questions regarding PCL, please use our mailing list: http://www.pcl-users.org/. If you want to help with the documentation, please open pull requests.

Closing as it's not a bug.

**Closed by jspricke** 2015-10-07 11:09 UTC
