### ISSUE TITLE
example_sift_keypoint_estimation.cpp

### ISSUE THREAD

**Issue by mimouncadosch** [PointCloudLibrary/pcl#1498] opened 2016-01-13 16:40 UTC
Hi,

I ran this example, and the program successfully computed the sift keypoints.

However, when visualizing the keypoints in the cloud, the keypoints seem translated away from the cloud. 

is there a way to set the cloud and keypoints to have the same origin and orientation?

Thanks

<img width="1347" alt="screen shot 2016-01-13 at 11 40 23 am" src="https://cloud.githubusercontent.com/assets/3169881/12300643/774a94e6-b9ea-11e5-82b6-c58baf9f3a97.png">

**Comment by SergioRAgostinho** [comment] 2016-01-13 21:22
This might be a duplicate of #1475

**Comment by taketwo** [comment] 2016-01-13 21:35
Here is what I get with "test/milk_cartoon_all_small_clorox.pcd" point cloud on trunk PCL with _vtk6.3_:

![screenshot from 2016-01-13 22-32-52](https://cloud.githubusercontent.com/assets/1241736/12308464/bdff7518-ba45-11e5-8558-4265f6730a01.png)

The found features seem... suspicious, but at least they are geometrically coincide with points from the cloud. Can you post your cloud somewhere?

**Comment by mimouncadosch** [comment] 2016-01-14 03:33
Hi,

Thanks for the quick response. It worked for me with the "test/milk_carton_all_small_clorox.pcd" file as well, so I guess it has to do with the pcd file itself.

Here is the pcd file I am using:
https://drive.google.com/file/d/0B8g_l4xptxC0eVg4LUtsVnlVSTg/view?usp=sharing

**Comment by VictorLamoine** [comment] 2016-01-20 21:01
Can you tell me which parameters you use?

```cpp
  const float min_scale = 0.1f;
  const int n_octaves = 6;
  const int n_scales_per_octave = 10;
  const float min_contrast = 0.5f;
```

I get no key points with the default parameters.

**Comment by SergioRAgostinho** [comment] 2016-01-24 18:52
@VictorLamoine are you looking at this?

**Comment by VictorLamoine** [comment] 2016-01-24 18:57
Yes and no. I looked at it, it's not the same as the view point.

I think the SIFT key point computation ignores the viewpoint information (it's fine), that's why it appears shifted when added in the visualizer.

A simple/nice solution would be to copy the sensor_orientation_ and sensor_position_ fields from the input cloud in the output (key points) cloud.

**Comment by SergioRAgostinho** [comment] 2016-01-24 22:27
Thanks for the briefing Victor. It was matter of doing what you suggested.

**Closed** 2016-01-26 08:33 UTC

**Comment by mimouncadosch** [comment] 2016-01-26 13:30
Thanks guys!
