### ISSUE TITLE
Add libproj-dev as dependancy

### ISSUE THREAD

**Issue by frozar** [PointCloudLibrary/pcl#2379] opened 2018-07-17 15:00 UTC
## Your Environment
* Operating System and version: ubuntu 16.04
* Compiler: gcc
* PCL Version: current master

## Expected Behavior
To compile.

## Current Behavior
Doesn't compile with the following message:
```
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by 'lib/libpcl_io.so.1.8.1.99'.  Stop.
```

## Possible Solution
```bash
sudo apt-get install libproj-dev
```
[Thanks to this link.](https://stackoverflow.com/questions/37369369/compiling-pcl-1-7-on-ubuntu-16-04-errors-in-cmake-generated-makefile)

**Comment by taketwo** [comment] 2018-07-17 15:05
Duplicate of #1828 and #1808. This is not a PCL problem, we don't depend on this library directly. But even if we did, what can we do about this? What do you propose?

**Comment by taketwo** [comment] 2018-07-17 17:57
Well sure, we can add a line to the compilation tutorial. As usual, PRs are welcome. I just meant we can not do anything about our CMake scripts or PCL code to solve this.

**Comment by jspricke** [comment] 2018-07-17 20:52
We can propose a stable release update to Ubuntu. Feel free to do it, there is a guideline online.

**Comment by frozar** [comment] 2018-07-20 12:07
Have you seen this Issue #2381?

**Comment by SergioRAgostinho** [comment] 2019-01-16 21:20
Closing this one since I don't a see a reason to keep it open. Otherwise please reopen it.

**Closed by SergioRAgostinho** 2019-01-16 21:20 UTC
