### ISSUE TITLE
[ConvexHull] ConvexHull::reconstruct (PointCloud &points) pretends points to be empty

### ISSUE THREAD

**Issue by mynickmynick** [PointCloudLibrary/pcl#5693] opened 2023-04-27 19:04 UTC
**Describe the bug**
i consider this a "bug" but I might be wrong and in any case it's low priority. BUT it made me waste a lot of time cause I was searching elsewhere to solve the issue. I might have a look to fix it if you agree with me it's a bug. 

ConvexHull::reconstruct (PointCloud &points) pretends points to be empty. If the points (out parameter) was already processed before 
the method leads to strange and erroneous results with frequent qhull errors or incorrect subsets given as a hull

**Context**

I was applying the convex hull on a loop for segmentation purpouses

**Expected behavior**

In my opinion as the PointCloud &points is an output it should disregard its initial content, reset its content and write the results on it

**Current Behavior**

If the points (out parameter) was already processed before 
the method leads to strange and erroneous results with frequent qhull errors or incorrect subsets given as a hull

**To Reproduce**

In my case I changed my code (a modification of pcl::ConditionalEuclideanClustering<PointT>::segment ) from

   PointCloudPtr tempHull1 = PointCloudPtr(new pcl::PointCloud<PointT >);
    PointCloudPtr tempHull2 = PointCloudPtr(new pcl::PointCloud<PointT >);
    PointCloudPtr tempHull3 = PointCloudPtr(new pcl::PointCloud<PointT >);
    cloud_cluster.back()->push_back((*input_)[iindex]);
    tempHull1->push_back((*input_)[iindex]);
    tempHull3->push_back((*input_)[iindex]);

    processed[iindex] = true;

    // Process the current cluster (it can be growing in size as it is being processed)
    while (cii < static_cast<int> (current_cluster.size ()))
    {
      // Search for neighbors around the current seed point of the current cluster
      if (searcher_->radiusSearch ((*input_)[current_cluster[cii]], cluster_tolerance_, nn_indices, nn_distances) < 1)
      {
        cii++;
        continue;
      }

      // Process the neighbors
      for (int nii = 1; nii < static_cast<int> (nn_indices.size ()); ++nii)  // nii = neighbor indices iterator
      {

        // Has this point been processed before?
        if (nn_indices[nii] == UNAVAILABLE || processed[nn_indices[nii]])
          continue;

        // Validate if condition holds
        if (condition_function_ ((*input_)[current_cluster[cii]], (*input_)[nn_indices[nii]], nn_distances[nii]))
        {
          float area, volume;
          if(cloud_cluster.back()->size()>10) 
          {
            pcl::ConvexHull<PointT> chull;
            tempHull3->push_back((*input_)[nn_indices[nii]]);
            chull.setInputCloud(tempHull3);
            chull.setComputeAreaVolume(true);
            int res=chull.reconstruct(*tempHull2);
            area = chull.getTotalArea();
            volume = chull.getTotalVolume();

            DO STUFF

to

   PointCloudPtr tempHull1 = PointCloudPtr(new pcl::PointCloud<PointT >);
    ///////////PointCloudPtr tempHull2 = PointCloudPtr(new pcl::PointCloud<PointT >);
    PointCloudPtr tempHull3 = PointCloudPtr(new pcl::PointCloud<PointT >);
    cloud_cluster.back()->push_back((*input_)[iindex]);
    tempHull1->push_back((*input_)[iindex]);
    tempHull3->push_back((*input_)[iindex]);

    processed[iindex] = true;

    // Process the current cluster (it can be growing in size as it is being processed)
    while (cii < static_cast<int> (current_cluster.size ()))
    {
      // Search for neighbors around the current seed point of the current cluster
      if (searcher_->radiusSearch ((*input_)[current_cluster[cii]], cluster_tolerance_, nn_indices, nn_distances) < 1)
      {
        cii++;
        continue;
      }

      // Process the neighbors
      for (int nii = 1; nii < static_cast<int> (nn_indices.size ()); ++nii)  // nii = neighbor indices iterator
      {

        // Has this point been processed before?
        if (nn_indices[nii] == UNAVAILABLE || processed[nn_indices[nii]])
          continue;

        // Validate if condition holds
        if (condition_function_ ((*input_)[current_cluster[cii]], (*input_)[nn_indices[nii]], nn_distances[nii]))
        {
          float area, volume;
          if(cloud_cluster.back()->size()>10) 
          {
            pcl::ConvexHull<PointT> chull;
            tempHull3->push_back((*input_)[nn_indices[nii]]);
            chull.setInputCloud(tempHull3);
            chull.setComputeAreaVolume(true);
            PointCloudPtr tempHull2 = PointCloudPtr(new pcl::PointCloud<PointT >);//FRESH DEF MOVED HERE
            int res=chull.reconstruct(*tempHull2);
            area = chull.getTotalArea();
            volume = chull.getTotalVolume();

            DO STUFF

and with that simple move the algorithm passed from not working at all with unpredicted behaviour and lots of qhull errors
to working well

**Your Environment (please complete the following information):**

 - OS: Windows 10
 - Compiler: [MSVS]
 - PCL Version [last]

**Possible Solution**

check what the code is doing and if it is correct and acceptable : reset the output cloud at first or if there are no errors that provoke a premature exit

**Comment by mvieth** [comment] 2023-04-28 08:25
@mynickmynick I checked the ConvexHull code, and `points` is correctly cleared. In the 2D case [here](https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/impl/convex_hull.hpp#L219), and in the 3D case [resized here](https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/impl/convex_hull.hpp#L357) and [later written to by index](https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/impl/convex_hull.hpp#L380).
Additionally, I modified the tests in test/surface/test_convex_hull.cpp by adding two points to each cloud passed to `reconstruct`, and all tests still passed.
So I don't see how it should cause any errors if `points` is not empty. I guess your problem is caused by something else.

**Comment by mynickmynick** [comment] 2023-04-28 08:48
thanks I'll have a closer look, reproduce the matter and let you know. the clear you mention is far in the code and there are returns before anyway, probably it's because I had partially forced-ignored the qhull errors

**Comment by mynickmynick** [comment] 2023-05-02 13:22
@mvieth  it's complicated and time consuming reproduce the problem in a simpler setting, now I am having it only inside a complex application, where I also altered functions like reconstruct performReconstruction performReconstruction2D performReconstruction3D to return an int error code in order to reject the results if error code <>0
The errors are given by qh_new_qhull()
I don't know why this happens only when chull.reconstruct() gets a parameter (output point cloud) not allocated just before
I give up for the moment cause I don't have time.
I will just keep using my fork for this application.
I also by the way would like to know why reconstruct performReconstruction performReconstruction2D performReconstruction3D are void functions. In my application I need a return code

**Comment by mynickmynick** [comment] 2023-05-02 13:52
it seems that something is going wrong with my assigning from one PointCloudPtr  to another. Aren't they C++ standard smart pointers and if I assign one to the other the destructors take care of possible deallocation of the old pointed cloud??

I have 

    PointCloudPtr tempHull1 = PointCloudPtr(new pcl::PointCloud<PointT >);
    PointCloudPtr tempHull2 = PointCloudPtr(new pcl::PointCloud<PointT >);
    PointCloudPtr tempHull3 = PointCloudPtr(new pcl::PointCloud<PointT >);


at each step I update the convex hull of the growing segment cluster and if the new convex hull tempHull2  is valid and flat I update by just

                  tempHull1 = tempHull2;
                  tempHull3 = tempHull2;


here is the full code extract from the modified
template<typename PointT> void
pcl::ConditionalEuclideanClustering<PointT>::segment (pcl::IndicesClusters &clusters)


 // Process all points indexed by indices_
  for (const auto& iindex : (*indices_)) // iindex = input index
  {
    // Has this point been processed before?
    if (iindex == UNAVAILABLE || processed[iindex])
      continue;

    // Set up a new growing cluster
    Indices current_cluster;
    int cii = 0;  // cii = cluster indices iterator

    // Add the point to the cluster
    current_cluster.push_back (iindex);

    cloud_cluster.push_back(PointCloudPtr(new pcl::PointCloud<PointT >) );
    PointCloudPtr tempHull1 = PointCloudPtr(new pcl::PointCloud<PointT >);
    PointCloudPtr tempHull2 = PointCloudPtr(new pcl::PointCloud<PointT >);//this uncommented malfunctions
    PointCloudPtr tempHull3 = PointCloudPtr(new pcl::PointCloud<PointT >);
    cloud_cluster.back()->push_back((*input_)[iindex]);
    tempHull1->push_back((*input_)[iindex]);
    tempHull3->push_back((*input_)[iindex]);
    int tempHull2Size = 1;
    processed[iindex] = true;

    // Process the current cluster (it can be growing in size as it is being processed)
    while (cii < static_cast<int> (current_cluster.size ()))
    {
      // Search for neighbors around the current seed point of the current cluster
      if (searcher_->radiusSearch ((*input_)[current_cluster[cii]], cluster_tolerance_, nn_indices, nn_distances) < 1)
      {
        cii++;
        continue;
      }

      // Process the neighbors
      for (int nii = 1; nii < static_cast<int> (nn_indices.size ()); ++nii)  // nii = neighbor indices iterator
      {

        // Has this point been processed before?
        if (nn_indices[nii] == UNAVAILABLE || processed[nn_indices[nii]])
          continue;

        // Validate if condition holds
        if (condition_function_ ((*input_)[current_cluster[cii]], (*input_)[nn_indices[nii]], nn_distances[nii]))
        {
          float area, volume;
          if(cloud_cluster.back()->size()>10) //(tempHull1->size() > 4)
          {
            pcl::ConvexHull<PointT> chull;
            tempHull3->push_back((*input_)[nn_indices[nii]]);
            //std::cout <<"LOADING tempHull3 size "<< tempHull3->size() << std::endl;
            chull.setInputCloud(tempHull3);
            //chull.setDimension(3);
            chull.setComputeAreaVolume(true);
            //PointCloudPtr tempHull2 = PointCloudPtr(new pcl::PointCloud<PointT >);//this uncommented wotrks fine

            int res=chull.reconstruct(*tempHull2);
            area = chull.getTotalArea();
            volume = chull.getTotalVolume();
            if (!res &&
              216 * volume * volume <=
              UnflatnessThreshold * (area * area * area))
            {

                  tempHull1 = tempHull2;
                  tempHull3 = tempHull2;
                  tempHull2Size = tempHull2->size();
                  std::cout << "------------tempHull2 size and res " << tempHull2->size() << " " <<res << std::endl;


                // Add the point to the cluster
                current_cluster.push_back(nn_indices[nii]);
                cloud_cluster.back()->push_back((*input_)[nn_indices[nii]]);
                processed[nn_indices[nii]] = true;

            }
            else
            {

              tempHull3 = tempHull1;
              std::cout << "Rejecting Point -----\n";
              std::cout <<"tempHull1 size "<< tempHull1->size() << std::endl;
              std::cout <<"tempHull3 size "<< tempHull3->size() << std::endl;
              std::cout <<"cloud_cluster.back.size:: "<< cloud_cluster.back()->size() << std::endl;
              for (auto p: tempHull1->points)
                std::cout <<" -- P: "<< p.x<<" : "<< p.y<<" : "<< p.z;
              std::cout << std::endl;

            }
          }
          else
          {
            // Add the point to the cluster
            current_cluster.push_back(nn_indices[nii]);
            cloud_cluster.back()->push_back((*input_)[nn_indices[nii]]);
            tempHull3->push_back((*input_)[nn_indices[nii]]);
            tempHull1->push_back((*input_)[nn_indices[nii]]);
            processed[nn_indices[nii]] = true;
            std::cout <<"tempHull1 size "<< tempHull1->size() << std::endl;
          }
        }
      }
      cii++;
    }

    // If extracting removed clusters, all clusters need to be saved, otherwise only the ones within the given cluster size range
    if (extract_removed_clusters_ ||
      (static_cast<int> (current_cluster.size ()) >= min_cluster_size_ &&
        static_cast<int> (current_cluster.size ()) <= max_cluster_size_))
    {
      pcl::PointIndices pi;
      pi.header = input_->header;
      pi.indices.resize (current_cluster.size ());
      for (int ii = 0; ii < static_cast<int> (current_cluster.size ()); ++ii)  // ii = indices iterator
        pi.indices[ii] = current_cluster[ii];

      if (extract_removed_clusters_ && static_cast<int> (current_cluster.size ()) < min_cluster_size_)
        small_clusters_->push_back (pi);
      else if (extract_removed_clusters_ && static_cast<int> (current_cluster.size ()) > max_cluster_size_)
        large_clusters_->push_back (pi);
      else
        clusters.push_back (pi);
    }
  }

**Comment by mynickmynick** [comment] 2023-05-02 14:57
insisting with this peculiar debugging:
if I overload this method

template <typename PointInT> int
pcl::ConvexHull<PointInT>::reconstruct (PointCloudPtr & points)

with 

template <typename PointInT> int
pcl::ConvexHull<PointInT>::reconstruct (PointCloudPtr & points)

where I immediately refresh the hull, everything works fine
  points = PointCloudPtr(new PointCloud);

But if instead I try just to reset the hull at start with 

  //points = PointCloudPtr(new PointCloud);
  points->clear();
  points->resize (0);
  points->width = 0; points->height = 0;
  points->is_dense = true;

I keep getting the errors

why 
  points->clear();
  points->resize (0);
  points->width = 0; points->height = 0;
  points->is_dense = true;
isn't nearly equivalent to 
  points = PointCloudPtr(new PointCloud);
for the execution results??


working overload:

template <typename PointInT> int
pcl::ConvexHull<PointInT>::reconstruct (PointCloudPtr & points)
{
  points = PointCloudPtr(new PointCloud);
  points->header = input_->header;
  if (!initCompute () || input_->points.empty () || indices_->empty ())
  {
    points->clear ();
    return 1;
  }

  // Perform the actual surface reconstruction
  std::vector<pcl::Vertices> polygons;
  res_=performReconstruction (*points, polygons, false);

  points->width = points->size ();
  points->height = 1;
  points->is_dense = true;


  deinitCompute ();
  return res_;
}


not working overload

template <typename PointInT> int
pcl::ConvexHull<PointInT>::reconstruct (PointCloudPtr & points)
{
  //points = PointCloudPtr(new PointCloud);

  points->clear();
  points->resize (0);
  points->width = 0; points->height = 0;
  points->is_dense = true;

  points->header = input_->header;
  if (!initCompute () || input_->points.empty () || indices_->empty ())
  {
    points->clear ();
    return 1;
  }

  // Perform the actual surface reconstruction
  std::vector<pcl::Vertices> polygons;
  res_=performReconstruction (*points, polygons, false);

  points->width = points->size ();
  points->height = 1;
  points->is_dense = true;


  deinitCompute ();
  return res_;
}

**Comment by mynickmynick** [comment] 2023-05-03 16:00
@mvieth  i am not sure how to use google test by a cmake project (I have used it only by visual studio projects). How can I run the test_convex_hull on a windows machine with MSVS? To try to reproduce the problem with a simple setting and few points.

**Comment by larshg** [comment] 2023-05-03 19:22
> @mvieth i am not sure how to use google test by a cmake project (I have used it only by visual studio projects). How can I run the test_convex_hull on a windows machine with MSVS? To try to reproduce the problem with a simple setting and few points.

Are you using vcpkg for dependencies?
Anyways you can see here how pcl includes gtest https://github.com/PointCloudLibrary/pcl/blob/fe19581ca50bf0d39172638cafeeec70d9473a9e/test/CMakeLists.txt#L14-L50

And subdirectories to see how to add the actual tests.
I think though, that it could be simplified a little, so maybe not the best inspiration. But hopefully enough to get you started.

**Comment by mynickmynick** [comment] 2023-05-04 10:07
@larshg thanks but my lack is more basic. I already added gtests for instance for my merge request #5690 to test/common/test_centroid.cpp
and it runs on github pipeline.
My problem is I am not sure how to run it locally on my PC sorry! ;)

**Comment by mvieth** [comment] 2023-05-05 09:26
@mynickmynick I can't give you Windows-specific advice, but you can check how they are run on our CI pipeline: https://github.com/PointCloudLibrary/pcl/blob/master/.ci/azure-pipelines/build/windows.yaml (especially the `Run Unit Tests` step).
On Linux, I often simply run the executable from the command line, e.g. `./test/common/test_centroid ../test/bun0.pcd` (when inside the build directory)

**Comment by mvieth** [comment] 2023-05-22 09:24
@mynickmynick Can I close this issue? As I said above, I checked and I am sure that the `reconstruct` function does ignore any previous contents of the output cloud, as it should. My best guess is that there is a problem in your code, maybe you copy pointers when you actually want a deep-copy of the point cloud. However, on the PCL side I don't see any problem.

**Comment by mynickmynick** [comment] 2023-05-22 10:04
I don't have time to further investigate this issue and I abandoned the looped convex hull inside segmentation cause too slow so yes close it, may be in the future I will investigate more in detail with a more simple and easy to debug application this kind of problem I had

**Closed** 2023-05-22 11:19 UTC
Labels: kind: bug, module: surface
