### ISSUE TITLE
why the coordinates axis is not at the center of the window?

### ISSUE THREAD

**Issue by DamonsJ** [PointCloudLibrary/pcl#3305] opened 2019-08-26 12:52 UTC
* Operating System and version: window 10 
* Compiler: visual studio 2017
* PCL Version: 1.9

![捕获](https://user-images.githubusercontent.com/28893028/63692005-4c4d2900-c843-11e9-9952-23bcc9c77a13.PNG)

how can I set parameter?

**Comment by larshg** [comment] 2022-03-04 21:51
I guess its centered by its boundingbox which would place it where it is now. Closing as not a bug in PCL.
You can supply X,Y,Z to addCoordinateSystem to place it else where, but resetting the camera view will probably put it back like this.

**Closed by larshg** 2022-03-04 21:51 UTC
Labels: kind: question, module: visualization, needs: feedback
