### ISSUE TITLE
Incorrect point cloud visualization in PCL

### ISSUE THREAD

**Issue by arccosxx** [PointCloudLibrary/pcl#2630] opened 2018-11-20 10:03 UTC
## Your Environment
* Operating System and version: Windows 10 1803.
* Compiler: MSVS2017
* PCL Version: 1.9.0

## Context
I am visualizing point cloud by PCL Visualizer. I need that my clouds render correctly.
Example cloud: 
PCD File: https://drive.google.com/open?id=1F0R_nR7Aqi73kSwy1cOIf3gdgaBRxsWt
XYZ File: https://drive.google.com/open?id=1P0Rwnhfk18XRyNi1xKdOoU32MqElPmze

## Expected Behavior
Here is an example of displaying this cloud in another program (Bentley Microstation). 
Right result screenshot: https://drive.google.com/open?id=1Eg9h6-VNU7na_PqjJYxdGGmIjNNlwn9p

## Current Behavior
The cloud render uncorrectly. Dots are drawn along some lines.
Wrong result screenshot: https://drive.google.com/open?id=1pHIbrsB1buytmgc-AvvCkbBqTrofPhFm

## Code to Reproduce
```
pcl::PCDReader reader;
pcl::PointCloud<pcl::PointXYZRGB>::Ptr inputCloud(new pcl::PointCloud<pcl::PointXYZRGB>);
reader.read<pcl::PointXYZRGB>("test.pcd", *inputCloud);
for (size_t i = 0; i < inputCloud->points.size(); ++i) 
{
  uint32_t rgb = (static_cast<uint32_t>(0) << 16 | static_cast<uint32_t>(75) << 8 | static_cast<uint32_t>(115));
  inputCloud->points[i].rgb = *reinterpret_cast<float*>(&rgb);
}
boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer(new pcl::visualization::PCLVisualizer("3D Viewer"));
viewer->setBackgroundColor(0, 0, 0);
viewer->addPointCloud<pcl::PointXYZRGB>(inputCloud, "SourceCloud");
while (!viewer->wasStopped())
{
     viewer->spinOnce(100);
     boost::this_thread::sleep(boost::posix_time::microseconds(100000));
}
```

Where mistake?

**Comment by arccosxx** [comment] 2018-11-21 04:35
I tested your suggestion. Firstly I opened *.xyz file in CloudCompare and secondly *.pcd file.
I saw the difference: XYZ file was rendered correctly, PCD file was rendered with lines.
I guess that there is a problem in converting XYZ to PCD.

Convert code;

```
bool
loadXYZCloud(const std::string &filename, pcl::PointCloud<pcl::PointXYZ> &cloud)
{
	std::ifstream fs;
	fs.open(filename.c_str(), std::ios::binary);
	if (!fs.is_open() || fs.fail())
	{
		fs.close();
		return (false);
	}

	std::string line;
	std::vector<std::string> st;

	while (!fs.eof())
	{
		getline(fs, line);
		// Ignore empty lines
		if (line == "")
			continue;

		// Tokenize the line
		boost::trim(line);
		boost::split(st, line, boost::is_any_of("\t\r "), boost::token_compress_on);

		if (st.size() != 3)
			continue;
		cloud.push_back(pcl::PointXYZ(float(atof(st[0].c_str())), float(atof(st[1].c_str())), float(atof(st[2].c_str()))));
	}
	fs.close();
	cloud.width = uint32_t(cloud.size()); cloud.height = 1; cloud.is_dense = true;
	return (true);
}
...
pcl::PointCloud<pcl::PointXYZ>::Ptr xyzCloud(new pcl::PointCloud<pcl::PointXYZ>);
if (!loadXYZCloud("test_orig.xyz", *xyzCloud))
    return (-1);
pcl::io::savePCDFileBinaryCompressed("test.pcd", *xyzCloud);
```
Could there be a mistake here?

And also I noticed that XYZ file opened in CloudCompare and converted to PCD file, rendered correctly in PCL Visualizer.
This file: https://drive.google.com/open?id=1MuiD7M9OAP4sPGZWN_02B9L3WknZ00mx

I noticed that the file headers are different.
**My PCD-file header:**
VERSION 0.7
FIELDS x y z
SIZE 4 4 4
TYPE F F F
COUNT 1 1 1
WIDTH 2167027
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 2167027
DATA binary_compressed

**CloudCompare PCD-file header:**
VERSION 0.7
FIELDS x y z _
SIZE 4 4 4 1
TYPE F F F U
COUNT 1 1 1 4
WIDTH 2167027
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 2167027
DATA binary

**Comment by greenbrettmichael** [comment] 2018-11-25 22:05
@arccosxx these are exactly the contents of the example xyz2pcd, https://github.com/PointCloudLibrary/pcl/blob/master/tools/xyz2pcd.cpp#L55 . This reproduces the error for me, I would bet on an issue reading some lines of the file. I will do a short investigation.

**Comment by greenbrettmichael** [comment] 2018-11-25 23:52
@arccosxx you need to scale down your data to use float. your data is stored in 9 sig figs (xxxxxxx.xx) but really has ranges ~{46.00, 24.00, 10.00}. Float eps can be estimated 1.19e-07, which means you need to limit your storage to 7 sig figs. Notice that CloudCompare gives a warning that it is scaling your data.
![image](https://user-images.githubusercontent.com/10648075/48986351-d5cba100-f0e1-11e8-89e5-794449bbd647.png)

this can easily be achieved by normalizing your data around 2323870.610,605389.440,244.510 (just picked a random point). The code below replaces the point creation line in your function.

```
if (st.size () != 3)
      continue;
double x = atof(st[0].c_str());
double y = atof(st[1].c_str());
double z = atof(st[2].c_str());
x -= 2323870.610;
y -= 605389.440;
z -= 244.510;
cloud.push_back (PointXYZ (x,y,z));
```
![image](https://user-images.githubusercontent.com/10648075/48986442-f9431b80-f0e2-11e8-91fc-e33b719808b1.png)

pcd file generated with above code^


you could also use TYPE D D D, but I do not recommend this for your data. By the way, the header from CloudCompare is different due to a known artifact of that exporter https://github.com/CloudCompare/CloudCompare/issues/776

I suggest closing this issue and moving conversation to http://www.pcl-users.org/ if you need further assistance.

**Comment by SergioRAgostinho** [comment] 2018-11-26 09:07
Thanks for helping out @greenbrettmichael.  We have more on our hands that we can usually handle so spontaneous acts of user support are really appreciated. 

@arccosxx unfortunately the mailing list is not really working at the moment, so for the time being, stick to asking questions around here. Please reopen the issues if needed.

**Closed by SergioRAgostinho** 2018-11-26 09:07 UTC
Labels: question
