### ISSUE TITLE
[Normal Estimation] Bug in implementation, compared to Open3D

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#4270] opened 2020-07-13 06:07 UTC
Bug is from normal estimation. Simple test: add a random translation to point cloud, NormalEstimation gives completely different results. Problem solved after replacing the normal estimation with an implementation from Open3D.

_Originally posted by @mitmy in https://github.com/PointCloudLibrary/pcl/issues/4102#issuecomment-657350190_

@mitmy, could you post 3 pcd in a zip file? Original cloud, cloud with errors generated using PL, reference cloud with Open3D

**Comment by SergioRAgostinho** [comment] 2020-07-13 08:41
Likely a duplicate of #2403

**Closed** 2020-07-13 14:58 UTC
Labels: kind: bug, module: features, needs: author reply
