### ISSUE TITLE
Problem with RenderViewsTesselatedSphere

### ISSUE THREAD

**Issue by Andreas93S** [PointCloudLibrary/pcl#2188] opened 2018-01-19 13:19 UTC
Hi!

I'm working on a project where I render synthetic view point clouds from CAD models using the RenderViewsTesselatedSphere-function in PCL (The version found in pcl::apps). However, I'm getting very strange results for certain views where almost all points are rendered in a plane (see Image 1 for the distorted (incorrectly rendered) point cloud vs. Image 2 which shows the correctly rendered point cloud). This does not happen every time and thus seems to be nondeterministic. I've done some research and found that it might have something to do with the sampling of the depth buffer. I've tried changing the view angle, tessellation level, vertices/faces, radius of the tessellated sphere but nothing seems to be working. I've also written a modified version of the RenderViewsTesselatedSphere-function which sets the clipping range of the vtk-camera, which unfortunately also didn't have any positive effect. My current environment is Ubuntu 14.04 LTS, gcc 4.8.5, pcl 1.8.0. I've also created a virtual machine on my Ubuntu system which runs Ubuntu 16.04 LTS, gcc 5.4.0 and pcl 1.8.0. When I run the tests on the virtual machine I don't get any errors i.e. all point clouds are rendered correctly. If I introduce a delay when rendering the view point clouds in Ubuntu 14.04 I notice that the error doesn't happen that frequently, however, the problem still persists. 

Has anyone else experienced the same problem? 

![image1](https://user-images.githubusercontent.com/35326460/35150227-e1c93cae-fd19-11e7-87b3-4e9f55ce4747.jpg)
![image2](https://user-images.githubusercontent.com/35326460/35150231-e3ef176a-fd19-11e7-852e-485b7054920f.jpg)

## Your Environment

* Operating System and version: Ubuntu 14.04 LTS
* Compiler: gcc 4.8.5
* PCL Version: 1.8.0

## Expected Behavior

Normally rendered point clouds when using the RenderViewsTesselatedSphere-function

## Current Behavior

Some rendered view point clouds are distorted where almost all points lie in a plane 

## Possible Solution

Introducing a delay between each rendering. 

## Code to Reproduce

I have a repo at https://github.com/Andreas93S/pcl_RenderViewsTessellatedSphere_example where you can download and test the example code I'm running. 

## Context

Rendering view point clouds from CAD models using the RenderViewsTesselatedSphere-function

**Comment by SergioRAgostinho** [comment] 2018-01-25 22:42
There's a previous report of problems with the same app in here https://github.com/PointCloudLibrary/pcl/issues/381 and a proposed fix on pastebin. I'm not sure if both problems are the same or not but you can give it a try in the meantime. 

I'll have a look at the things you posted to see if I can reproduce your results.

**Comment by SergioRAgostinho** [comment] 2018-01-26 00:06
I can't reproduce your results with the current pcl master branch. Have you tried that one?

![myimage](https://user-images.githubusercontent.com/1709142/35418831-a69c9988-022c-11e8-956e-1e77ee6afe19.gif)

**Comment by Andreas93S** [comment] 2018-01-26 13:20
Hi Sergio!

Thank you for your answer! Yes, it seems that you ran my example correctly. The error does not necessarily appear during during every execution though.  

I looked at the issue in https://github.com/PointCloudLibrary/pcl/issues/381 and ran the proposed fix in pastebin and got the following results after the first run:

![fix_image](https://user-images.githubusercontent.com/35326460/35440609-67369450-02a0-11e8-84e0-c97bb27baee7.jpg)

Indeed the problem still exists... Then I installed another virtual machine using Ubuntu 14.04 with the exact same specs as in the host, installing PCL from the current master branch, and got no errors when running my example. I notice that my host uses a NVIDIA GTX 1080 (driver version: 384.90) graphics card while the virtual machine (which does not have access to the GPU) uses the VMware SVGA II Adapter. I have access to another computer which also uses the same NVIDIA GTX 1080 graphics card, with the same driver installed, that also produces the same error.

**Comment by SergioRAgostinho** [comment] 2018-01-26 13:56
> Thank you for your answer! Yes, it seems that you ran my example correctly. The error does not necessarily appear during during every execution though.

Often does it happen i.e., one in how many runs? Do you normally do anything specific other than moving around the manipulator?

> Then I installed another virtual machine using Ubuntu 14.04 with the exact same specs as in the host, installing PCL from the current master branch, and got no errors when running my example. [...] I have access to another computer which also uses the same NVIDIA GTX 1080 graphics card, with the same driver installed, that also produces the same error.

So either it's fixed on the master branch or you think it's the specific driver.

From my side I'm running a GTX 1060 with the driver 387.34. 14.04 no longer has hardware updates, so you won't have an updated driver unless you manually install it.

**Comment by Andreas93S** [comment] 2018-01-30 08:27
> How often does it happen i.e., one in how many runs? Do you normally do anything specific other than moving around the manipulator?

There is no pattern unfortunately when the error occurs. This makes it very difficult since I can't reproduce the error very well. Sometimes it happens every second run and sometimes it occurs after 10 runs. What is interesting however is that it usually happens for the very first rendered view. I've tried with other CAD models and for most of them this seems to be the case (with some exceptions). I don't move the rendering window during execution either.

> So either it's fixed on the master branch or you think it's the specific driver/card.

I pulled down the latest version of PCL from Github on my Ubuntu 14.04 system which uses the NVIDIA GTX 1080 (driver version: 384.90) and was able to reproduce the error there as well. So my guess is that this might be driver/hardware related. 

One interesting observation that I mentioned in my initial post was that if I introduce a delay before rendering the first view, I almost eliminate the error completely. To do this I added the following in pcl/apps/src/render_views_tesselated_sphere.cpp:

    if(i == 0)
        sleep(1); 
    render_win->Render ();

This was purely experimental and not a very elegant solution. The duration of the delay seemed to have an impact as well. A delay smaller than ~0.1 second had very little impact on improving the results whereas a delay of ~1 second greatly improved the results (but didn't solve the problem completely).

> Worth mentioning, I'm running vtk 5.10.

I'm using VTK version: 5.8.0

**Comment by Andreas93S** [comment] 2018-06-28 08:46
Hi!

> Did you managed to find a more elegant solution? I'm having the same problem and always with the first rendered view, but for me happens every run.

No, unfortunately I never found a more elegant solution to the problem. I think that I zeroed it down to being a hardware related issue concerning the graphics card. Most of the time it was the first rendered view that came out wrong but sometimes there were other other views that came out wrong as well. 

Unfortunately, I no longer have any access to the computers which caused this behavior so I might not be of much further assistance.

However, I'm quite interested in knowing what your setup is. Most importantly what graphics card you are using.

**Comment by SergioRAgostinho** [comment] 2018-12-03 22:12
Closing due to inactivity. Please reopen if needed.

**Closed by SergioRAgostinho** 2018-12-03 22:12 UTC
Labels: status: waiting feedback
