### ISSUE TITLE
registerKeyboardCallback not working on Mac OSX

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1465] opened 2015-12-08 22:07 UTC
Reported on [StackOverflow](http://stackoverflow.com/questions/34050665/pcl-visualizer-example-cannot-acquire-keyboard-and-mouse-events).

Test code
---
```cpp
#include <iostream>
#include <pcl/visualization/pcl_visualizer.h>

void keyboardEventOccurred(const pcl::visualization::KeyboardEvent &event, void* viewer_void)
{
  boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer = *static_cast<boost::shared_ptr<pcl::visualization::PCLVisualizer> *>(viewer_void);
  if (event.getKeySym() == "r" && event.keyDown())
    std::cout << "'r' was pressed" << std::endl;
  if (event.getKeySym() == "h" && event.keyDown())
    std::cout << "'h' was pressed" << std::endl;
}

void mouseEventOccurred(const pcl::visualization::MouseEvent &event, void* viewer_void)
{
  boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer = *static_cast<boost::shared_ptr<pcl::visualization::PCLVisualizer> *>(viewer_void);

  if (event.getButton() == pcl::visualization::MouseEvent::LeftButton &&
      event.getType() == pcl::visualization::MouseEvent::MouseButtonRelease)
    std::cout << "Left mouse button released at position (" << event.getX() << ", " << event.getY() << ")" << std::endl;
}

int main()
{
  pcl::visualization::PCLVisualizer::Ptr viewer(new pcl::visualization::PCLVisualizer);
  viewer->addCoordinateSystem();
  viewer->registerKeyboardCallback(keyboardEventOccurred, (void*)&viewer);
  viewer->registerMouseCallback(mouseEventOccurred, (void*)&viewer);
  viewer->spin();
}
```

Can a Mac user confirm this issue? Please specify PCL / VTK version.

**Comment by SergioRAgostinho** [comment] 2015-12-08 22:48
:+1: I'll go over it, over the weekend.

**Comment by SergioRAgostinho** [comment] 2015-12-12 13:34
It's confirmed but I don't think there's nothing we can do about it. See http://www.vtk.org/Wiki/Cocoa_VTK#Use_Application_Bundles

**Comment by taketwo** [comment] 2015-12-12 14:50
According to the page, `set(EXECUTABLE_FLAG MACOSX_BUNDLE)` in CMake script should help?

**Comment by SergioRAgostinho** [comment] 2015-12-12 15:08
Well, the thing is if you do that, in the end you'll have a "normal" Mac application (package). This bundle option is targeted towards applications which don't really make use of terminal for printing and receiving inputs. It basically generates a container folder which holds everything your application needs for running 
For more info see https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html

Overall, this limitation is something a Mac developer has to take into account when his app makes use of VTK, not really a PCL bug.

**Comment by taketwo** [comment] 2015-12-12 15:19
I see. The person who asked this question came from the [PCLVisualizer](http://pointclouds.org/documentation/tutorials/pcl_visualizer.php) tutorial. Would you mind to add a short note for Mac users in the "Interaction Customization" section? (An example of "note" section can be seen in many other tutorials, e.g. [this one](http://pointclouds.org/documentation/tutorials/depth_sense_grabber.php)).

**Comment by SergioRAgostinho** [comment] 2015-12-12 17:12
:+1:

**Comment by SergioRAgostinho** [comment] 2015-12-12 17:27
By the way, seems this will be fixed in VTK 7.0
https://gitlab.kitware.com/vtk/vtk/merge_requests/909

**Comment by taketwo** [comment] 2015-12-12 17:31
>  The bug has only been open 10 years :)

:laughing:

Great. This is worth mentioning in the note as well, I guess.

**Comment by SergioRAgostinho** [comment] 2015-12-12 17:49
> The bug has only been open 10 years :)

:)
Makes me wonder if we should start looking around pending issues we have lying around since 2013.

**Comment by taketwo** [comment] 2015-12-12 20:51
Pending issues are like a fine wine... need time :)

Closing as this is not a bug in PCL.

**Closed by taketwo** 2015-12-12 20:51 UTC

**Comment by MartinBloedorn** [comment] 2016-02-15 12:14
Thanks for the posts here! I was running into the same problem (PCL 1.7.2, VTK 6.3.0, both installed through Homebrew). 
I haven't tried the updated VTK for now; I'd just like to share an oversimplified workaround. By setting my `CMakeLists.txt` to compile my project as an OSX App, Keyboard Event handling works OK (and terminal output still works if a run the binary in `*.app/Contents/MacOS/`). The full CMake file:

    cmake_minimum_required(VERSION` 2.8 FATAL_ERROR)
    project(pcl_project)

    find_package(PCL 1.2 REQUIRED)
    aux_source_directory(. SRC_LIST)

    include_directories(${PCL_INCLUDE_DIRS})
    link_directories(${PCL_LIBRARY_DIRS})
    add_definitions(${PCL_DEFINITIONS})

    add_executable (${PROJECT_NAME} MACOSX_BUNDLE pcl_project.cpp)
    target_link_libraries (${PROJECT_NAME} ${PCL_LIBRARIES})

    if(APPLE)
        set(EXECUTABLE_FLAG MACOSX_BUNDLE)
        set(MACOSX_BUNDLE_BUNDLE_NAME ${PROJECT_NAME})
        set_target_properties(${PROJECT_NAME} PROPERTIES MACOSX_BUNDLE TRUE)
    endif(APPLE)

When closing the Window, the `while (!viewer->wasStopped ())` loop still hangs as it did before, but at least keyboard seems to be functioning nicely.

**Comment by jbuck167** [comment] 2017-09-22 15:13
Sorry to report this but it appears that the keyboard & mouse no longer work on Mac OS 10.12.6 with pcl 1.8.1 (Homebrew stable version at time of posting) + VTK 7.1.1 (Homebrew 7.1.1_1). Supposedly in VTK 8.0.1 (Homebrew stable version at time of posting), the keyboard & mouse work, but I have not been able to get pcl 1.8.1 to link with VTK 8.0.1 to confirm. 

The note in pcl_visualizer tutorial can be changed.

**Comment by SergioRAgostinho** [comment] 2017-09-22 16:52
It was already part of VTK 7.0.0 rc1. Can you test their examples in isolated fashion to make sure it's already working normally there. See https://gitlab.kitware.com/vtk/vtk/issues/2025 for more info.
