### ISSUE TITLE
compiler error: in add_stack_var, at cfgexpand.c:456 when building with Spack

### ISSUE THREAD

**Issue by mlawsonca** [PointCloudLibrary/pcl#4573] opened 2021-01-16 00:35 UTC
I am working with Spack to try and get pcl available as a package. However, I run into the following error:
`/var/tmp/mlawso/spack-stage/spack-stage-pcl-1.11.1-rk6vazv2wwcdj4tnosovbtpauofytilx/spack-src/octree/include/pcl/octree/impl/octree_pointcloud.hpp:331:1: internal compiler error: in add_stack_var, at cfgexpand.c:456
`

The issue can be seen fully at [https://github.com/spack/spack/issues/20984](url), with all dependencies included in [spack-build-env(1).txt](https://github.com/PointCloudLibrary/pcl/files/5823506/spack-build-env.1.txt) and the build output included in [spack-build-out.txt](https://github.com/PointCloudLibrary/pcl/files/5823505/spack-build-out.txt)

**Comment by mvieth** [comment] 2021-01-16 09:00
I can say that PCL compiles fine with gcc 10.2.0, so the problem is likely not with PCL. You can try to compile PCL on your system, without spack, to confirm this.
I noticed in spack-build-out.txt that sometimes gcc 4.9.3 appears, and I found this bug report https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64164 which might be related. Is it possible that two compilers are mixed?

**Comment by mlawsonca** [comment] 2021-01-16 09:29
I tried compiling it on my system without spack and obtained the same error:
```
Scanning dependencies of target pcl_octree
[  7%] Building CXX object octree/CMakeFiles/pcl_octree.dir/src/octree_inst.cpp.o
...
In file included from /vscratch1/username/pcl/octree/include/pcl/octree/impl/octree_pointcloud_adjacency.hpp:50,
                 from /vscratch1/username/pcl/octree/include/pcl/octree/octree_pointcloud_adjacency.h:248,
                 from /vscratch1/username/pcl/octree/include/pcl/octree/octree.h:45,
                 from /vscratch1/username/pcl/octree/src/octree_inst.cpp:37:
/vscratch1/username/pcl/octree/include/pcl/octree/impl/octree_pointcloud.hpp: In member function 'void pcl::octree::OctreePointCloud<PointT, LeafContainerT, BranchContainerT, OctreeT>::defineBoundingBox() [with PointT = pcl::PointXYZ; LeafContainerT = pcl::octree::OctreeContainerPointIndices; BranchContainerT = pcl::octree::OctreeContainerEmpty; OctreeT = pcl::octree::OctreeBase<pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty>]':
/vscratch1/username/pcl/octree/include/pcl/octree/impl/octree_pointcloud.hpp:331:1: internal compiler error: in add_stack_var, at cfgexpand.c:456
  331 | pcl::octree::OctreePointCloud<PointT, LeafContainerT, BranchContainerT, OctreeT>::
      | ^~~
0x104ad383 add_stack_var
    /var/tmp/username/spack-stage/spack-stage-gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/spack-src/gcc/cfgexpand.c:456
0x104affdb expand_one_ssa_partition
    /var/tmp/username/spack-stage/spack-stage-gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/spack-src/gcc/cfgexpand.c:1425
0x104affdb expand_used_vars
    /var/tmp/username/spack-stage/spack-stage-gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/spack-src/gcc/cfgexpand.c:2068
0x104b2707 execute
    /var/tmp/username/spack-stage/spack-stage-gcc-10.2.0-htozopzbdwvoc5wxwgi5fitjqjbhrphr/spack-src/gcc/cfgexpand.c:6410
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://github.com/spack/spack/issues> for instructions.
make[2]: *** [octree/CMakeFiles/pcl_octree.dir/build.make:82: octree/CMakeFiles/pcl_octree.dir/src/octree_inst.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:994: octree/CMakeFiles/pcl_octree.dir/all] Error 2
```

gcc-4.9.3 appears as gcc-4.9.3/gcc-10.2.0 because gcc-4.9.3 is the compiler that was used to compiler gcc-10.2.0. It doesn't have any other involvement in the build.

**Comment by mvieth** [comment] 2021-01-16 09:53
Can you try compiling PCL with a not-self-compiled compiler?

**Comment by mlawsonca** [comment] 2021-01-16 20:12
I was able to build with gcc 8.3.1 that was installed on the machine. Not sure why 10.2.0 ran into issues (particularly considering all of the other packages that I recently compiled with it). But thank you

**Comment by mvieth** [comment] 2021-01-17 09:39
As mentioned, I can compile PCL with gcc 10.2.0 (not self compiled), so the version does not seem to be the problem. You could try to compile your gcc 10.2.0 with your gcc 8.3.1 instead of gcc 4.9.3, maybe then it works.
Anyway, I am going to close this issue, since I don't see any problem with PCL. If you do find a problem with PCL after all, feel free to reopen this.

**Closed by mvieth** 2021-01-17 09:39 UTC
Labels: kind: compile error, status: triage
