### ISSUE TITLE
Boost 1.67.0 failure: error: called object type 'nullptr_t' is not a function or function pointer

### ISSUE THREAD

**Issue by yurivict** [PointCloudLibrary/pcl#2349] opened 2018-06-21 06:59 UTC
```
In file included from /usr/local/include/boost/preprocessor/iteration/detail/iter/forward1.hpp:67:
In file included from /usr/local/include/boost/function/detail/function_iterate.hpp:14:
In file included from /usr/local/include/boost/function/detail/maybe_include.hpp:43:
/usr/local/include/boost/function/function_template.hpp:159:33: error: called object type 'nullptr_t' is not a function or function pointer
          BOOST_FUNCTION_RETURN((*f)(BOOST_FUNCTION_ARGS));
                                ^~~~
/usr/local/include/boost/function/function_template.hpp:81:36: note: expanded from macro 'BOOST_FUNCTION_RETURN'
#  define BOOST_FUNCTION_RETURN(X) X
                                   ^
/usr/local/include/boost/function/function_template.hpp:934:53: note: in instantiation of member function 'boost::detail::function::void_function_obj_invoker4<nullptr_t, void, const pcl::PointCloud<pcl::PointNormal> &, const std::__1::vector<int, std::__1::allocator<int> > &, const pcl::PointCloud<pcl::PointNormal> &, const std::__1::vector<int, std::__1::allocator<int> > &>::invoke' requested here
        { { &manager_type::manage }, &invoker_type::invoke };
                                                    ^
/usr/local/include/boost/function/function_template.hpp:725:13: note: in instantiation of function template specialization 'boost::function4<void, const pcl::PointCloud<pcl::PointNormal> &, const std::__1::vector<int, std::__1::allocator<int> > &, const pcl::PointCloud<pcl::PointNormal> &, const std::__1::vector<int, std::__1::allocator<int> > &>::assign_to<nullptr_t>' requested here
      this->assign_to(f);
            ^
/usr/local/include/boost/function/function_template.hpp:1070:5: note: in instantiation of function template specialization 'boost::function4<void, const pcl::PointCloud<pcl::PointNormal> &, const std::__1::vector<int, std::__1::allocator<int> > &, const pcl::PointCloud<pcl::PointNormal> &, const std::__1::vector<int, std::__1::allocator<int> > &>::function4<nullptr_t>' requested here
    base_type(f)
    ^
/wrkdirs/usr/ports/graphics/pcl-pointclouds/work/pcl-pcl-1.8.1/registration/include/pcl/registration/registration.h:126:11: note: in instantiation of function template specialization 'boost::function<void (const pcl::PointCloud<pcl::PointNormal> &, const std::__1::vector<int, std::__1::allocator<int> > &, const pcl::PointCloud<pcl::PointNormal> &, const std::__1::vector<int, std::__1::allocator<int> > &)>::function<nullptr_t>' requested here
        , update_visualizer_ (NULL)
          ^
/wrkdirs/usr/ports/graphics/pcl-pointclouds/work/pcl-pcl-1.8.1/registration/include/pcl/registration/icp.h:137:7: note: in instantiation of member function 'pcl::Registration<pcl::PointNormal, pcl::PointNormal, float>::Registration' requested here
      IterativeClosestPoint () 
      ^
/wrkdirs/usr/ports/graphics/pcl-pointclouds/work/pcl-pcl-1.8.1/recognition/src/face_detection/rf_face_detector_trainer.cpp:479:68: note: in instantiation of member function 'pcl::IterativeClosestPoint<pcl::PointNormal, pcl::PointNormal, float>::IterativeClosestPoint' requested here
    pcl::IterativeClosestPoint<pcl::PointNormal, pcl::PointNormal> reg;
                                                                   ^
```

Build log: http://beefy11.nyi.freebsd.org/data/head-i386-default/p472945_s335462/logs/pcl-pointclouds-1.8.1_5.log (IPv6-only)

**Comment by taketwo** [comment] 2018-06-21 13:59
Please post more information about your environment, especially boost version. But ideally, just fix it and send a PR ;)

**Comment by yurivict** [comment] 2018-06-21 16:31
To clarify here: I am a port maintainer. I created the port and maintain it, I don't actually use PCL. Some other people probably use it. So I can't fix problems like this, especially when I don't know anything about the code.

**Comment by taketwo** [comment] 2018-06-21 16:36
@yurivict no problem, thanks for reporting anyway!

I wanted to check the boost version myself, but can not access the log file ("Unable to connect"). Does your comment "IPv6-only" imply I need to do something special to download it?

**Comment by yurivict** [comment] 2018-06-21 17:27
Sorry, this URL is on IPv6-only network. No IPv4 access.
One way to access it is through the Tor network. Are you familiar with Tor/have Tor installed and proxy settings in the browser? If not, I will post the log text somewhere else...

**Comment by yurivict** [comment] 2018-06-21 17:43
[pcl-pointclouds-1.8.1_5.log](https://github.com/PointCloudLibrary/pcl/files/2124743/pcl-pointclouds-1.8.1_5.log)

**Comment by alkavan** [comment] 2018-07-01 05:56
It's worth to note I'm having the same issue with Boost 1.67 on Win10 + vcpkg.
I suspect this is something needs to be fixed in PCL at some point. I'll be glad to help, but I'm not sure I understand the issue here, is this just something that needs to be refactored in many places?

Anyway, I must wonder, if nowadays, Boost somewhat of an overhead...

**Comment by taketwo** [comment] 2018-07-01 18:36
The issue is that `NULL` is apparently not a proper initializer for `boost::function` anymore. I think it's not necessary to explicitly initialize `update_visualizer_` at all, the default-constructed empty function will be just fine, so that line can be dropped.

> Anyway, I must wonder, if nowadays, Boost somewhat of an overhead...

What do you suggest?

**Comment by taketwo** [comment] 2018-08-31 16:09
@alkavan did you have a chance to try the changes I proposed?

**Comment by taketwo** [comment] 2018-09-02 22:33
@jbeich Thanks for confirming. Would you mind to send a pull request?

**Closed** 2018-09-10 07:32 UTC
