### ISSUE TITLE
[custom] error: macro "_mm512_srli_epi32" passed 3 arguments, but takes just 2

### ISSUE THREAD

**Issue by hitbuyi** [PointCloudLibrary/pcl#6020] opened 2024-04-26 04:07 UTC
pcl 12.1 built from source in Ubuntu20.04, build process 
```
git clone  https://github.com/PointCloudLibrary/pcl.git
cd pcl
git checkout pcl-1.12.1
cmake -DBUILD_2d=ON -DBUILD_CUDA=ON -DBUILD_GPU=ON -DBUILD_TESTS=ON -DBUILD_apps=ON -DBUILD_common=ON -DBUILD_cuda_apps=ON -DBUILD_cuda_common=ON -DBUILD_cuda_features=ON -DBUILD_cuda_filters_include_pcl_cuda_filters=ON -DBUILD_cuda_io=ON -DBUILD_cuda_sample_consensus=ON -DBUILD_cuda_segmentation=ON -DBUILD_examples=ON -DBUILD_features=ON -DBUILD_filters=ON -DBUILD_geometry=ON -DBUILD_global_tests=ON -DBUILD_gpu_containers=ON -DBUILD_gpu_features=ON -DBUILD_gpu_kinfu=ON -DBUILD_gpu_kinfu_large_scale=ON -DBUILD_gpu_octree=ON -DBUILD_gpu_people=ON -DBUILD_gpu_segmentation=ON -DBUILD_gpu_surface=ON -DBUILD_gpu_tracking=ON -DBUILD_gpu_utils=ON -DBUILD_io=ON -DBUILD_kdtree=ON -DBUILD_keypoints=ON -DBUILD_ml=ON -DBUILD_octree=ON -DBUILD_outofcore=ON -DBUILD_recognition=ON -DBUILD_registration=ON -DBUILD_sample_consensus=ON -DBUILD_search=ON -DBUILD_segmentation=ON -DBUILD_simulation=OFF -DBUILD_stereo=ON -DBUILD_surface=ON -DBUILD_surface_on_nurbs=OFF -DBUILD_tools=ON -DBUILD_tracking=ON -DBUILD_visualization=ON ..
-- Found ClangFormat: /usr/bin/clang-format-10 (found suitable version "10.0.0", minimum required is "10") 
-- Adding target 'format'
-- Using CPU native flags for SSE optimization: -msse4.2 -mfpmath=sse -march=native
-- Found OpenMP, spec date 201511
-- Eigen found (include: /usr/local/include/eigen3, version: 3.3.90)
-- FLANN found (include: /usr/include, lib: /usr/lib/x86_64-linux-gnu/libflann_cpp.so)
-- Checking for module 'metslib'
--   No package 'metslib' found
-- QHULL found (include: /usr/include, lib: /usr/lib/x86_64-linux-gnu/libqhull_r.so)
CMake Warning (dev) at cmake/pcl_find_cuda.cmake:8 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:363 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found CUDA Toolkit v11.3
-- CMAKE_CUDA_ARCHITECTURES: 35;37;50;52;53;60;61;62;70;72;75;80;86
-- Qt version: 5.12.8
CMake Deprecation Warning at cmake/pcl_find_qt.cmake:61 (cmake_policy):
  The OLD behavior for policy CMP0100 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:383 (include)


-- GTest found (include: /usr/include, src: /usr/src/gtest)
-- DOXYGEN_FOUND 
-- HTML_HELP_COMPILER 
-- Found CPack generators: DEB
-- PCL build with following flags:
--  -Wabi=11 -Wall -Wextra -Wno-unknown-pragmas -fno-strict-aliasing -Wno-format-extra-args -Wno-sign-compare -Wno-invalid-offsetof -Wno-conversion -msse4.2 -mfpmath=sse -march=native -mavx2 -fopenmp
-- The following subsystems will be built:
--   common
--   kdtree
--   octree
--   search
--   sample_consensus
--   filters
--   2d
--   geometry
--   io
--   features
--   ml
--   segmentation
--   surface
--   registration
--   keypoints
--   tracking
--   recognition
--   stereo
--   cuda_common
--   cuda_features
--   cuda_segmentation
--   cuda_sample_consensus
--   gpu_containers
--   gpu_utils
--   gpu_octree
--   gpu_features
--   gpu_kinfu
       building: 
       |_ tools
--   gpu_kinfu_large_scale
       building: 
       |_ tools
--   gpu_segmentation
--   gpu_surface
--   gpu_tracking
--   global_tests
--   tests_2d
--   tests_common
--   tests_features
--   tests_filters
--   tests_geometry
--   tests_gpu_octree
--   tests_io
--   tests_kdtree
--   tests_keypoints
--   tests_ml
--   tests_octree
--   tests_recognition
--   tests_registration
--   tests_search
--   tests_surface
--   tests_segmentation
--   tests_sample_consensus
--   tools
-- The following subsystems will not be built:
--   visualization: Requires external library vtk.
--   apps: Requires visualization.
--   benchmarks: Disabled by default
--   cuda_io: Requires external library openni.
--   cuda_apps: Requires visualization.
--   outofcore: Requires visualization.
--   examples: Requires outofcore.
--   gpu_people: Requires visualization.
--   people: Requires visualization.
--   simulation: Disabled by default.
--   tests_people: Requires visualization.
--   tests_outofcore: Requires visualization.
--   tests_visualization: Requires visualization.
-- Configuring done (0.4s)
-- Generating done (0.3s)
-- Build files have been written to: /home/hitbuyi/PCL/pcl-1.12.1/build
```
it build successfully, but when  I  runned a simple test code,  
test_pcl.cpp
```
#include <iostream>
#include <pcl/common/common_headers.h>
#include <pcl/io/pcd_io.h>
#include <pcl/visualization/pcl_visualizer.h>
#include <pcl/visualization/cloud_viewer.h>
#include <pcl/console/parse.h>
 
 
int main(int argc, char **argv) {
    std::cout << "Test PCL !!!" << std::endl;
    
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr point_cloud_ptr (new pcl::PointCloud<pcl::PointXYZRGB>);
    uint8_t r(255), g(15), b(15);
    for (float z(-1.0); z <= 1.0; z += 0.05)
    {
      for (float angle(0.0); angle <= 360.0; angle += 5.0)
      {
	pcl::PointXYZRGB point;
	point.x = 0.5 * cosf (pcl::deg2rad(angle));
	point.y = sinf (pcl::deg2rad(angle));
	point.z = z;
	uint32_t rgb = (static_cast<uint32_t>(r) << 16 |
		static_cast<uint32_t>(g) << 8 | static_cast<uint32_t>(b));
	point.rgb = *reinterpret_cast<float*>(&rgb);
	point_cloud_ptr->points.push_back (point);
      }
      if (z < 0.0)
      {
	r -= 12;
	g += 12;
      }
      else
      {
	g -= 12;
	b += 12;
      }
    }
    point_cloud_ptr->width = (int) point_cloud_ptr->points.size ();
    point_cloud_ptr->height = 1;
    
    pcl::visualization::CloudViewer viewer ("test");
    viewer.showCloud(point_cloud_ptr);
    while (!viewer.wasStopped()){ };
    return 0;
}
```

CMakeLists.txt

```
cmake_minimum_required(VERSION 2.6)
project(pcl_test)

set(Boost_DEBUG ON)
set(BOOST_LIBRARYDIR /usr/lib/x86_64-linux-gnu)

find_package(PCL  REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable(pcl_test pcl_test.cpp)

target_link_libraries (pcl_test ${PCL_LIBRARIES})

install(TARGETS pcl_test RUNTIME DESTINATION bin)

```

$ cmake ..
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /usr/local/share/pcl-1.12/PCLConfig.cmake:142 (find_package):
  Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
  variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  CMake variable EIGEN_ROOT is set to:

    /usr/local/include/eigen3

  For compatibility, find_package is ignoring the variable, but code in a
  .cmake module might still use it.
Call Stack (most recent call first):
  /usr/local/share/pcl-1.12/PCLConfig.cmake:295 (find_eigen)
  /usr/local/share/pcl-1.12/PCLConfig.cmake:538 (find_external_library)
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'eigen3'
--   Found eigen3, version 3.3.90
-- Found Eigen: /usr/local/include/eigen3 (Required is at least version "3.1") 
-- Eigen found (include: /usr/local/include/eigen3, version: 3.3.90)
-- Found Boost 1.78.0 at /usr/local/lib/cmake/Boost-1.78.0
--   Requested configuration: QUIET COMPONENTS system;filesystem;date_time;iostreams;serialization
-- BoostConfig: find_package(boost_headers 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Found boost_headers 1.78.0 at /usr/local/lib/cmake/boost_headers-1.78.0
-- BoostConfig: find_package(boost_system 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Found boost_system 1.78.0 at /usr/local/lib/cmake/boost_system-1.78.0
-- Boost toolset is gcc9 (GNU 9.4.0)
-- Scanning /usr/local/lib/cmake/boost_system-1.78.0/libboost_system-variant*.cmake
--   Including /usr/local/lib/cmake/boost_system-1.78.0/libboost_system-variant-shared.cmake
--   [x] libboost_system.so.1.78.0
--   Including /usr/local/lib/cmake/boost_system-1.78.0/libboost_system-variant-static.cmake
--   [ ] libboost_system.a
-- Adding boost_system dependencies: headers
-- BoostConfig: find_package(boost_filesystem 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Found boost_filesystem 1.78.0 at /usr/local/lib/cmake/boost_filesystem-1.78.0
-- Boost toolset is gcc9 (GNU 9.4.0)
-- Scanning /usr/local/lib/cmake/boost_filesystem-1.78.0/libboost_filesystem-variant*.cmake
--   Including /usr/local/lib/cmake/boost_filesystem-1.78.0/libboost_filesystem-variant-shared.cmake
--   [x] libboost_filesystem.so.1.78.0
--   Including /usr/local/lib/cmake/boost_filesystem-1.78.0/libboost_filesystem-variant-static.cmake
--   [ ] libboost_filesystem.a
-- Adding boost_filesystem dependencies: atomic;headers
-- Found boost_atomic 1.78.0 at /usr/local/lib/cmake/boost_atomic-1.78.0
-- Boost toolset is gcc9 (GNU 9.4.0)
-- Scanning /usr/local/lib/cmake/boost_atomic-1.78.0/libboost_atomic-variant*.cmake
--   Including /usr/local/lib/cmake/boost_atomic-1.78.0/libboost_atomic-variant-shared.cmake
--   [x] libboost_atomic.so.1.78.0
--   Including /usr/local/lib/cmake/boost_atomic-1.78.0/libboost_atomic-variant-static.cmake
--   [ ] libboost_atomic.a
-- Adding boost_atomic dependencies: headers
-- BoostConfig: find_package(boost_date_time 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Found boost_date_time 1.78.0 at /usr/local/lib/cmake/boost_date_time-1.78.0
-- Boost toolset is gcc9 (GNU 9.4.0)
-- Scanning /usr/local/lib/cmake/boost_date_time-1.78.0/libboost_date_time-variant*.cmake
--   Including /usr/local/lib/cmake/boost_date_time-1.78.0/libboost_date_time-variant-shared.cmake
--   [x] libboost_date_time.so.1.78.0
--   Including /usr/local/lib/cmake/boost_date_time-1.78.0/libboost_date_time-variant-static.cmake
--   [ ] libboost_date_time.a
-- Adding boost_date_time dependencies: headers
-- BoostConfig: find_package(boost_iostreams 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Found boost_iostreams 1.78.0 at /usr/local/lib/cmake/boost_iostreams-1.78.0
-- Boost toolset is gcc9 (GNU 9.4.0)
-- Scanning /usr/local/lib/cmake/boost_iostreams-1.78.0/libboost_iostreams-variant*.cmake
--   Including /usr/local/lib/cmake/boost_iostreams-1.78.0/libboost_iostreams-variant-shared.cmake
--   [x] libboost_iostreams.so.1.78.0
--   Including /usr/local/lib/cmake/boost_iostreams-1.78.0/libboost_iostreams-variant-static.cmake
--   [ ] libboost_iostreams.a
-- Adding boost_iostreams dependencies: headers
-- BoostConfig: find_package(boost_serialization 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Found boost_serialization 1.78.0 at /usr/local/lib/cmake/boost_serialization-1.78.0
-- Boost toolset is gcc9 (GNU 9.4.0)
-- Scanning /usr/local/lib/cmake/boost_serialization-1.78.0/libboost_serialization-variant*.cmake
--   Including /usr/local/lib/cmake/boost_serialization-1.78.0/libboost_serialization-variant-shared.cmake
--   [x] libboost_serialization.so.1.78.0
--   Including /usr/local/lib/cmake/boost_serialization-1.78.0/libboost_serialization-variant-static.cmake
--   [ ] libboost_serialization.a
-- Adding boost_serialization dependencies: headers
-- Found Boost: /usr/local/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.65.0") found components: system filesystem date_time iostreams serialization 
CMake Warning (dev) at /usr/local/share/pcl-1.12/Modules/FindFLANN.cmake:44 (find_package):
  Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
  variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  CMake variable FLANN_ROOT is set to:

    /usr

  For compatibility, find_package is ignoring the variable, but code in a
  .cmake module might still use it.
Call Stack (most recent call first):
  /usr/local/share/pcl-1.12/PCLConfig.cmake:252 (find_package)
  /usr/local/share/pcl-1.12/PCLConfig.cmake:297 (find_flann)
  /usr/local/share/pcl-1.12/PCLConfig.cmake:538 (find_external_library)
  CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'flann'
--   Found flann, version 1.9.1
-- Found FLANN: /usr/lib/x86_64-linux-gnu/libflann_cpp.so  
-- FLANN found (include: /usr/include, lib: /usr/lib/x86_64-linux-gnu/libflann_cpp.so)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components: OpenGL GLX 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.23
-- Found libusb: /usr/lib/x86_64-linux-gnu/libusb-1.0.so  
-- Found OpenNI2: /usr/lib/libOpenNI2.so;libusb::libusb (found version "2.2.0.33") 
-- OpenNI2 found (version: 2.2.0.33, include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so;libusb::libusb)
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- Found Boost 1.78.0 at /usr/local/lib/cmake/Boost-1.78.0
--   Requested configuration: QUIET COMPONENTS system;filesystem;date_time;iostreams;serialization
-- BoostConfig: find_package(boost_headers 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- BoostConfig: find_package(boost_system 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- BoostConfig: find_package(boost_filesystem 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- BoostConfig: find_package(boost_date_time 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- BoostConfig: find_package(boost_iostreams 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- BoostConfig: find_package(boost_serialization 1.78.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Eigen found (include: /usr/local/include/eigen3, version: 3.3.90)
-- OpenNI2 found (version: 2.2.0.33, include: /usr/include/openni2, lib: /usr/lib/libOpenNI2.so;libusb::libusb)
-- Found Qhull: /usr/lib/x86_64-linux-gnu/libqhull_r.so  
-- QHULL found (include: /usr/include, lib: /usr/lib/x86_64-linux-gnu/libqhull_r.so)
-- looking for PCL_COMMON
-- Found PCL_COMMON: /usr/local/lib/libpcl_common.so  
-- looking for PCL_KDTREE
-- Found PCL_KDTREE: /usr/local/lib/libpcl_kdtree.so  
-- looking for PCL_OCTREE
-- Found PCL_OCTREE: /usr/local/lib/libpcl_octree.so  
-- looking for PCL_SEARCH
-- Found PCL_SEARCH: /usr/local/lib/libpcl_search.so  
-- looking for PCL_SAMPLE_CONSENSUS
-- Found PCL_SAMPLE_CONSENSUS: /usr/local/lib/libpcl_sample_consensus.so  
-- looking for PCL_FILTERS
-- Found PCL_FILTERS: /usr/local/lib/libpcl_filters.so  
-- looking for PCL_2D
-- Found PCL_2D: /usr/local/include/pcl-1.12  
-- looking for PCL_GEOMETRY
-- Found PCL_GEOMETRY: /usr/local/include/pcl-1.12  
-- looking for PCL_IO
-- Found PCL_IO: /usr/local/lib/libpcl_io.so  
-- looking for PCL_FEATURES
-- Found PCL_FEATURES: /usr/local/lib/libpcl_features.so  
-- looking for PCL_ML
-- Found PCL_ML: /usr/local/lib/libpcl_ml.so  
-- looking for PCL_SEGMENTATION
-- Found PCL_SEGMENTATION: /usr/local/lib/libpcl_segmentation.so  
-- looking for PCL_VISUALIZATION
-- Found PCL_VISUALIZATION: /usr/local/lib/libpcl_visualization.so  
-- looking for PCL_SURFACE
-- Found PCL_SURFACE: /usr/local/lib/libpcl_surface.so  
-- looking for PCL_REGISTRATION
-- Found PCL_REGISTRATION: /usr/local/lib/libpcl_registration.so  
-- looking for PCL_KEYPOINTS
-- Found PCL_KEYPOINTS: /usr/local/lib/libpcl_keypoints.so  
-- looking for PCL_TRACKING
-- Found PCL_TRACKING: /usr/local/lib/libpcl_tracking.so  
-- looking for PCL_RECOGNITION
-- Found PCL_RECOGNITION: /usr/local/lib/libpcl_recognition.so  
-- looking for PCL_STEREO
-- Found PCL_STEREO: /usr/local/lib/libpcl_stereo.so  
-- looking for PCL_OUTOFCORE
-- Found PCL_OUTOFCORE: /usr/local/lib/libpcl_outofcore.so  
-- looking for PCL_PEOPLE
-- Found PCL_PEOPLE: /usr/local/lib/libpcl_people.so  
-- Found PCL: pcl_common;pcl_kdtree;pcl_octree;pcl_search;pcl_sample_consensus;pcl_filters;pcl_io;pcl_features;pcl_ml;pcl_segmentation;pcl_visualization;pcl_surface;pcl_registration;pcl_keypoints;pcl_tracking;pcl_recognition;pcl_stereo;pcl_outofcore;pcl_people;Boost::system;Boost::filesystem;Boost::date_time;Boost::iostreams;Boost::serialization;/usr/lib/libOpenNI2.so;libusb::libusb;VTK::ChartsCore;VTK::CommonColor;VTK::CommonComputationalGeometry;VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::CommonMath;VTK::CommonMisc;VTK::CommonTransforms;VTK::FiltersCore;VTK::FiltersExtraction;VTK::FiltersGeneral;VTK::FiltersGeometry;VTK::FiltersModeling;VTK::FiltersSources;VTK::ImagingCore;VTK::ImagingSources;VTK::InteractionImage;VTK::InteractionStyle;VTK::InteractionWidgets;VTK::IOCore;VTK::IOGeometry;VTK::IOImage;VTK::IOLegacy;VTK::IOPLY;VTK::RenderingAnnotation;VTK::RenderingCore;VTK::RenderingContext2D;VTK::RenderingLOD;VTK::RenderingFreeType;VTK::ViewsCore;VTK::ViewsContext2D;VTK::RenderingOpenGL2;VTK::GUISupportQt;FLANN::FLANN;QHULL::QHULL  
-- Configuring done (1.6s)
-- Generating done (0.0s)
-- Build files have been written to: /media/hitbuyi/56C445CFC445B1D3/Lidar/PCL/install_remove/test_pcl/build
```

`$ make `

```
[ 50%] Building CXX object CMakeFiles/pcl_test.dir/pcl_test.cpp.o
In file included from /usr/local/include/eigen3/Eigen/Core:180,
                 from /usr/local/include/eigen3/Eigen/StdVector:14,
                 from /usr/local/include/pcl-1.12/pcl/point_cloud.h:45,
                 from /usr/local/include/pcl-1.12/pcl/common/common.h:47,
                 from /usr/local/include/pcl-1.12/pcl/common/common_headers.h:38,
                 from /media/hitbuyi/56C445CFC445B1D3/Lidar/PCL/install_remove/test_pcl/pcl_test.cpp:2:
/usr/local/include/eigen3/Eigen/src/Core/arch/AVX512/MathFunctions.h:75:97: error: macro "_mm512_srli_epi32" passed 3 arguments, but takes just 2
   75 |   Packet16f emm0 = _mm512_cvtepi32_ps(_mm512_srli_epi32(preinterpret<Packet16i,Packet16f>(x), 23));
      |                                                                                                 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:55,
                 from /usr/local/include/pcl-1.12/pcl/common/common.h:44,
                 from /usr/local/include/pcl-1.12/pcl/common/common_headers.h:38,
                 from /media/hitbuyi/56C445CFC445B1D3/Lidar/PCL/install_remove/test_pcl/pcl_test.cpp:2:
/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h:1352: note: macro "_mm512_srli_epi32" defined here
 1352 | #define _mm512_srli_epi32(X, C)          \
      | 
In file included from /usr/local/include/eigen3/Eigen/Core:180,
                 from /usr/local/include/eigen3/Eigen/StdVector:14,
                 from /usr/local/include/pcl-1.12/pcl/point_cloud.h:45,
                 from /usr/local/include/pcl-1.12/pcl/common/common.h:47,
                 from /usr/local/include/pcl-1.12/pcl/common/common_headers.h:38,
                 from /media/hitbuyi/56C445CFC445B1D3/Lidar/PCL/install_remove/test_pcl/pcl_test.cpp:2:
/usr/local/include/eigen3/Eigen/src/Core/arch/AVX512/MathFunctions.h: In function ‘Packet Eigen::internal::plog(const Packet&) [with Packet = __vector(16) float]’:
/usr/local/include/eigen3/Eigen/src/Core/arch/AVX512/MathFunctions.h:75:39: error: ‘_mm512_srli_epi32’ was not declared in this scope
   75 |   Packet16f emm0 = _mm512_cvtepi32_ps(_mm512_srli_epi32(preinterpret<Packet16i,Packet16f>(x), 23));
      |                                       ^~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/pcl_test.dir/build.make:76: CMakeFiles/pcl_test.dir/pcl_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/pcl_test.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
an error occured during the make stage.  I tried pcl v1.13, v1.14, even v1.10,  same error  occured, any help will be appreciated

**Comment by mvieth** [comment] 2024-04-26 08:27
@hitbuyi This seems more like an Eigen problem than a PCL problem. What Eigen version are you using? The CMake log says 3.3.90, so this is not the default Eigen version on Ubuntu 20.04. But which Eigen branch or tag are you using? Have you tried a different Eigen version, e.g. 3.3.7 or 3.4.0?

**Comment by hitbuyi** [comment] 2024-04-26 09:12
> @hitbuyi This seems more like an Eigen problem than a PCL problem. What Eigen version are you using? The CMake log says 3.3.90, so this is not the default Eigen version on Ubuntu 20.04. But which Eigen branch or tag are you using? Have you tried a different Eigen version, e.g. 3.3.7 or 3.4.0?

It did a Eigen bug, I found[ here](http://dalab.se.sjtu.edu.cn/gitlab/xiaoyuwei/eigen/-/commit/452371cead5e83131a816b1069e1aec4b9c6cf36), when I change Eigen to  v3.4.0,  the problem solved.

**Comment by mvieth** [comment] 2024-04-26 09:59
Okay, so it seems you used the `before-git-migration` tag from the Eigen repository. I don't know what that tag is supposed to represent, but it certainly is not a stable release. Choose a release like 3.4.0 or 3.3.9, otherwise you are indeed more likely to encounter bugs.
Closing this issue since the problem is solved.

**Closed by mvieth** 2024-04-26 09:59 UTC
Labels: kind: compile error
