### ISSUE TITLE
Make lineWithLineIntersection return centroid

### ISSUE THREAD

**Issue by Kaju-Bubanja** [PointCloudLibrary/pcl#2378] opened 2018-07-17 13:41 UTC
## Your Environment

* Operating System and version:
* Compiler:
* PCL Version:

## Context

I was wondering why [lineWithLineIntersection](https://github.com/PointCloudLibrary/pcl/blob/bba5936c1b7e4319597dadea940dab98b1cb06da/common/include/pcl/common/impl/intersections.hpp) returns the first point of the segment and not the centroid between p1 and p2?
Wouldn't returning the centroid be strictly better especially when the epsilon gets increased by the user?
Is the reason computational cost or would this be a good change?

## Expected Behavior

Make lineWithLineIntersection return the centroid of the found line segment.

**Comment by taketwo** [comment] 2018-07-17 13:54
Please define "strictly better".

**Comment by Kaju-Bubanja** [comment] 2018-07-17 14:20
Maybe strictly better is not the right word, but I think taking the centroid would be less surprising. Assuming you have a large epsilon and a large line segment the centroid could still be useful, while p1 or p2 could be off(ofc depending on what you want to do). I use it to estimate the center of a cube with two normals from plane centers belonging to the cube. And if the plane segmentation is not good the centroids might be off and subsequently the line with line intersection is off, while the centroid is better. But maybe I'm overthinking this and it is only useful in my use case.

**Comment by taketwo** [comment] 2018-07-17 14:40
> ofc depending on what you want to do

I think this is the key sentence here. You described a case when computing a centroid makes sense. But there may be a case when a point on the first line is needed (i.e. finding a point on the first line that is closest to the second line). I have no idea who implemented this helper function and in which algorithm he used it. But I think it's logical to assume that this was the intended behavior.

For this reason I'd avoid changing the behavior now. However, we can certainly add centroid computation functionality (either a new function, or a bool flag in existing function). A more accurate docstring can also be helpful.

**Comment by taketwo** [comment] 2018-09-09 23:52
Closing as there are no action items right now. If somebody finds it useful to implement a version that computes centroid, please send a PR or chime in first so we can discuss details.

**Closed by taketwo** 2018-09-09 23:52 UTC
