### ISSUE TITLE
[custom] convertion problem between <pcl::PointWithRange> and <pcl::RangeImage>

### ISSUE THREAD

**Issue by unclesammy** [PointCloudLibrary/pcl#5222] opened 2022-04-10 06:35 UTC
So I am learning rangeImage,and I got this code from the tutorial.Here's part of it.
` boost::shared_ptr<pcl::RangeImage> range_image_ptr(new pcl::RangeImage);
    //const std::shared_ptr<const pcl::PointCloud<pcl::PointWithRange>> rip;

    pcl::RangeImage& rangeImage = *range_image_ptr;

    rangeImage.createFromPointCloud(pointCloud, angularResolution, maxAngleWidth, maxAngleHeight,
        sensorPose, coordinate_frame, noiseLevel, minRange, borderSize);

    std::cout << rangeImage << "\n";
    // --------------------------------------------
    // -----Open 3D viewer and add point cloud-----
    // --------------------------------------------
    pcl::visualization::PCLVisualizer viewer("3D Viewer");
    viewer.setBackgroundColor(1, 1, 1);
    // 添加深度图点云
    pcl::visualization::PointCloudColorHandlerCustom<pcl::PointWithRange> range_image_color_handler(range_image_ptr, 0, 0, 0);
    viewer.addPointCloud(range_image_ptr, range_image_color_handler, "range image");
    viewer.setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 4, "range image");`
My compiler went wrong with.

> cannot convert argument 1 from 'boost::shared_ptr<pcl::RangeImage>' to 'const std::shared_ptr<const pcl::PointCloud<pcl::PointWithRange>> &'

Is that because the latest pcl doesnt support this convertion anymore?and how shall I solve this?

**Comment by mvieth** [comment] 2022-04-10 12:17
@unclesammy From which tutorial did you get the code?

**Comment by unclesammy** [comment] 2022-04-10 12:37
@mvieth I'm now using the tutorial 'How to visualize a range image',and I need to update my issue.I no longer have the problem of convertion since I change my c++ standard to 17 and enable AVX2(But maybe mostly I use the PCL tutorial).
Now my problem is that once I entre the main loop. Then I have an Exception thrown at 0x00007FFFDFC956FD (vtkRenderingContext2D-9.0d.dll).

**Comment by mvieth** [comment] 2022-04-10 12:42
Sounds like that is the same problem as in issue #5159

**Comment by unclesammy** [comment] 2022-04-10 14:50
I solved the convention problem now,just convert it into pcl::rangeimage::ptr would do

**Comment by mvieth** [comment] 2022-04-11 07:56
I would close this issue, since it seems to be a duplicate of issue #5159 (the exception in vtkRenderingContext2D-9.0d.dll).
I still don't know from which tutorial you got the previous code (the code with the conversion problem), but it does not appear to be an official, current PCL tutorial (one from pointclouds.org). As you noticed, the `boost::shared_ptr` is the problem, PCL switched to `std::shared_ptr` in newer versions.

**Closed by mvieth** 2022-04-11 07:56 UTC
Labels: status: triage

**Comment by unclesammy** [comment] 2022-04-11 12:29
@mvieth thanks!
