### ISSUE TITLE
[cmake] Failed to find OSPRay

### ISSUE THREAD

**Issue by fbartelt** [PointCloudLibrary/pcl#5615] opened 2023-02-22 06:52 UTC
Tried to install pcl from AUR through `yay` and got the following cmake Error:
```
at /lib/cmake/ospray-2.10.0/osprayConfig.cmake:26 (message):
  Failed to find OSPRay - OSPRay install root: /, determined from relative
  path from osprayConfg.cmake install location: /lib/cmake/ospray-2.10.0,
  does not contain OSPRay headers.  Either the install directory was deleted,
  or the install tree was only partially relocated outside of CMake after
  OSPRay was built.
``` 

<details>
<summary>Build Log</summary>

```
==> Starting build()...
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /sbin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /sbin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /sbin/pkg-config (found version "1.8.0") 
-- Performing Test LIBATOMIC_NOT_NEEDED
-- Performing Test LIBATOMIC_NOT_NEEDED - Failed
-- Found ClangFormat: /sbin/clang-format (found suitable version "15.0.7", minimum required is "14") 
-- Adding target 'format'
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5") found components: C CXX 
-- Found OpenMP, spec date 201511
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Checking for module 'eigen3'
--   Found eigen3, version 3.4.0
-- Found Eigen: /usr/include/eigen3 (Required is at least version "3.3") 
-- Eigen found (include: /usr/include/eigen3, version: 3.4.0)
-- Found flann version 1.9.2
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.26
-- Found libusb: /usr/lib/libusb-1.0.so  
-- Could NOT find OpenNI (missing: OPENNI_LIBRARIES OPENNI_INCLUDE_DIRS) 
-- OpenNI grabber support: not building because OpenNI not found
-- Could NOT find OpenNI2 (missing: OPENNI2_LIBRARIES OPENNI2_INCLUDE_DIRS) 
-- OpenNI2 grabber support: not building because OpenNI2 not found
-- Could NOT find Ensenso (missing: ENSENSO_LIBRARIES ENSENSO_INCLUDE_DIRS) 
-- IDS-Imaging Ensenso camera support: not building because Ensenso not found
-- Could NOT find davidSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
-- David Vision Systems SDK support: not building because davidSDK not found
-- Could NOT find DSSDK (missing: DSSDK_LIBRARIES DSSDK_INCLUDE_DIRS) 
-- DepthSense SDK support: not building because DSSDK not found
-- Could NOT find RSSDK (missing: RSSDK_LIBRARIES RSSDK_INCLUDE_DIRS) 
-- RealSense SDK support: not building because RSSDK not found
-- Could NOT find RSSDK2
-- RealSense SDK 2.0 (librealsense) support: not building because RSSDK2 not found
-- Checking for module 'metslib'
--   Package 'metslib', required by 'virtual:world', not found
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.13") 
-- Found PNG: /usr/lib/libpng.so (found version "1.6.39") 
-- Found Qhull version 8.0.2
-- Found CUDA Toolkit v11.8
-- The CUDA compiler identification is NVIDIA 11.8.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /opt/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CMAKE_CUDA_ARCHITECTURES: 35;37;50;52;53;60;61;62;70;72;75;80;86;87;89;90
-- Found MPI_C: /lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
CMake Error at /lib/cmake/ospray-2.10.0/osprayConfig.cmake:26 (message):
  Failed to find OSPRay - OSPRay install root: /, determined from relative
  path from osprayConfg.cmake install location: /lib/cmake/ospray-2.10.0,
  does not contain OSPRay headers.  Either the install directory was deleted,
  or the install tree was only partially relocated outside of CMake after
  OSPRay was built.
Call Stack (most recent call first):
  /lib/cmake/ospray-2.10.0/osprayConfig.cmake:69 (ospray_report_not_found)
  /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:256 (find_package)
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:368 (find_package):
  By not providing "FindOpenVR.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenVR", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenVR" with any
  of the following names:

    OpenVRConfig.cmake
    openvr-config.cmake

  Add the installation prefix of "OpenVR" to CMAKE_PREFIX_PATH or set
  "OpenVR_DIR" to a directory containing one of the above files.  If "OpenVR"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: OpenVR
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:415 (find_package):
  By not providing "FindFontConfig.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "FontConfig", but CMake did not find one.

  Could not find a package configuration file provided by "FontConfig" with
  any of the following names:

    FontConfigConfig.cmake
    fontconfig-config.cmake

  Add the installation prefix of "FontConfig" to CMAKE_PREFIX_PATH or set
  "FontConfig_DIR" to a directory containing one of the above files.  If
  "FontConfig" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: FontConfig
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:462 (find_package):
  By not providing "Findmpi4py.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "mpi4py", but
  CMake did not find one.

  Could not find a package configuration file provided by "mpi4py" with any
  of the following names:

    mpi4pyConfig.cmake
    mpi4py-config.cmake

  Add the installation prefix of "mpi4py" to CMAKE_PREFIX_PATH or set
  "mpi4py_DIR" to a directory containing one of the above files.  If "mpi4py"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: mpi4py
-- Found PostgreSQL: /lib/libpq.so (found version "15.1")  
-- Found Boost: /usr/include (found suitable exact version "1.81.0")  
COMPONENT = openvdb
-- Found OpenVDB: /usr/include (found version "10.0.1") found components: openvdb 
-- OpenVDB ABI Version: 10
-- Found Boost: /usr/include (found version "1.81.0") found components: iostreams regex 
-- Found Blosc: /lib/libblosc.so (found version "1.21.3") 
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:697 (find_package):
  By not providing "FindTHEORA.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "THEORA", but
  CMake did not find one.

  Could not find a package configuration file provided by "THEORA" with any
  of the following names:

    THEORAConfig.cmake
    theora-config.cmake

  Add the installation prefix of "THEORA" to CMAKE_PREFIX_PATH or set
  "THEORA_DIR" to a directory containing one of the above files.  If "THEORA"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: THEORA
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:744 (find_package):
  By not providing "FindOGG.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OGG", but
  CMake did not find one.

  Could not find a package configuration file provided by "OGG" with any of
  the following names:

    OGGConfig.cmake
    ogg-config.cmake

  Add the installation prefix of "OGG" to CMAKE_PREFIX_PATH or set "OGG_DIR"
  to a directory containing one of the above files.  If "OGG" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: OGG
-- Found ODBC: /lib/libodbc.so  
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:838 (find_package):
  By not providing "FindMySQL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MySQL", but
  CMake did not find one.

  Could not find a package configuration file provided by "MySQL" with any of
  the following names:

    MySQLConfig.cmake
    mysql-config.cmake

  Add the installation prefix of "MySQL" to CMAKE_PREFIX_PATH or set
  "MySQL_DIR" to a directory containing one of the above files.  If "MySQL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: MySQL
-- Reading /lib/cmake/libLAS/liblas-config.cmake
-- libLAS configuration, version 1.8.2b1
-- Found Boost: /usr/include (found suitable exact version "1.81.0") found components: program_options thread system iostreams filesystem chrono atomic regex 
-- Found LibXml2: /lib/libxml2.so (found version "2.10.3") 
-- Found ADIOS2: /lib/cmake/adios2/adios2-config.cmake (found version "2.8.3") found components: C CXX MPI 
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:1073 (find_package):
  By not providing "FindFFMPEG.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FFMPEG", but
  CMake did not find one.

  Could not find a package configuration file provided by "FFMPEG" (requested
  version 5.1) with any of the following names:

    FFMPEGConfig.cmake
    ffmpeg-config.cmake

  Add the installation prefix of "FFMPEG" to CMAKE_PREFIX_PATH or set
  "FFMPEG_DIR" to a directory containing one of the above files.  If "FFMPEG"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: FFMPEG
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:1120 (find_package):
  By not providing "FindGL2PS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GL2PS", but
  CMake did not find one.

  Could not find a package configuration file provided by "GL2PS" (requested
  version 1.4.2) with any of the following names:

    GL2PSConfig.cmake
    gl2ps-config.cmake

  Add the installation prefix of "GL2PS" to CMAKE_PREFIX_PATH or set
  "GL2PS_DIR" to a directory containing one of the above files.  If "GL2PS"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: GL2PS
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:1167 (find_package):
  By not providing "FindLibHaru.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibHaru", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibHaru"
  (requested version 2.4.0) with any of the following names:

    LibHaruConfig.cmake
    libharu-config.cmake

  Add the installation prefix of "LibHaru" to CMAKE_PREFIX_PATH or set
  "LibHaru_DIR" to a directory containing one of the above files.  If
  "LibHaru" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: LibHaru
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:1214 (find_package):
  By not providing "FindJsonCpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "JsonCpp", but
  CMake did not find one.

  Could not find a package configuration file provided by "JsonCpp"
  (requested version 0.7.0) with any of the following names:

    JsonCppConfig.cmake
    jsoncpp-config.cmake

  Add the installation prefix of "JsonCpp" to CMAKE_PREFIX_PATH or set
  "JsonCpp_DIR" to a directory containing one of the above files.  If
  "JsonCpp" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: JsonCpp
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:1308 (find_package):
  By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NetCDF", but
  CMake did not find one.

  Could not find a package configuration file provided by "NetCDF" with any
  of the following names:

    NetCDFConfig.cmake
    netcdf-config.cmake

  Add the installation prefix of "NetCDF" to CMAKE_PREFIX_PATH or set
  "NetCDF_DIR" to a directory containing one of the above files.  If "NetCDF"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: NetCDF
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:1355 (find_package):
  By not providing "FindCGNS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CGNS", but
  CMake did not find one.

  Could not find a package configuration file provided by "CGNS" (requested
  version 4.1.1) with any of the following names:

    CGNSConfig.cmake
    cgns-config.cmake

  Add the installation prefix of "CGNS" to CMAKE_PREFIX_PATH or set
  "CGNS_DIR" to a directory containing one of the above files.  If "CGNS"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: CGNS
-- Found HDF5: /lib/libhdf5.so;/lib/libsz.so;/lib/libz.so;/lib/libdl.a;/lib/libm.so (found version "1.12.2") found components: C HL 
-- Found ADIOS2: /lib/cmake/adios2/adios2-config.cmake (found suitable version "2.8.3", minimum required is "2.4") found components: C CXX MPI 
-- Found Boost: /usr/include (found suitable exact version "1.81.0")  
-- Found Boost: /usr/include (found suitable exact version "1.81.0") found components: serialization 
-- Found SQLite3: /usr/include (found version "3.40.1") 
-- Found GDAL: /lib/libgdal.so (found version "3.6.2") 
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:1872 (find_package):
  By not providing "FindLibPROJ.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibPROJ", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibPROJ" with any
  of the following names:

    LibPROJConfig.cmake
    libproj-config.cmake

  Add the installation prefix of "LibPROJ" to CMAKE_PREFIX_PATH or set
  "LibPROJ_DIR" to a directory containing one of the above files.  If
  "LibPROJ" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: LibPROJ
-- Found MPI: TRUE (found version "3.1") found components: C 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /lib/libX11.so;/lib/libXext.so
-- Looking for XOpenDisplay in /lib/libX11.so;/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found GLEW: /usr/include (found version "2.2.0") 
-- Found OpenGL: /lib/libOpenGL.so  found components: OpenGL GLX 
-- Found Python3: /bin/python3.10 (found suitable version "3.10.9", minimum required is "3.10") found components: Interpreter Development.Module Development.Embed 
-- Found LibArchive: /lib/libarchive.so (found version "3.6.2") 
-- Found EXPAT: /lib/libexpat.so (found version "2.5.0") 
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:2295 (find_package):
  By not providing "FindLZMA.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LZMA", but
  CMake did not find one.

  Could not find a package configuration file provided by "LZMA" with any of
  the following names:

    LZMAConfig.cmake
    lzma-config.cmake

  Add the installation prefix of "LZMA" to CMAKE_PREFIX_PATH or set
  "LZMA_DIR" to a directory containing one of the above files.  If "LZMA"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: LZMA
CMake Warning at /lib/cmake/vtk/VTK-vtk-module-find-packages.cmake:2342 (find_package):
  By not providing "FindLZ4.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LZ4", but
  CMake did not find one.

  Could not find a package configuration file provided by "LZ4" with any of
  the following names:

    LZ4Config.cmake
    lz4-config.cmake

  Add the installation prefix of "LZ4" to CMAKE_PREFIX_PATH or set "LZ4_DIR"
  to a directory containing one of the above files.  If "LZ4" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /lib/cmake/vtk/vtk-config.cmake:150 (include)
  cmake/pcl_find_vtk.cmake:31 (find_package)
  CMakeLists.txt:388 (include)


-- Could not find the VTK package due to a missing dependency: LZ4
-- Found TIFF: /lib/libtiff.so (found version "4.5.0")  
-- Found JPEG: /lib/libjpeg.so (found version "80") 
-- Found Freetype: /lib/libfreetype.so (found version "2.13.0") 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- VTK version: 9.1.0
-- VTK rendering backend: OpenGL2
-- VTK Qt support: YES
-- VTK libs: VTK::WrappingTools;VTK::WebPython;VTK::WebCore;VTK::WebGLExporter;VTK::ViewsQt;VTK::ViewsInfovis;VTK::Java;VTK::UtilitiesBenchmarks;VTK::ViewsContext2D;VTK::zfp;VTK::loguru;VTK::cli11;VTK::TestingRendering;VTK::TestingIOSQL;VTK::TestingGenericBridge;VTK::TestingCore;VTK::RenderingTk;VTK::RenderingRayTracing;VTK::RenderingVolumeAMR;VTK::RenderingQt;VTK::PythonContext2D;VTK::RenderingParallelLIC;VTK::RenderingParallel;VTK::RenderingOpenVR;VTK::RenderingVR;VTK::RenderingVolumeOpenGL2;VTK::RenderingMatplotlib;VTK::PythonInterpreter;VTK::RenderingLabel;VTK::octree;VTK::RenderingLOD;VTK::RenderingLICOpenGL2;VTK::RenderingImage;VTK::RenderingFreeTypeFontConfig;VTK::RenderingFFMPEGOpenGL2;VTK::RenderingExternal;VTK::RenderingContextOpenGL2;VTK::ParallelMPI4Py;VTK::mpi4py;VTK::IOXdmf2;VTK::xdmf2;VTK::IOVeraOut;VTK::IOVPIC;VTK::vpic;VTK::IOTecplotTable;VTK::IOTRUCHAS;VTK::IOSegY;VTK::IOPostgreSQL;VTK::IOParallelXdmf3;VTK::IOXdmf3;VTK::xdmf3;VTK::IOParallelXML;VTK::IOParallelNetCDF;VTK::IOParallelLSDyna;VTK::IOParallelExodus;VTK::IOPLY;VTK::IOPIO;VTK::IOPDAL;VTK::IOOpenVDB;VTK::IOOggTheora;VTK::theora;VTK::ogg;VTK::IOOMF;VTK::IOODBC;VTK::IONetCDF;VTK::IOMySQL;VTK::IOMotionFX;VTK::pegtl;VTK::IOMPIParallel;VTK::IOParallel;VTK::IOMPIImage;VTK::IOMINC;VTK::IOLSDyna;VTK::IOLAS;VTK::IOInfovis;VTK::libxml2;VTK::IOImport;VTK::IOIOSS;VTK::ioss;VTK::IOHDF;VTK::IOH5part;VTK::h5part;VTK::IOH5Rage;VTK::IOGeoJSON;VTK::IOFides;VTK::fides;VTK::IOFFMPEG;VTK::IOVideo;VTK::IOMovie;VTK::IOExportPDF;VTK::IOExportGL2PS;VTK::RenderingGL2PSOpenGL2;VTK::gl2ps;VTK::IOExport;VTK::libharu;VTK::IOGeometry;VTK::RenderingVtkJS;VTK::jsoncpp;VTK::RenderingSceneGraph;VTK::IOExodus;VTK::exodusII;VTK::netcdf;VTK::IOEnSight;VTK::IOCityGML;VTK::IOChemistry;VTK::IOCONVERGECFD;VTK::IOCGNSReader;VTK::cgns;VTK::IOAsynchronous;VTK::IOAMR;VTK::hdf5;VTK::IOADIOS2;VTK::InteractionImage;VTK::InfovisBoostGraphAlgorithms;VTK::InfovisBoost;VTK::ImagingStencil;VTK::ImagingStatistics;VTK::ImagingOpenGL2;VTK::ImagingMorphological;VTK::ImagingMath;VTK::ImagingFourier;VTK::GUISupportQtSQL;VTK::IOSQL;VTK::sqlite;VTK::GUISupportQtQuick;VTK::GUISupportQt;VTK::GeovisGDAL;VTK::IOGDAL;VTK::GeovisCore;VTK::InfovisLayout;VTK::libproj;VTK::ViewsCore;VTK::InteractionWidgets;VTK::RenderingVolume;VTK::RenderingAnnotation;VTK::ImagingHybrid;VTK::ImagingColor;VTK::InteractionStyle;VTK::FiltersTopology;VTK::FiltersSelection;VTK::FiltersSMP;VTK::FiltersReebGraph;VTK::FiltersPython;VTK::FiltersProgrammable;VTK::FiltersPoints;VTK::FiltersParallelVerdict;VTK::FiltersVerdict;VTK::verdict;VTK::FiltersParallelStatistics;VTK::FiltersParallelImaging;VTK::FiltersParallelGeometry;VTK::FiltersParallelFlowPaths;VTK::FiltersParallelDIY2;VTK::FiltersImaging;VTK::ImagingGeneral;VTK::FiltersHyperTree;VTK::FiltersGeneric;VTK::FiltersFlowPaths;VTK::FiltersAMR;VTK::DomainsParallelChemistry;VTK::FiltersParallelMPI;VTK::FiltersParallel;VTK::FiltersTexture;VTK::FiltersModeling;VTK::FiltersHybrid;VTK::ParallelMPI;VTK::mpi;VTK::DomainsChemistryOpenGL2;VTK::RenderingOpenGL2;VTK::glew;VTK::opengl;VTK::RenderingUI;VTK::DomainsChemistry;VTK::CommonPython;VTK::WrappingPythonCore;VTK::Python;VTK::CommonArchive;VTK::ChartsCore;VTK::InfovisCore;VTK::FiltersExtraction;VTK::ParallelDIY;VTK::IOXML;VTK::IOXMLParser;VTK::expat;VTK::diy2;VTK::ParallelCore;VTK::IOLegacy;VTK::IOCore;VTK::lzma;VTK::lz4;VTK::doubleconversion;VTK::FiltersStatistics;VTK::eigen;VTK::ImagingSources;VTK::IOImage;VTK::tiff;VTK::png;VTK::metaio;VTK::jpeg;VTK::DICOMParser;VTK::RenderingContext2D;VTK::RenderingFreeType;VTK::freetype;VTK::zlib;VTK::RenderingCore;VTK::FiltersSources;VTK::CommonColor;VTK::AcceleratorsVTKmFilters;VTK::ImagingCore;VTK::FiltersGeometry;VTK::FiltersGeneral;VTK::fmt;VTK::CommonComputationalGeometry;VTK::FiltersCore;VTK::CommonExecutionModel;VTK::AcceleratorsVTKmDataModel;VTK::CommonDataModel;VTK::pugixml;VTK::CommonSystem;VTK::CommonMisc;VTK::exprtk;VTK::CommonTransforms;VTK::CommonMath;VTK::kissfft;VTK::AcceleratorsVTKmCore;VTK::vtkm;VTK::CommonCore;VTK::utf8;VTK::vtksys;VTK::kwiml
-- Qt version: 5.15.8
CMake Deprecation Warning at cmake/pcl_find_qt.cmake:61 (cmake_policy):
  The OLD behavior for policy CMP0100 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:396 (include)


-- Found Pcap: /usr/lib/libpcap.so  
-- Found Boost: /usr/include (found suitable version "1.81.0", minimum required is "1.65.0") found components: filesystem date_time iostreams system regex 
-- Found OpenGL: /lib/libOpenGL.so   
-- Found GLEW: /usr/include  
-- DOXYGEN_FOUND 
-- HTML_HELP_COMPILER 
-- PCL build with following flags:
-- -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fopenmp
-- The following subsystems will be built:
--   common
--   kdtree
--   octree
--   search
--   sample_consensus
--   filters
--   2d
--   geometry
--   io
--   features
--   ml
--   segmentation
--   visualization
--   surface
--   registration
--   keypoints
--   tracking
--   recognition
--   stereo
--   outofcore
--   people
--   tools
-- The following subsystems will not be built:
--   apps: Disabled by default
--   benchmarks: Disabled by default
--   examples: Code examples are disabled by default.
--   simulation: Disabled by default.
--   global_tests: Disabled by default
-- Configuring incomplete, errors occurred!
See also "/home/fbartelt/.cache/yay/pcl/src/build/CMakeFiles/CMakeOutput.log".
```

</details>

<details>
<summary>CMake Error Log </summary>

```
Performing C++ SOURCE FILE Test LIBATOMIC_NOT_NEEDED failed with the following output:
Change Dir: /home/fbartelt/.cache/yay/pcl/src/build/CMakeFiles/CMakeScratch/TryCompile-sQMzKC

Run Build Command(s):/sbin/make -f Makefile cmTC_9427f/fast && /sbin/make  -f CMakeFiles/cmTC_9427f.dir/build.make CMakeFiles/cmTC_9427f.dir/build
make[1]: Entering directory '/home/fbartelt/.cache/yay/pcl/src/build/CMakeFiles/CMakeScratch/TryCompile-sQMzKC'
Building CXX object CMakeFiles/cmTC_9427f.dir/src.cxx.o
/sbin/c++ -DLIBATOMIC_NOT_NEEDED  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS  -std=c++14 -o CMakeFiles/cmTC_9427f.dir/src.cxx.o -c /home/fbartelt/.cache/yay/pcl/src/build/CMakeFiles/CMakeScratch/TryCompile-sQMzKC/src.cxx
Linking CXX executable cmTC_9427f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9427f.dir/link.txt --verbose=1
/sbin/c++ -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now  CMakeFiles/cmTC_9427f.dir/src.cxx.o -o cmTC_9427f 
/sbin/ld: CMakeFiles/cmTC_9427f.dir/src.cxx.o: in function `main':
src.cxx:(.text.startup+0x34): undefined reference to `__atomic_load'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_9427f.dir/build.make:99: cmTC_9427f] Error 1
make[1]: Leaving directory '/home/fbartelt/.cache/yay/pcl/src/build/CMakeFiles/CMakeScratch/TryCompile-sQMzKC'
make: *** [Makefile:127: cmTC_9427f/fast] Error 2


Source file was:

#include <atomic>
struct big { int foo[64]; };
std::atomic<big> x;
int main() {
   return x.load().foo[13];
}

```

</details>

**Environment**

 - OS: ArchLinux 6.1.12.arch1-1
 - Compiler: GCC 12.2.1
 - PCL Version 1.13.0

**Comment by larshg** [comment] 2023-02-22 09:15
This is a sub dependency to VTK, but I doubt you will get much more help from here, since we don't really maintain all others package/install methods.
You are probably better off with StackOverflow or some local forum of AUR/yay?
If subdependencies are not automatically intalled, you can try (re)install them - it seems to properly find OSPRays headers.

Closing as its not a bug in PCL per se, but feel free to continue discussion.

**Closed by larshg** 2023-02-22 09:15 UTC
Labels: kind: bug, status: triage

**Comment by fbartelt** [comment] 2023-02-22 17:29
Thanks for pointing this out, it helped me find the solution. In case someone has the same error and sees this issue, a workaround (ospray/ospray#511) is to create a symlink at `/include` to point to `/usr/include`
