### ISSUE TITLE
Strange color behavior when saving .PCD file and loading it again. from [PCL-users]

### ISSUE THREAD

**Issue by r9y9** [PointCloudLibrary/pcl#1543] opened 2016-02-19 04:46 UTC
ref: http://www.pcl-users.org/Strange-color-behavior-when-saving-PCD-file-and-loading-it-again-td4040975.html

I was able to reproduce this with my PCD file (captured by Kinect v2) locally, so I filed this issue here.

A sample code and pcd file can be found at https://github.com/r9y9/pcdio_test.

Orignal point cloud captured by kinect v2:

<img width="752" alt="2016-02-19 13 28 03" src="https://cloud.githubusercontent.com/assets/1220272/13166688/d26d0116-d70d-11e5-9fcc-9b4732d7eae2.png">

Saving and loading it again then:

<img width="752" alt="2016-02-19 13 28 57" src="https://cloud.githubusercontent.com/assets/1220272/13166690/d89dcdae-d70d-11e5-8778-a1786a796e6c.png">

This strange behavior only happens when saving PCD file as ASCII (no problem in binary mode). I'm testing with PCL trunk on osx 10.10.4.

**Comment by VictorLamoine** [comment] 2016-02-19 08:20
Thanks for the complete test code!
I can reproduce this issue on Ubuntu 14.04 with PCL trunk and PCL 1.7.2.

Your input PCD file doesn't seem to be corrupted, I used `pcl_converter` to convert it to a PLY file and it is fine.

**Comment by UnaNancyOwen** [comment] 2016-02-19 15:29
I'll report test results.
I can reproduce this issue as well on Windows (vc14) with PCL 1.8.0rc1.

**Comment by SergioRAgostinho** [comment] 2016-02-20 10:12
I was able to reproduce it as well. I'm looking into this now.

**Comment by SergioRAgostinho** [comment] 2016-02-20 13:23
The issue is related to our float representation of color. As you know, color is stored in 32bits, sometimes as float with the member name ' rgb' sometimes as a unit32_t with member name 'rgba' . The color information is packed as 
```
uint8_t alpha | uint8_t red | uint8_t green | uint8_t blue
```
Now according to the [IEEE 754 NaN definition](https://en.wikipedia.org/wiki/NaN), if your first 9 bits are set to 1s, then the value is parsed as a NaN. 

When we use the type PointXYZRGB and we [get the fields](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/impl/pcd_io.hpp#L492) for the pointcloud, it's inferring we have an rgb field of float type. When we then later do the [pcl::is_nan check](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/io/impl/pcd_io.hpp#L581), everything in this format
```
s111 1111 1xxx xxxx xxxx xxxx xxxx xxxx
```
 get's interpreted as nan. 

I gotta admit, fixing this one requires some Boost MPL kung fu skill, I'm not really sure I have at the moment :smile:, but let's see...

**Comment by VictorLamoine** [comment] 2016-02-20 14:52
What about https://github.com/PointCloudLibrary/pcl/pull/1385 ?

**Comment by SergioRAgostinho** [comment] 2016-02-20 14:59
> What about #1385 ?

It will solve the issue. 

I really feel we should simply register all point types with uint32_t rgba, and I tried it, but it opened even bigger problems :smile:

**Comment by taketwo** [comment] 2016-08-18 13:20
Should be fixed by #1385, reopen if it is not.

**Closed by taketwo** 2016-08-18 13:20 UTC
Labels: bug

**Comment by dhiegomaga** [comment] 2018-05-24 17:09
I had this same issue today. So it's not solved? Any workaround?

**Comment by dhiegomaga** [comment] 2018-05-24 21:14
I'm actually using [pcl_ros](http://wiki.ros.org/pcl_ros#pointcloud_to_pcd)... I guess it is 1.7, but I'm not sure. I needed to save the pointcloud from a topic. I guess it might easier to convert to XYZGRBA ?
