### ISSUE TITLE
Very long link time optimization PCL 1.8, VTK >= 6, Ubuntu 16.04

### ISSUE THREAD

**Issue by JuliusKu** [PointCloudLibrary/pcl#1854] opened 2017-04-11 14:20 UTC
Ubuntu 16.04
gcc 5.4.0
PCL 1.8 build with VTK 5.10, 6.3 and 7.0

When building a project linking to vtk 6 or 7 the build takes very long (I forced stopping after 30min).
More precisely, the process takes ages for the link time optimization. 
I'm not running into this problem when using PCL build with VTK 5.

I was able to reproduce this behavior on multiple systems. Furthermore, some colleagues have the same problem.

**Comment by wsascha** [comment] 2017-05-12 12:39
Having the same issues here. Any idea what could solve these problems? - I am willing to help :)

**Comment by jolesinski** [comment] 2017-05-13 08:55
Heve you tried using gold? It has speeded up link time a lot in my case, maybe it will help you. You can set it in cmake with:
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fuse-ld=gold")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fuse-ld=gold")

**Comment by KaushikSamba** [comment] 2019-11-23 01:09
Can you confirm this is still an issue?

**Comment by SergioRAgostinho** [comment] 2019-11-23 14:18
@taketwo complained about something similar a while ago and in the meantime we (slightly)  optimized our linking stage against VTK. TL;DR: Give it a try to the master branch and see if it is still a problem.

**Comment by kunaltyagi** [comment] 2020-05-19 10:20
Do you still have the long link time issues?

**Comment by wsascha** [comment] 2020-05-19 11:11
I'm sorry, my Ubuntu and compiler version has changed so I cannot reproduce this anymore.

**Comment by kunaltyagi** [comment] 2020-05-19 11:19
I don't see a significantly different CI run time across 16.04 and 20.04. Only a difference of 2.5 minutes (which could be significant, but nowhere close to 30 minutes if the issue was still present)

Total build times:
* 16.04: 75 minutes, 40 seconds
* 20.04: 73 minutes, 13 seconds

Closing because no evidence of issue still persisting. If found, please reopen/open a new ticket.

**Closed by kunaltyagi** 2020-05-19 11:19 UTC
Labels: kind: bug, module: cmake, module: visualization, needs: author reply

**Comment by pbeeson** [comment] 2020-10-12 20:28
I have seen this on 18.04 with Pcl-1.8 binaries.  Not EVERY library/executable, but occasionally one, for unknown reasons, takes 1.5 minutes to link.  If I switch to clang from gcc, it takes ~5 seconds.  So, maybe try clang if you end up here.
