### ISSUE TITLE
NormalEstimationOMP generates invalid normals

### ISSUE THREAD

**Issue by DavidRobb** [PointCloudLibrary/pcl#3226] opened 2019-07-15 12:42 UTC
Your Environment

Windows 10 
MS toolchain
PCL 1.9.1-4 from vcpkg x64-windows install

Would like to use the normalEstimationOMP as this is meant to be a drop in replacement for single threaded normalEstimation but the OMP version generates invalid normals for my data:

normalEstimation results:
![image](https://user-images.githubusercontent.com/11753801/61216673-e169e780-a705-11e9-9801-1fb219e999fa.png)

normalEstimationOMP results

![image](https://user-images.githubusercontent.com/11753801/61216723-0199a680-a706-11e9-85bc-fe4e0e1c546e.png)

Code to reproduce:
#include <iostream>
#include <pcl/features/normal_3d_omp.h>
#include <pcl/io/ply_io.h>
#include <pcl/point_types.h>

int main(int argc, char **argv) {

    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);

    // Fill in the cloud data
    pcl::PLYReader reader;
    //   // Replace the path below with the path where you saved your file
    reader.read("C:\\Users\\David\\Desktop\\frame15-Jul_09-29-16.ply", *cloud); // Remember to download the file first!

    std::cerr << "PointCloud " << cloud->width * cloud->height << " data points (" << pcl::getFieldsList(*cloud) << ").\n";

    pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
    tree->setInputCloud(cloud);
    pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> normalEstimator;
    normalEstimator.setInputCloud(cloud);
    normalEstimator.setSearchMethod(tree);
    normalEstimator.setRadiusSearch(30.0f);
    normalEstimator.setViewPoint(-700.0f, 140.0, 1100);
    pcl::PointCloud<pcl::Normal>::Ptr cloud_normals(new pcl::PointCloud<pcl::Normal>);
    normalEstimator.compute(*cloud_normals);

    int i = 0;
    for (pcl::Normal n : *cloud_normals) {
        std::cerr << i << "n = " << n.normal_x << ", " << n.normal_y << ", " << n.normal_z << "\n";
        i++;
    }

    return (0);
}

PLY data file:
[frame15-Jul_09-29-16.zip](https://github.com/PointCloudLibrary/pcl/files/3392300/frame15-Jul_09-29-16.zip)

**Comment by SergioRAgostinho** [comment] 2019-07-15 21:13
This is likely a duplicate of #2403 and we have a PR addressing it in #3169. I would suggest to give it a try and report if the problem gets fixed.

**Comment by taketwo** [comment] 2019-07-16 08:26
Right, we are moving towards merging OMP versions into the standard versions, but are not quite there yet.

I suppose the difference in results may come from us merging some bugfix for the standard version and not doing the same for the OMP version. I therefore suggest to have a look at the history of the two files and see if you can spot "unmatched" commits.

**Comment by DavidRobb** [comment] 2019-07-16 08:33
@
Yes. I looked at #2403 but thought it was different because I'm very happy with the standard normalEstimation results but not so with the OMP version. Without looking at the code, thought it might an issue with thread contention or each task not seeing the whole point cloud. However, as suggested could be a problem with code diverging.
Thanks for investigating

**Comment by dogod621** [comment] 2019-07-25 01:31
Hi, 

@SergioRAgostinho
Is covariance_matrix_ and xyz_centroid_ thread safe?
NormalEstimation reuse these two variables (kind of like global variables) in each computePointNormal

```C++
/** \brief Placeholder for the 3x3 covariance matrix at each surface patch. */
      EIGEN_ALIGN16 Eigen::Matrix3f covariance_matrix_;

      /** \brief 16-bytes aligned placeholder for the XYZ centroid of a surface patch. */
      Eigen::Vector4f xyz_centroid_;
```

```C++
inline bool
      computePointNormal (const pcl::PointCloud<PointInT> &cloud, const std::vector<int> &indices,
                          float &nx, float &ny, float &nz, float &curvature)
      {
        if (indices.size () < 3 ||
            computeMeanAndCovarianceMatrix (cloud, indices, covariance_matrix_, xyz_centroid_) == 0)
        {
          nx = ny = nz = curvature = std::numeric_limits<float>::quiet_NaN ();
          return false;
        }

        // Get the plane normal and surface curvature
        solvePlaneParameters (covariance_matrix_, nx, ny, nz, curvature);
        return true;
      }
```

If it isn't thread safe... why not just declare covariance_matrix_ and xyz_centroid_ inside computePointNormal, they are not use in other place anyway... ?

**Comment by taketwo** [comment] 2019-08-05 18:56
Note that OMP version uses free function `pcl::computePointNormal`, not the member method: https://github.com/PointCloudLibrary/pcl/blob/a2bedc96e0b7d1a19a6e92ca9292afe009251ae5/features/include/pcl/features/impl/normal_3d_omp.hpp#L81

The free function declares covariance matrix and centroid inside just like you suggested. So this can not be a problem.

**Comment by unageek** [comment] 2022-07-20 10:32
Is this still the case?

**Comment by unageek** [comment] 2022-07-22 07:39
I confirmed that the normals generated by `NormalEstimation` and `NormalEstimationOMP` are exactly the same.

**Comment by DavidRobb** [comment] 2022-07-22 08:17
Great. That is good to know. Happy for this issue to be closed.

**Comment by mvieth** [comment] 2022-07-22 08:31
I also just checked and also can't find any difference between the outputs of `NormalEstimation` and `NormalEstimationOMP`. So I'm closing this. Thanks everyone!

**Closed by mvieth** 2022-07-22 08:31 UTC
Labels: needs: code review
