### ISSUE TITLE
Eigen 3.3 alignment error due to incorrect use of stl structures when using AVX/vectorization

### ISSUE THREAD

**Issue by phleba** [PointCloudLibrary/pcl#1791] opened 2017-01-09 10:13 UTC
initial remark: This is a continuation and clarification of the problems presented in issue #1684. 

Eigen 3.3 introduces support for vectorization (I tested it only with AVX). See here: 
http://eigen.tuxfamily.org/index.php?title=3.3#Vectorization

PCL by default compiles with the compiler flag --march=native (thus, on my machine, enabling avx support) and if you stick to this default value, this problem occurs as soon as you work with PCL's point clouds. The reason seems to lay in the incorrect use of stl containers (like std::vector or std::map) in combination with Eigen datatypes within PCL. My understanding is that Eigen w. avx optimization expects the data to be layed out in 16-byte-alignment. Since stl containers do not seem guarantee that, you would have to use Eigens alligned allocators as described here. 

https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html 

Otherwise data access will eventually fail and you run into a segmentation fault. I suspect this is not done in the pcl library and would be happy if someone could follow that up.

## Your Environment
* Operating System and version: Ubuntu 16.04 w. kernel 4.8.1
* Compiler: gcc 5.4.0
* PCL Version: 1.8.0
* Eigen Version: > 3.3

## Code to Reproduce
See e.g. here:
https://github.com/PointCloudLibrary/pcl/issues/1684

This problem occured not only with programs using the pcl library but also with other programs unrelated to pcl utilizing Eigen structures within stl containers. Here, we worked on seemingly unrelated problems with our code and finally realized that everything was related through avx optimization and Eigen > 3.3.

Here is a follow up discussion on the bug tracking platform of the eigen ppl: 
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1146

Feel free to ask for clarifications or more details, I try to provide as much information as possible.

**Comment by taketwo** [comment] 2017-01-09 12:08
PCL does use Eigen allocators in std::vectors with points, both [inside PointCloud class](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/point_cloud.h#L410), and everywhere else, as appropriate, so this can not be the reason.

**Comment by PeterSchuebel** [comment] 2017-07-04 17:14
If I understand correctly, these Eigen-allocators are meant to be used in all std::vectors that contain Eigen objects.
A regex search in VisualStudio for `std::vector[^\S\r\n]*<[^\S\r\n]*Eigen::(Vector|Matrix)[0-4][f|d|i|u][^\S\r\n]*>` found the following instances where that is not the case:

```
.\pcl\recognition\include\pcl\recognition\face_detection\rf_face_utils.h(394):            std::vector < Eigen::Matrix3d > offset_covariances;
.\pcl\recognition\include\pcl\recognition\face_detection\rf_face_utils.h(395):            std::vector < Eigen::Matrix3d > angle_covariances;
.\pcl\recognition\include\pcl\recognition\face_detection\rf_face_utils.h(397):            std::vector < Eigen::Vector3d > offset_centroids;
.\pcl\recognition\include\pcl\recognition\face_detection\rf_face_utils.h(398):            std::vector < Eigen::Vector3d > angle_centroids;
.\pcl\recognition\src\face_detection\rf_face_detector_trainer.cpp(85):  std::vector < Eigen::Vector3f > clusters_mean;
.\pcl\registration\include\pcl\registration\gicp.h(297):      std::vector<Eigen::Matrix3d> mahalanobis_;
```

Do these need fixing then? E.g. in gicp.h, line 297 would change to `MatricesVector mahalanobis_;`.

**Comment by jspricke** [comment] 2017-07-04 17:45
* Peter Schübel <notifications@github.com> [2017-07-04 10:14]:
> Do these need fixing then? E.g. in gicp.h, line 297 would change to `MatricesVector mahalanobis_;`.

Yes, a pull request would be great :). Thanks for finding them!

**Comment by SergioRAgostinho** [comment] 2017-07-04 17:52
Please note that we do include <Eigen/StdVector> in pcl_base.h

https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html

**Comment by SergioRAgostinho** [comment] 2017-07-04 17:53
Ignore what I said.

**Comment by SergioRAgostinho** [comment] 2017-07-04 18:03
So, from what I could tell, you have issues with if you create containers for fixed-size vectorizable types, which have multiples of 16 bytes, with the default allocator. The types your string search returned do not meet this criteria.

https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html

**Comment by SergioRAgostinho** [comment] 2017-07-04 18:10
> PCL by default compiles with the compiler flag --march=native (thus, on my machine, enabling avx support) and if you stick to this default value, this problem occurs as soon as you work with PCL's point clouds.

Can you try this with the latest repo by the way? I ask this because we recently started exporting our SSE_FLAGS flags (-march=native is in there as well) to targets which link against a PCL.

**Comment by taketwo** [comment] 2018-09-08 23:27
I believe this issue was caused by PCL not exporting `SSE_FLAGS` (see [my comment](https://github.com/PointCloudLibrary/pcl/issues/1684#issuecomment-419679147) in #1684 with explanations).

Feel free to re-open if you still experience this issue with the latest PCL master (after #2100 was merged).

**Closed by taketwo** 2018-09-08 23:27 UTC
