### ISSUE TITLE
[visualization] PointPickingEvent.getPoint(x, y, z) not working properly

### ISSUE THREAD

**Issue by kaesesahnetorte** [PointCloudLibrary/pcl#5308] opened 2022-06-28 08:44 UTC
I am playing with the PointPicking functionality of the `pcl::Visualizer`.
I have found that the function `PointPickingEvent.getPoint(x, y, z)` does not seem to work properly for me:
Instead of providing the coordinates of the point I clicked it provides coordinates of some other point within the point cloud.
I am having multiple (2 to be exact) point clouds loaded in the visualizer.

Here is a very minimal code example. Am I doing something wrong?
[bug_pointpickingevent.zip](https://github.com/PointCloudLibrary/pcl/files/8999235/bug_pointpickingevent.zip)

**Comment by kaesesahnetorte** [comment] 2022-06-28 08:47
Rather, the function works unreliably, upon trying to select all the points in the point cloud (marking them red by clicking them), I find a point ~ 1/10 times, that will give this weird error.

**Comment by larshg** [comment] 2022-06-29 06:13
Closing as duplicate of #3954 @kaesesahnetorte please see that ticket and suggestions how to circumvent the problem. However its a bit extensive work.

**Closed by larshg** 2022-06-29 06:13 UTC
