### ISSUE TITLE
error LNK2001 about pcl_visualizer and vtkRenderWindowInteractorFixNew(void)?

### ISSUE THREAD

**Issue by 155cannon** [PointCloudLibrary/pcl#5013] opened 2021-11-04 09:18 UTC
I install the "PCL-1.12.0-AllInOne-msvc2019-win64.exe" and download the "pcl-1.12.0-rc1-pdb-msvc2019-win64.zip". Then unzip the pcl-1.12.0-rc1-pdb-msvc2019-win64.zip and put the pdb files in C:\Program Files\PCL 1.12.0\bin. Then I configurate the visual studio 2019(VC++ include, lib path and linker->input->Additional dependencies ).  It's OK in running the PCL programs.

And I need a new "addCylinder" function to draw a cylinder use the pcl::visualization::PCLVisualizer because the original addCylinder function is too simple and crude.  For example, the original addCylinder function can't be passed cylinder length or other parameters into.

So I download the pcl-pcl-1.12.0.zip and get the source code. I modify pcl_visualizer.cpp and pcl_visualizer.h then I copy both of them to my project path and add them to Visual Studio project configuration. I replace  #include <pcl/visualization/pcl_visualizer.h> with #include "pcl_visualizer.h" in pcl_visualizer.cpp and my own main.cpp. 

Compile and Build....  Error occurs!

pcl_visualizer.obj : error LNK2001: 无法解析的外部符号 "class vtkRenderWindowInteractor * __cdecl vtkRenderWindowInteractorFixNew(void)" (?vtkRenderWindowInteractorFixNew@@YAPEAVvtkRenderWindowInteractor@@XZ)

Compile is good but link is wrong!
How to solve the problem? I had searched for all kinds of methods to solve the problem but none of methods are effectual.
Thanks, everyone!

**Comment by larshg** [comment] 2021-11-04 11:41
You cannot just handpick two files from the visualization library like that. You need to recompile PCL to properly include the new changes to the .lib and .dll files.
You could also add a PR to PCL to share this new version of addCylinder :smile:

**Comment by larshg** [comment] 2021-11-04 11:41
Closing as not a bug in PCL, but please feel free to comment.

**Closed by larshg** 2021-11-04 11:41 UTC
Labels: kind: compile error, status: triage

**Comment by 155cannon** [comment] 2021-11-05 00:27
Thank you! @larshg

**Comment by 155cannon** [comment] 2021-11-05 01:43
The "PCL-1.12.0-AllInOne-msvc2019-win64.exe" installer already contains prebuilt PCL binaries which are ready to be used without any compilation step. I had installed the "PCL-1.12.0-AllInOne-msvc2019-win64.exe". How to  "recompile PCL to properly include the new changes to the .lib and .dll files"  simplely? Just generate pcl_visualization.dll and pcl_visualization.lib?

**Comment by 6092002418** [comment] 2024-01-23 10:56
Adding a PCL_EXPORTS works.

**Comment by JamesYasR** [comment] 2025-02-13 17:33
> Adding a PCL_EXPORTS works.

can you explain in details？please！
