### ISSUE TITLE
GPU support for region growing.

### ISSUE THREAD

**Issue by metallo25** [PointCloudLibrary/pcl#1355] opened 2015-10-05 15:58 UTC
Hello,
Is there GPU support for region growing segmentation in pcl::gpu?. Please let me know, thank you.

**Comment by jspricke** [comment] 2015-10-07 11:11
Please use our mailing list for such questsions: http://www.pcl-users.org/.

Closing as it's not a bug.

**Closed by jspricke** 2015-10-07 11:11 UTC
