### ISSUE TITLE
[compile error] "Build pcl v1.12.1 on windows with cuda11.0 got compile error"

### ISSUE THREAD

**Issue by SakuragiJump** [PointCloudLibrary/pcl#5583] opened 2023-01-17 09:30 UTC
When I build compile v1.12.1 on windows with cuda11.0, I got a lot of compile error message like below:
![image](https://user-images.githubusercontent.com/20235878/212858334-73510a25-ce04-4316-af44-794791907033.png)
It seems to be the use of if constexpr feature used in c++14 rather than c++17, have you guys tested the build process on windows platform?

Reproduce steps:
1. download the resource zip file and unzip it;
2. download the all in one installer and install it to get the 3rdparty libs and includes;
3. build from resouces:
```bash
cd /path/to/pcl
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=D:\codeplay\robot_sdk_dep\pcl_1.12.1 -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH;D:\PCL 1.12.1\3rdParty\Boost;D:\PCL 1.12.1\3rdParty\Eigen;D:\PCL 1.12.1\3rdParty\FLANN;D:\PCL 1.12.1\3rdParty\Qhull;D:\PCL 1.12.1\3rdParty\VTK;D:\openni2;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0" -DWITH_CUDA=true -DBUILD_GPU=true -DBUILD_visualization=true -DBUILD_2d=true -DCUDA_ARCH_BIN="75" -T v142 -G "Visual Studio 16 2019"
cmake --build . --target pcl_gpu_containers --config Release
```
4. then compile error like above.

**Your Environment (please complete the following information):**

 - OS: Win10
 - Compiler: msvc 14.29.30133, compiler version 19.29
 - PCL Version 1.12.1
 - PCL Type: Compiled from source

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? CUDA11.0

**Comment by mvieth** [comment] 2023-01-18 09:39
> have you guys tested the build process on windows platform?

Our CI regularly builds the gpu and cuda modules on Ubuntu (but not on Windows). Because it succeeds on Ubuntu, the problem is most likely not in PCL but caused by Windows/MSVC.

> It seems to be the use of if constexpr feature used in c++14 rather than c++17

What do you mean? I don't see anything related to `if constexpr` in the image you posted.

I searched for the error message and found https://github.com/actions/runner-images/issues/3485 and https://stackoverflow.com/questions/67732065
So it seems like the versions of MSVC and CUDA you are using are not compatible.

**Comment by mvieth** [comment] 2023-01-23 19:48
Closing due to the above reasons

**Closed by mvieth** 2023-01-23 19:48 UTC
Labels: kind: compile error, status: triage
