### ISSUE TITLE
LNK2019 error while doing build with Release option.

### ISSUE THREAD

**Issue by atuinn** [PointCloudLibrary/pcl#4357] opened 2020-08-26 13:53 UTC
Hi,
I got the following error while trying to generate exe for code from one of the examples with command : cmake --build . --config Release:
```
C:\Projects\nastawiacz\build>cmake --build . --config Release
Microsoft (R) Build Engine 16.7.0+b89cb5fde dla platformy .NET Framework
Copyright (C) Microsoft Corporation. Wszelkie prawa zastrzeżone.

  Checking Build System
  Building Custom Rule C:/Projects/nastawiacz/CMakeLists.txt
  pcd_write.cpp
C:\dev\vcpkg\vcpkg\installed\x64-windows\include\pcl/io/low_level_io.h(73,16): warning C4996: '_open': This function or
 variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See onli
ne help for details. [C:\Projects\nastawiacz\build\pcd_write.vcxproj]
C:\dev\vcpkg\vcpkg\installed\x64-windows\include\pcl/io/low_level_io.h(78,16): warning C4996: '_open': This function or
 variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See onli
ne help for details. [C:\Projects\nastawiacz\build\pcd_write.vcxproj]
pcd_write.obj : error LNK2019: nierozpoznany symbol zewnętrzny "public: void __cdecl pcl::EuclideanClusterExtraction<st
ruct pcl::PointNormal>::extract(class std::vector<struct pcl::PointIndices,class std::allocator<struct pcl::PointIndice
s> > &)" (?extract@?$EuclideanClusterExtraction@UPointNormal@pcl@@@pcl@@QEAAXAEAV?$vector@UPointIndices@pcl@@V?$allocat
or@UPointIndices@pcl@@@std@@@std@@@Z) przywołany w funkcji main [C:\Projects\nastawiacz\build\pcd_write.vcxproj]
C:\Projects\nastawiacz\build\Release\pcd_write.exe : fatal error LNK1120: liczba nierozpoznanych elementów zewnętrznych
: 1 [C:\Projects\nastawiacz\build\pcd_write.vcxproj]
```
Same error apeared in Visual Studio.
Here is the example code:
```
#include <string>

#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/search/organized.h>
#include <pcl/search/kdtree.h>
#include <pcl/features/normal_3d_omp.h>
#include <pcl/filters/conditional_removal.h>
#include <pcl/segmentation/extract_clusters.h>

#include <pcl/features/don.h>

using namespace pcl;

int
main(int argc, char* argv[])
{
    ///The smallest scale to use in the DoN filter.
    double scale1;

    ///The largest scale to use in the DoN filter.
    double scale2;

    ///The minimum DoN magnitude to threshold by
    double threshold;

    ///segment scene into clusters with given distance tolerance using euclidean clustering
    double segradius;

    if (argc < 6)
    {
        std::cerr << "usage: " << argv[0] << " inputfile smallscale largescale threshold segradius" << std::endl;
        exit(EXIT_FAILURE);
    }

    /// the file to read from.
    std::string infile = argv[1];
    /// small scale
    std::istringstream(argv[2]) >> scale1;
    /// large scale
    std::istringstream(argv[3]) >> scale2;
    std::istringstream(argv[4]) >> threshold;   // threshold for DoN magnitude
    std::istringstream(argv[5]) >> segradius;   // threshold for radius segmentation

    // Load cloud in blob format
    pcl::PCLPointCloud2 blob;
    pcl::io::loadPCDFile(infile.c_str(), blob);
    pcl::PointCloud<PointXYZRGB>::Ptr cloud(new pcl::PointCloud<PointXYZRGB>);
    pcl::fromPCLPointCloud2(blob, *cloud);

    // Create a search tree, use KDTreee for non-organized data.
    pcl::search::Search<PointXYZRGB>::Ptr tree;
    if (cloud->isOrganized())
    {
        tree.reset(new pcl::search::OrganizedNeighbor<PointXYZRGB>());
    }
    else
    {
        tree.reset(new pcl::search::KdTree<PointXYZRGB>(false));
    }

    // Set the input pointcloud for the search tree
    tree->setInputCloud(cloud);

    if (scale1 >= scale2)
    {
        std::cerr << "Error: Large scale must be > small scale!" << std::endl;
        exit(EXIT_FAILURE);
    }

    // Compute normals using both small and large scales at each point
    pcl::NormalEstimationOMP<PointXYZRGB, PointNormal> ne;
    ne.setInputCloud(cloud);
    ne.setSearchMethod(tree);

    /**
     * NOTE: setting viewpoint is very important, so that we can ensure
     * normals are all pointed in the same direction!
     */
    ne.setViewPoint(std::numeric_limits<float>::max(), std::numeric_limits<float>::max(), std::numeric_limits<float>::max());

    // calculate normals with the small scale
    std::cout << "Calculating normals for scale..." << scale1 << std::endl;
    pcl::PointCloud<PointNormal>::Ptr normals_small_scale(new pcl::PointCloud<PointNormal>);

    ne.setRadiusSearch(scale1);
    ne.compute(*normals_small_scale);

    // calculate normals with the large scale
    std::cout << "Calculating normals for scale..." << scale2 << std::endl;
    pcl::PointCloud<PointNormal>::Ptr normals_large_scale(new pcl::PointCloud<PointNormal>);

    ne.setRadiusSearch(scale2);
    ne.compute(*normals_large_scale);

    // Create output cloud for DoN results
    PointCloud<PointNormal>::Ptr doncloud(new pcl::PointCloud<PointNormal>);
    copyPointCloud(*cloud, *doncloud);

    std::cout << "Calculating DoN... " << std::endl;
    // Create DoN operator
    pcl::DifferenceOfNormalsEstimation<PointXYZRGB, PointNormal, PointNormal> don;
    don.setInputCloud(cloud);
    don.setNormalScaleLarge(normals_large_scale);
    don.setNormalScaleSmall(normals_small_scale);

    if (!don.initCompute())
    {
        std::cerr << "Error: Could not initialize DoN feature operator" << std::endl;
        exit(EXIT_FAILURE);
    }

    // Compute DoN
    don.computeFeature(*doncloud);

    // Save DoN features
    pcl::PCDWriter writer;
    writer.write<pcl::PointNormal>("don.pcd", *doncloud, false);

    // Filter by magnitude
    std::cout << "Filtering out DoN mag <= " << threshold << "..." << std::endl;

    // Build the condition for filtering
    pcl::ConditionOr<PointNormal>::Ptr range_cond(
        new pcl::ConditionOr<PointNormal>()
    );
    range_cond->addComparison(pcl::FieldComparison<PointNormal>::ConstPtr(
        new pcl::FieldComparison<PointNormal>("curvature", pcl::ComparisonOps::GT, threshold))
    );
    // Build the filter
    pcl::ConditionalRemoval<PointNormal> condrem;
    condrem.setCondition(range_cond);
    condrem.setInputCloud(doncloud);

    pcl::PointCloud<PointNormal>::Ptr doncloud_filtered(new pcl::PointCloud<PointNormal>);

    // Apply filter
    condrem.filter(*doncloud_filtered);

    doncloud = doncloud_filtered;

    // Save filtered output
    std::cout << "Filtered Pointcloud: " << doncloud->size() << " data points." << std::endl;

    writer.write<pcl::PointNormal>("don_filtered.pcd", *doncloud, false);

    // Filter by magnitude
    std::cout << "Clustering using EuclideanClusterExtraction with tolerance <= " << segradius << "..." << std::endl;

    pcl::search::KdTree<PointNormal>::Ptr segtree(new pcl::search::KdTree<PointNormal>);
    segtree->setInputCloud(doncloud);

    std::vector<pcl::PointIndices> cluster_indices;
    pcl::EuclideanClusterExtraction<PointNormal> ec;

    ec.setClusterTolerance(segradius);
    ec.setMinClusterSize(50);
    ec.setMaxClusterSize(100000);
    ec.setSearchMethod(segtree);
    ec.setInputCloud(doncloud);
    ec.extract(cluster_indices);

    int j = 0;
    for (std::vector<pcl::PointIndices>::const_iterator it = cluster_indices.begin(); it != cluster_indices.end(); ++it, j++)
    {
        pcl::PointCloud<PointNormal>::Ptr cloud_cluster_don(new pcl::PointCloud<PointNormal>);
        for (std::vector<int>::const_iterator pit = it->indices.begin(); pit != it->indices.end(); ++pit)
        {
            cloud_cluster_don->points.push_back((*doncloud)[*pit]);
        }

        cloud_cluster_don->width = cloud_cluster_don->size();
        cloud_cluster_don->height = 1;
        cloud_cluster_don->is_dense = true;

        //Save cluster
        std::cout << "PointCloud representing the Cluster: " << cloud_cluster_don->size() << " data points." << std::endl;
        std::stringstream ss;
        ss << "don_cluster_" << j << ".pcd";
        writer.write<pcl::PointNormal>(ss.str(), *cloud_cluster_don, false);
    }
}
```
With example below everything works fine:

```
#include <iostream>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>

int
  main (int argc, char** argv)
{
  pcl::PointCloud<pcl::PointXYZ> cloud;

  // Fill in the cloud data
  cloud.width    = 5;
  cloud.height   = 1;
  cloud.is_dense = false;
  cloud.points.resize (cloud.width * cloud.height);

  for (auto& point: cloud)
  {
    point.x = 1024 * rand () / (RAND_MAX + 1.0f);
    point.y = 1024 * rand () / (RAND_MAX + 1.0f);
    point.z = 1024 * rand () / (RAND_MAX + 1.0f);
  }

  pcl::io::savePCDFileASCII ("test_pcd.pcd", cloud);
  std::cerr << "Saved " << cloud.size () << " data points to test_pcd.pcd." << std::endl;

  for (const auto& point: cloud)
    std::cerr << "    " << point.x << " " << point.y << " " << point.z << std::endl;

  return (0);
}
```
Any ideas how to solve this issue?

 - OS: [Windows 10]
 - Compiler: [Visual Studio 16 2019]
 - PCL Version [1.11.0 x64 and x32]
 - PCL Type: [Installed with vcpkg]

**Comment by kunaltyagi** [comment] 2020-08-26 18:03
Please edit the title to contain a brief summary

**Comment by larshg** [comment] 2020-08-26 18:56
Please write the libs you are linking against.

**Comment by atuinn** [comment] 2020-08-26 19:11
I can't check until tomorrow but I didn't add anything in linking options, so linking is only against thinks automatically added by visual studio. Before building vcpkg integrate install was done.

**Comment by larshg** [comment] 2020-08-26 20:02
And did you add the cmake file that vcpkg generated, can't remember exactly but goes into the tool chain file.

If you used cmake to generate a solution.

With vcpkg ingrate install all libs and include dirt are added to new projects?
Haven't really tried that part myself.

**Comment by atuinn** [comment] 2020-08-27 06:03
I am beginner in cmake and vcpkg but if I understand correctly vcpkg integrate install allow cmake to find all libraries installed with vcpkg. Here is my cmake file:
```
cmake_minimum_required(VERSION 2.8 FATAL_ERROR)
set( CMAKE_TOOLCHAIN_FILE "C:\\dev\\vcpkg\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake" )
project(pcd_write)

find_package(PCL 1.2 REQUIRED)

include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (pcd_write pcd_write.cpp)
target_link_libraries (pcd_write ${PCL_LIBRARIES})
```

**Comment by atuinn** [comment] 2020-08-27 06:38
`ec.extract(cluster_indices);`
After commenting this line build is completed without error.

**Comment by larshg** [comment] 2020-08-27 07:11
If you use Cmake GUI you can enter the CMake tool chain here:
![image](https://user-images.githubusercontent.com/1165340/91408975-086d7500-e845-11ea-8cb9-f7ea44d0c871.png)

I'm not sure if it works the same way as you did, directly in the CmakeLists file, but it probably should.

Then verify in the generated project under Linker -> input that you have all the pcl_XX.libs added.

**Comment by atuinn** [comment] 2020-08-27 08:10
I did as you said. Still same error. Below are paths under Additional Dependencies:
```
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_segmentation.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_surface.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_keypoints.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_tracking.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_recognition.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_stereo.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\boost_system-vc140-mt.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\boost_filesystem-vc140-mt.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\boost_date_time-vc140-mt.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\boost_iostreams-vc140-mt.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\boost_regex-vc140-mt.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\qhull_p.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\flann_cpp.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_ml.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_registration.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_features.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_filters.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_sample_consensus.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_search.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_kdtree.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_io.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_octree.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\pcl_common.lib
C:\dev\vcpkg\vcpkg\installed\x64-windows\lib\lz4.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
```

**Comment by larshg** [comment] 2020-08-27 08:30
Seems like the euclideanClusterExtraction doesn't support PointNormal. If you change it to PointXYZ, then it will compile.

I reproduced the error with PointNormal type.

**Comment by larshg** [comment] 2020-08-27 08:36
The PCL version in vcpkg, becaues it windows, gets build with PCL_ONLY_CORE_POINT_TYPES. Which only expands to XYZ, XYZI, RGBA and RGB.

Alternatively you can include the extract_clusters.hpp file.

**Comment by atuinn** [comment] 2020-08-27 09:39
Indeed after including extract_clusters.hpp file compilation ended successfully. Thank you for your time.

**Comment by SergioRAgostinho** [comment] 2020-08-27 10:30
Closing since this is not an issue.

**Closed by SergioRAgostinho** 2020-08-27 10:30 UTC
Labels: kind: compile error, module: io, needs: author reply, platform: windows
