### ISSUE TITLE
New prebuilds and support for VS 2013

### ISSUE THREAD

**Issue by PhilLab** [PointCloudLibrary/pcl#1358] opened 2015-10-06 16:48 UTC
Prebuilds allow for a quick start and a steep learning curve using the library and would be nice :smile:
 
I know that providing them is a lot of work but is there anything planned (both in terms of newer visual studio versions and for new PCL versions - the [last prebuilds](http://pointclouds.org/downloads/windows.html) are for 1.6)?

Thanks for your maintenance and improvement of PCL!

**Comment by jspricke** [comment] 2015-10-06 17:51
New prebuilds build indeed be great, but currently we don't have any Windows developer. If you are willing to help, please write a mail to the pcl-dev mailing list.
Closing as it's not a bug.

**Closed by jspricke** 2015-10-06 17:51 UTC
