### ISSUE TITLE
Error with return of transform

### ISSUE THREAD

**Issue by martijnvwezel** [PointCloudLibrary/pcl#1359] opened 2015-10-06 19:08 UTC
Something is wrong with D:\GIT\pcl\doc\tutorials\content\sources\registration_api\example1.cpp

 161    Transformation (output, tgt, good_correspondences, transform);

It only gives NaN results back, so the second time it does ICP it breaks. Working on it to solve!

**Comment by jspricke** [comment] 2015-10-07 11:10
This depends a lot on your input data. Closing as it's not a bug.

**Closed by jspricke** 2015-10-07 11:10 UTC
