### ISSUE TITLE
vtkOutputWindows is spamming me with Deprecated warnings

### ISSUE THREAD

**Issue by ClementDardenne** [PointCloudLibrary/pcl#3145] opened 2019-06-11 16:03 UTC
Hi, 

## Your Environment
* Operating System and version: Windows 10
* Compiler: Visual Studio 2017
* PCL Version: PCL 1.9.1 (VTK provided by PCL in ThirdParty, version 8.1.2)

## Context
I'm using a PCLVisualizer to display a PoygonMesh. I update this PCLVisualizer (spinOnce) several times per second by adding spheres, lines and moving coordinate systems (the coordinates of these shapes come from a socket communication with an external software, but I don't think it's relevant here). 

Each time I run my program (Release mode), there is a vtkOutputWindow appearing, displaying several warnings endlessly, which slow considerably my PCLVisualizer. I can of course close the VTK window, but I would like to avoid to do it every time (+ it creates a delay between my packets received and what is displayed). 

The warnings : 
![image](https://user-images.githubusercontent.com/17929363/59287246-945fa500-8c71-11e9-9378-82df75e28e07.png)

I would like a way to disable this warning, or even better, not open at all the VTK window.

## Expected Behavior
Be able to turn off the vtkOutputWindows, or at least have a way to disable warnings.

## Possible Solution
I tried several things after some researches (not working so far) : 
1 - I tried to set the flag VTK_LEGACY_SILENT:BOOL=ON in VTKConfig.cmake, and re-generate with cmake, but no effects.
2 - Some suggested this piece of code, to redirect warnings to a file or stderr : 
vtkOutputWindow *w = vtkFileOutputWindow::New();
w->SetFileName("vtk_errors.txt")
vtkOutputWindow::SetInstance(w);
w->Delete(); // now SetInstance owns the reference
or 
vtkSmartPointer<vtkWin32OutputWindow> myOutputWindow = vtkSmartPointer<vtkWin32OutputWindow>::New(); 
myOutputWindow->SetSendToStdErr(true);
vtkOutputWindow::SetInstance(myOutputWindow);
or
vtkObject::GlobalWarningDisplayOff();

Same, no effects.

I would really appreciate some suggestions, it looks like it's a well-known issue, but there is no solutions so far. Thank you in advance.

Clément

**Comment by taketwo** [comment] 2019-06-11 16:37
Duplicate of #2619, please have a look there. You will need to either switch to unreleased PCL master or [add a line to your code](https://github.com/PointCloudLibrary/pcl/issues/2619#issuecomment-471609940).

**Closed by taketwo** 2019-06-11 16:37 UTC
