### ISSUE TITLE
"data member initializer is not allowed", when include <pcl/point_types.h> into .cu file

### ISSUE THREAD

**Issue by zhuyu2015** [PointCloudLibrary/pcl#3267] opened 2019-08-02 13:26 UTC
"data member initializer is not allowed", when include <pcl/point_types.h> into .cu file

## Your Environment

* Operating System and version: windows 10, 1809
* Compiler: nvcc
* PCL Version: 1.9.1-6

## Current Behavior
there will be many error: data member initializer is not allowed, whenever I include the <pcl/point_types.h> in a nvcc compiled .cu, .cpp, or .hpp file.

## Code to Reproduce
#include <cuda_runtime.h>
#include <cuda.h>
#include <pcl/point_types.h>
int main()
{
	int x = 10;
	
	return 0;
}

**Comment by KaliEtQuali** [comment] 2019-12-03 14:15
Hello,
I'm facing the same issue: Did you find a solution for this ?

**Comment by kunaltyagi** [comment] 2019-12-04 07:26
Please provide more details. The issue is definitely solved for current released PCL 1.9.1-1

```c++
// cuda
#include <cuda.h>
#include <cuda_runtime.h>

// pcl
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>

int main() {
int x = 10;
pcl::PointCloud<pcl::PointXYZ>* ptr = nullptr;
return 0;
}
```
```bash
$ nvcc main.cpp -I/usr/include/pcl-1.9/ -I /usr/include/eigen3/
$ ./a.out
10
```

Might be an issue of nvcc version
```bash
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by funmonty** [comment] 2019-12-10 05:43
I'm facing the same issue. 

CUDA : 10.0
Windows 10
PCL 1.8.1

**Comment by kunaltyagi** [comment] 2019-12-10 07:16
Seems like a Windows platform issue. Can't reproduce on Linux.

**Comment by funmonty** [comment] 2019-12-10 08:12
@zhuyu2015, Are you using CMake to generate make files? If yes, can you share it here?

**Comment by vishnukumarts** [comment] 2020-01-01 14:57
+1

**Comment by vishnukumarts** [comment] 2020-01-02 15:14
What is the solution with windows?, I tried with PCL 1.9.1, same issue occurs.

**Comment by larshg** [comment] 2020-05-14 19:14
I just tested master and it compiles. It does however spawn a lot of these warnings:

`Warning: offsetof applied to non-POD types is nonstandard`.

Lets close this.

**Closed** 2020-05-14 21:11 UTC
Labels: platform: windows
