### ISSUE TITLE
Within a new project, this compile process has a bug in two header files (type_traits.h and point_struct_traits.h).

### ISSUE THREAD

**Issue by piluohong** [PointCloudLibrary/pcl#6057] opened 2024-05-29 08:07 UTC
error: redefinition of ‘struct pcl::traits::decomposeArray<T>’
   68 |  template<typename T> struct decomposeArray; 
These two header files (type_traits.h and point_struct_traits.h) are conficted.

**Comment by mvieth** [comment] 2024-05-29 08:52
@piluohong 
- Which operating system do you use?
- Which PCL version do you use? How did you install it?
- Which compiler do you use?
- Can you provide a small program that I can use to reproduce the error?

**Comment by mvieth** [comment] 2024-06-03 08:24
@piluohong If you don't reply soon, I will close this issue. In PCL 1.11.0, `decomposeArray` is defined in type_traits.h. Since PCL 1.11.1, `decomposeArray` is defined in point_struct_traits.h. There is no PCL version where it is defined in both headers. My best guess is that you have multiple PCL versions installed.

**Closed** 2024-06-06 08:52 UTC
Labels: kind: compile error, status: triage

**Comment by piluohong** [comment] 2024-06-07 03:40
Sorry for not checking it in time. I've had this happen to both ubuntu18.04 and ubuntu20.04, where ubuntu18.04 has multiple versions, but I isolated them when I linked. ubuntu20.04 is the PCL that only comes with ROS noetic. Then I installed PCL1.14.0 version and this kind of problem also appeared. The project I compiled is Coco-LIC, which is available on github. Sorry again for not checking your reply in time, thank you for your kind answer

**Comment by piluohong** [comment] 2024-06-07 03:46
This is in ubuntu 20.04. ROS's PCL is 1.10. I install PCL 1.14.0 by source code. Then
/usr/local/include/pcl-1.14/pcl/type_traits.h:103:23: error: redefinition of ‘struct pcl::traits::asType<2>’
  103 |     template<> struct asType<detail::PointFieldTypes::UINT8>   { using type = std::uint8_t; };
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by MGforest** [comment] 2024-08-20 11:42
Hi @piluohong , 
I have the same situation and error. 

> This is in ubuntu 20.04. ROS's PCL is 1.10. I install PCL 1.14.0 by source code.

This is not a PCL problem, but I don't know how to work around it. noetic needs 1.10 and COCO-LIC 1.14. 
Did you find a solution? 

Many thanks in advance for your reply.
