### ISSUE TITLE
[compile error] "PCL1.11 boost shared pointer not supported"

### ISSUE THREAD

**Issue by Joechencc** [PointCloudLibrary/pcl#4305] opened 2020-08-05 16:10 UTC
I know from PCL1.11 boost sharepointer is changed to std sharepointer. When I conduct experiment in ROS_tutorial like to subscribe a point cloud, this error pops up. http://wiki.ros.org/pcl_ros

How can I subscribe a pointcloud using pcl1.11

**Comment by kunaltyagi** [comment] 2020-08-05 18:20
1. That's not an error, that's the wiki page
2. Please use latest `perception_pcl`. We've [added code there](https://github.com/ros-perception/perception_pcl/blob/melodic-devel/pcl_ros/include/pcl_ros/point_cloud.h#L347) to ensure compatibility (backwards and forwards)
3. Please use ROS's type aliases while dealing with ROS

Closing as not a bug. Please use discord or discourse.ros to discuss such issues

**Comment by Joechencc** [comment] 2020-08-05 23:52
The error is like following:
/usr/include/boost/function/function_template.hpp: In instantiation of ‘static void boost::detail::function::void_function_invoker1<functionptr, r,="" t0="">::invoke(boost::detail::function::function_buffer&, T0) [with FunctionPtr = void ()(const std::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&); R = void; T0 = const boost::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&]’: /usr/include/boost/function/function_template.hpp:925:38: required from ‘void boost::function1<r, t1="">::assign_to(Functor) [with Functor = void ()(const std::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&); R = void; T0 = const boost::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&]’ /usr/include/boost/function/function_template.hpp:716:7: required from ‘boost::function1<r, t1="">::function1(Functor, typename boost::enable_if_c<(! boost::is_integral<functor>::value), int>::type) [with Functor = void ()(const std::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&); R = void; T0 = const boost::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&; typename boost::enable_if_c<(! boost::is_integral<functor>::value), int>::type = int]’ /usr/include/boost/function/function_template.hpp:1061:16: required from ‘boost::function<r(t0)&gt;::function(functor, typename="" boost::enable_if_c&lt;(!="" boost::is_integral<functor="">::value), int>::type) [with Functor = void ()(const std::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&); R = void; T0 = const boost::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&; typename boost::enable_if_c<(! boost::is_integral<functor>::value), int>::type = int]’ /home/chao/catkin_ws/src/beginner_tutorials/src/pointcloudlistener.cpp:138:88: required from here /usr/include/boost/function/function_template.hpp:118:11: error: invalid initialization of reference of type ‘const std::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >&’ from expression of type ‘const boost::shared_ptr<const pcl::pointcloud<pcl::pointxyz=""> >’ BOOST_FUNCTION_RETURN(f(BOOST_FUNCTION_ARGS)); ^ beginner_tutorials/CMakeFiles/pointcloudlistener.dir/build.make:62: recipe for target 'beginner_tutorials/CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o' failed make[2]: * [beginner_tutorials/CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o] Error 1 CMakeFiles/Makefile2:486: recipe for target 'beginner_tutorials/CMakeFiles/pointcloudlistener.dir/all' failed make[1]: [beginner_tutorials/CMakeFiles/pointcloudlistener.dir/all] Error 2 Makefile:140: recipe for target 'all' failed make: ** [all] Error 2

**Comment by kunaltyagi** [comment] 2020-08-06 02:42
@Joechencc said:

I download and build PCL1.11 from the link here: PointCloudLibrary/pcl.git

and installed http://wiki.ros.org/perception_pcl in ROS. Why do I still have this problem? My code works at Ubuntu16.04 with pcl version 1.8. The code is linked here: Joechencc/minicheetah3Dvisulization@master/beginner_tutorials/src/pointcloudlistener.cpp

Can you tell me why PCL 1.11 does not work?

The error is like following:

```
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o: In function callback(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZ> const> const&)': pointcloudlistener.cpp:(.text+0x390): undefined reference to pcl::PCLBasepcl::PointXYZ::setInputCloud(boost::shared_ptr<pcl::PointCloudpcl::PointXYZ const> const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl16NormalEstimationINS_8PointXYZENS_11PointNormalEEE[_ZTVN3pcl16NormalEstimationINS_8PointXYZENS_11PointNormalEEE]+0x28): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl16NormalEstimationINS_8PointXYZENS_11PointNormalEEE[_ZTVN3pcl16NormalEstimationINS_8PointXYZENS_11PointNormalEEE]+0x30): undefined reference to pcl::PCLBasepcl::PointXYZ::setIndices(boost::shared_ptr<std::vector<int, std::allocator > const> const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl16NormalEstimationINS_8PointXYZENS_11PointNormalEEE[_ZTVN3pcl16NormalEstimationINS_8PointXYZENS_11PointNormalEEE]+0x38): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl7FeatureINS_8PointXYZENS_11PointNormalEEE[_ZTVN3pcl7FeatureINS_8PointXYZENS_11PointNormalEEE]+0x20): undefined reference to pcl::PCLBasepcl::PointXYZ::setInputCloud(boost::shared_ptr<pcl::PointCloudpcl::PointXYZ const> const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl7FeatureINS_8PointXYZENS_11PointNormalEEE[_ZTVN3pcl7FeatureINS_8PointXYZENS_11PointNormalEEE]+0x28): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > > const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl7FeatureINS_8PointXYZENS_11PointNormalEEE[_ZTVN3pcl7FeatureINS_8PointXYZENS_11PointNormalEEE]+0x30): undefined reference to pcl::PCLBasepcl::PointXYZ::setIndices(boost::shared_ptr<std::vector<int, std::allocator > const> const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl7FeatureINS_8PointXYZENS_11PointNormalEEE[_ZTVN3pcl7FeatureINS_8PointXYZENS_11PointNormalEEE]+0x38): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl6search6SearchINS_8PointXYZEEE[_ZTVN3pcl6search6SearchINS_8PointXYZEEE]+0x38): undefined reference to pcl::search::Searchpcl::PointXYZ::setInputCloud(boost::shared_ptr<pcl::PointCloudpcl::PointXYZ const> const&, boost::shared_ptr<std::vector<int, std::allocator > const> const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl9VoxelGridINS_8PointXYZEEE[_ZTVN3pcl9VoxelGridINS_8PointXYZEEE]+0x20): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZ> const> const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl9VoxelGridINS_8PointXYZEEE[_ZTVN3pcl9VoxelGridINS_8PointXYZEEE]+0x28): undefined reference to pcl::PCLBasepcl::PointXYZ::setIndices(boost::shared_ptr<std::vector<int, std::allocator > > const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl9VoxelGridINS_8PointXYZEEE[_ZTVN3pcl9VoxelGridINS_8PointXYZEEE]+0x30): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl9VoxelGridINS_8PointXYZEEE[_ZTVN3pcl9VoxelGridINS_8PointXYZEEE]+0x38): undefined reference to pcl::PCLBasepcl::PointXYZ::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl6FilterINS_8PointXYZEEE[_ZTVN3pcl6FilterINS_8PointXYZEEE]+0x20): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZ> const> const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl6FilterINS_8PointXYZEEE[_ZTVN3pcl6FilterINS_8PointXYZEEE]+0x28): undefined reference to pcl::PCLBasepcl::PointXYZ::setIndices(boost::shared_ptr<std::vector<int, std::allocator > > const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl6FilterINS_8PointXYZEEE[_ZTVN3pcl6FilterINS_8PointXYZEEE]+0x30): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl6FilterINS_8PointXYZEEE[_ZTVN3pcl6FilterINS_8PointXYZEEE]+0x38): undefined reference to pcl::PCLBasepcl::PointXYZ::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl7PCLBaseINS_8PointXYZEEE[_ZTVN3pcl7PCLBaseINS_8PointXYZEEE]+0x20): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setInputCloud(boost::shared_ptr<pcl::PointCloud<pcl::PointXYZ> const> const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl7PCLBaseINS_8PointXYZEEE[_ZTVN3pcl7PCLBaseINS_8PointXYZEEE]+0x28): undefined reference to pcl::PCLBasepcl::PointXYZ::setIndices(boost::shared_ptr<std::vector<int, std::allocator > > const&)'
CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl7PCLBaseINS_8PointXYZEEE[_ZTVN3pcl7PCLBaseINS_8PointXYZEEE]+0x30): undefined reference to pcl::PCLBase<pcl::PointXYZ>::setIndices(boost::shared_ptr<std::vector<int, std::allocator<int> > const> const&)' CMakeFiles/pointcloudlistener.dir/src/pointcloudlistener.cpp.o:(.data.rel.ro._ZTVN3pcl7PCLBaseINS_8PointXYZEEE[_ZTVN3pcl7PCLBaseINS_8PointXYZEEE]+0x38): undefined reference to pcl::PCLBasepcl::PointXYZ::setIndices(boost::shared_ptr<pcl::PointIndices const> const&)'
collect2: error: ld returned 1 exit status
beginner_tutorials/CMakeFiles/pointcloudlistener.dir/build.make:379: recipe for target '/home/chaonew/catkin_make/devel/lib/beginner_tutorials/pointcloudlistener' failed
make[2]: *** [/home/chaonew/catkin_make/devel/lib/beginner_tutorials/pointcloudlistener] Error 1
CMakeFiles/Makefile2:578: recipe for target 'beginner_tutorials/CMakeFiles/pointcloudlistener.dir/all' failed
```

**Comment by kunaltyagi** [comment] 2020-08-06 02:51
Please don't open new issues. You can continue asking on closed issues. If needed, reopen an issue, but **it'd be closed if it's not a bug**

> Can you tell me why PCL 1.11 does not work?

PCL shifted to std pointers while ROS is using boost pointers

> should I install PCL 1.11 from the link you shared? Is there installation guide for this??

The link I shared was for 
1. `perception_pcl`: used by ROS and possibly you under-the-hood for message passing
2. Workaround for getting std and boost pointers to work together

Please search for the `ros_ptr` and `pcl_ptr` in that repository to understand how to use smart pointers while juggling ROS and PCL's demands.

Installing perception_pcl is very easy if you use `catkin` tools. You just need to clone the repository in your workspace. If you're using `catkin_make` instead, please create an underlay workspace (aka your workspace overlays the workspace where perception_pcl is installed). ROS has a [tutorial for that here](https://wiki.ros.org/catkin/Tutorials/workspace_overlaying)

Please note that using custom PCL version with ROS is considered an advanced operation. This is an issue with ROS and not with PCL hence why the ticket was closed (and will be closed again).

Please use discord to discuss this further and if you have time, submit a Pull Request with a tutorial for others to learn from. It's difficult to make tutorials for beginners since we can't understand the issues faced by them.

**Closed by kunaltyagi** 2020-08-06 02:51 UTC
Labels: kind: compile error

**Comment by Joechencc** [comment] 2020-08-06 07:27
I know where is the problem and I installed perception_pcl in ROS, but the problem still exists, and I do not know how to get std and boost pointers to work together . Can you share the discord link please?

**Comment by kunaltyagi** [comment] 2020-08-06 10:15
> if convenient, can you share the discord link please?

It's on the README. https://discord.gg/JFFMAXS

> How to construct callback function to make it work?

You can't use `pcl::XXXX::Ptr` for ROS. You have to use the typedefs that ROS provides. ROS uses `boost::shared_ptr` explicitly. Eg: https://github.com/ros-perception/perception_pcl/blob/melodic-devel/pcl_ros/include/pcl_ros/features/feature.h#L72

You'll need to do something similar. Or replace `pcl::XXXX::ConstPtr` with `boost::shared_ptr<const pcl::XXX>`

The subscription part doesn't need to be changed. You'll also need to use `ros_ptr` and `pcl_ptr` on the interface boundaries. See https://github.com/ros-perception/perception_pcl/blob/e812d3cf1b67cc73841b41e690d53c74e5077a05/pcl_ros/src/pcl_ros/features/normal_3d.cpp#L59-L69 for example
