### ISSUE TITLE
statistical_outlier_removal does not appear to work with Ubuntu pre-built libpcl-all OR a libpcl-all issue

### ISSUE THREAD

**Issue by meder411** [PointCloudLibrary/pcl#1666] opened 2016-07-30 18:27 UTC
I am compiling the [example from here](http://pointclouds.org/documentation/tutorials/statistical_outlier.php) on Ubuntu 14.04 using CMake. My program wasn't working, so I tried the exact example from the docs except with my pointcloud file (a .ply file) and got the same error.

I am wondering if my  issue is due to outdated docs or an outdated/faulty binary.  The build complains about a faulty package, which seems to be true based on a search of my file system. It's wholly possible that if the binary issue is fixed, the statistical_outlier_removal issue will disappear as well.

The weird part is, though, that I have also tried running this through [python-pcl](https://github.com/strawlab/python-pcl) and their [Python adaptation of this filter](https://github.com/strawlab/python-pcl/blob/master/examples/statistical_outlier_fiter.py) works just fine on my system.

----------------------------------------------------
MY PROBLEM
----------------------------------------------------
My commands:

`mkdir build`
`cd build`
`cmake ..`
`make`

Output & Error:

    Scanning dependencies of target test
    [100%] Building CXX object CMakeFiles/test.dir/test.cpp.o
    Linking CXX executable test
    CMakeFiles/test.dir/test.cpp.o (.rodata._ZTVN3pcl25StatisticalOutlierRemovalINS_8PointXYZEEE[_ZTVN3pcl25StatisticalOutlierRemovalINS_8PointXYZEEE]+0x48): undefined reference to `pcl::StatisticalOutlierRemoval<pcl::PointXYZ>::applyFilter(pcl::PointCloud<pcl::PointXYZ>&)'
    CMakeFiles/test.dir/test.cpp.o: In function `pcl::StatisticalOutlierRemoval<pcl::PointXYZ>::applyFilter(std::vector<int, std::allocator<int> >&)':
    /usr/include/pcl-1.7/pcl/filters/statistical_outlier_removal.h:169: undefined reference to `pcl::StatisticalOutlierRemoval<pcl::PointXYZ>::applyFilterIndices(std::vector<int, std::allocator<int> >&)'
    collect2: error: ld returned 1 exit status
    make[2]: *** [test] Error 1
    make[1]: *** [CMakeFiles/test.dir/all] Error 2
    make: *** [all] Error 2

----------------------------------------------------
MY INSTALLATION
----------------------------------------------------

I installed PCL by following the [instructions from here](http://pointclouds.org/downloads/linux.html):

`sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl`
`sudo apt-get update`
`sudo apt-get install libpcl-all`

NOTE: These instructions led to a lot of complaining from my builds, excerpts are pasted below. I tried changing the last step to `sudo apt-get install libpcl-1.7-all` but the complaining continued:

> -- The imported target "vtkHybridJava" references the file
>    "/usr/lib/jni/libvtkHybridJava.so.5.8.0"
> but this file does not exist.  Possible reasons include:
> * The file was deleted, renamed, or moved to another location.
> * An install or uninstall procedure did not complete successfully.
> * The installation package was faulty and contained
>    "/usr/lib/vtk-5.8/VTKTargets.cmake"
> but not all the files it references.
> 
> -- The imported target "vtkWidgetsTCL" references the file
>    "/usr/lib/libvtkWidgetsTCL.so.5.8.0"
> but this file does not exist.  Possible reasons include:
> * The file was deleted, renamed, or moved to another location.
> * An install or uninstall procedure did not complete successfully.
> * The installation package was faulty and contained
>    "/usr/lib/vtk-5.8/VTKTargets.cmake"
> but not all the files it references.
> 
> -- The imported target "vtkWidgetsPythonD" references the file
>    "/usr/lib/libvtkWidgetsPythonD.so.5.8.0"
> but this file does not exist.  Possible reasons include:
> * The file was deleted, renamed, or moved to another location.
> * An install or uninstall procedure did not complete successfully.
> * The installation package was faulty and contained
>    "/usr/lib/vtk-5.8/VTKTargets.cmake"
> but not all the files it references.

I checked and my file system does not have those referenced files. However, I do have the files mentioned as fault (i.e. the .cmake files). Perhaps this is the cause of my problem?

----------------------------------------------------
MY FILES
----------------------------------------------------

test.cpp:

    #include <iostream>
    #include <pcl/io/pcd_io.h>
    #include <pcl/point_types.h>
    #include <pcl/filters/statistical_outlier_removal.h>

    int main (int argc, char** argv)
    {
      pcl::PointCloud<pcl::PointXYZ>::Ptr cloud (new pcl::PointCloud<pcl::PointXYZ>);
      pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered (new pcl::PointCloud<pcl::PointXYZ>);

      // Fill in the cloud data
      pcl::PCDReader reader;
      // Replace the path below with the path where you saved your file
      reader.read<pcl::PointXYZ> ("reconstruction.ply", *cloud);

      std::cerr << "Cloud before filtering: " << std::endl;
      std::cerr << *cloud << std::endl;

      // Create the filtering object
      pcl::StatisticalOutlierRemoval<pcl::PointXYZ> sor;
      sor.setInputCloud (cloud);
      sor.setMeanK (50);
      sor.setStddevMulThresh (1.0);
      sor.filter (*cloud_filtered);

      std::cerr << "Cloud after filtering: " << std::endl;
      std::cerr << *cloud_filtered << std::endl;

      pcl::PCDWriter writer;
      writer.write<pcl::PointXYZ> ("reconstruction_inliers.ply", *cloud_filtered, false);

      sor.setNegative (true);
      sor.filter (*cloud_filtered);
      writer.write<pcl::PointXYZ> ("reconstruction_outliers.ply", *cloud_filtered, false);

      return (0);
    }

CMakeLists.txt:

	cmake_minimum_required(VERSION 2.6 FATAL_ERROR)
	project(Mesh)
	find_package(PCL 1.2 REQUIRED)

	include_directories(${PCL_INCLUDE_DIRS})
	link_directories(${PCL_LIBRARY_DIRS})
	add_definitions(${PCL_DEFINITIONS})

	include(CheckCXXCompilerFlag)
	CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
	if(COMPILER_SUPPORTS_CXX11)
	    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
	else()
	        message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
	endif()
	add_executable(test test.cpp)
	target_link_libraries(test ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES})

**Comment by SergioRAgostinho** [comment] 2016-08-22 23:14
I was unable to reproduce the linking error you're getting with the test files you provided. Can you provide more info about on the pcl version you're running. As a potential work around, have you considered to compile the 1.8.0 from source and see if you still get the same thing. 

The way I see it it looks really strange, because you seem to link OK against pcl-filters, but at the same time, the symbols for that method are not there...

**Comment by SergioRAgostinho** [comment] 2016-08-22 23:31
I was able to reproduce it after all. You're not linking against pcl-filters
```
target_link_libraries(test ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES})
```

you need to add `${PCL_FILTERS_LIBRARIES}` like this
```
target_link_libraries(test ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES} ${PCL_FILTERS_LIBRARIES})
```
Closing this now. Reopen if it's not solved.

**Closed by SergioRAgostinho** 2016-08-22 23:31 UTC
Labels: status: waiting feedback

**Comment by Joecool48** [comment] 2018-02-17 03:01
Hi guys,

I have a very similar problem with pcl not being able to find any filter I try to use. Here is my CMakeList and program. For some reason no matter what I try if I include any filter in my program from pcl catkin_make gives errors.

Thanks!

Here is CMake lists:

`cmake_minimum_required(VERSION 2.8.3)
project(lidar)
catkin_package(
   INCLUDE_DIRS include
   LIBRARIES ${PROJECT_NAME}
   )
find_package(PCL 1.2 REQUIRED COMPONENTS common io visualization filters)
find_package(catkin REQUIRED COMPONENTS
  roscpp
  rospy
  rplidar_ros
  sensor_msgs
  std_msgs
  pcl_ros
  PCL
)
find_package(PCL REQUIRED COMPONENTS common io visualization)
find_package(Boost REQUIRED COMPONENTS system)
find_package(Eigen 3 QUIET)

include_directories(${catkin_INCLUDE_DIRS} ${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})

add_executable (obstacleAvoidance src/obstacleAvoidance.cpp)

target_link_libraries(obstacleAvoidance ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES} ${Boost_LIBRARIES} ${catkin_LIBRARIES} ${PCL_LIBRARIES} ${PCL_FILTERS_LIBRARIES})`


Here is my code:

`#include <stdio.h>
#include "ros/ros.h"
#include <iostream>
#include "sensor_msgs/LaserScan.h"
#include "pcl_ros/point_cloud.h"
#include "pcl/point_types.h"
#include "pcl/filters/passthrough.h"
#include "pcl/filters/statistical_outlier_removal.h"

ros::Publisher pub;
int frameCount = 0;
typedef pcl::PointCloud<pcl::PointXY> PointCloud;
void scanCallback(const sensor_msgs::LaserScan::ConstPtr& scan)
{
	PointCloud::Ptr cloud (new PointCloud);
	cloud->header.frame_id = "Frame: " + frameCount;
	frameCount++;
    int count = scan->scan_time / scan->time_increment;
    cloud->width = count;
    cloud->height = 1;
    //ROS_INFO("I heard a laser scan %s[%d]:", scan->header.frame_id.c_str(), count);
    //ROS_INFO("angle_range, %f, %f", RAD2DEG(scan->angle_min), RAD2DEG(scan->angle_max));
    int actualSize = 0;
    for(int i = 0; i < count; i++) {
    	float radians = scan->angle_min + scan->angle_increment * i;
    	float range = scan->ranges[i];
    	if (!(range > scan->range_max) && !(range < scan->range_min)) {
    		double x = range * cos(radians);
    		double y = range * sin(radians);
    		pcl::PointXY point;
    		point.x = x;
    		point.y = y;
    		cloud->points.push_back (point);
    		actualSize++;
    	}
    }
    cloud->width = actualSize;
    //Declare new cloud for after filtering
    pcl::PassThrough<pcl::PointXY> pass_x;
    pcl::PassThrough<pcl::PointXY> pass_y;

    pass_x.setInputCloud (cloud);
    //Filter the cloud
    // pcl::StatisticalOutlierRemoval<pcl::PointXY> sor;
    // sor.setInputCloud (cloud);
    // sor.setMeanK (50);
    // sor.setStddevMulThresh (1.0);
    // sor.filter (*filtered);
    //cloud->header.stamp = ros::Time::now().toNSec();
    pub.publish (cloud);

}

int main(int argc, char **argv)
{
    ros::init(argc, argv, "obstacleAvoidance");
    ros::NodeHandle n;

    ros::Subscriber sub = n.subscribe<sensor_msgs::LaserScan>("/scan", 10, scanCallback);

    pub = n.advertise<PointCloud> ("cloud", 10);

    ros::spin();

    return 0;
}`

And her is the exact error message it gives every time:

CMakeFiles/obstacleAvoidance.dir/src/obstacleAvoidance.cpp.o:(.data.rel.ro._ZTVN3pcl11PassThroughINS_7PointXYEEE[_ZTVN3pcl11PassThroughINS_7PointXYEEE]+0x48): undefined reference to `pcl::PassThrough<pcl::PointXY>::applyFilter(pcl::PointCloud<pcl::PointXY>&)'
CMakeFiles/obstacleAvoidance.dir/src/obstacleAvoidance.cpp.o: In function `pcl::PassThrough<pcl::PointXY>::applyFilter(std::vector<int, std::allocator<int> >&)':
obstacleAvoidance.cpp:(.text._ZN3pcl11PassThroughINS_7PointXYEE11applyFilterERSt6vectorIiSaIiEE[_ZN3pcl11PassThroughINS_7PointXYEE11applyFilterERSt6vectorIiSaIiEE]+0x1f): undefined reference to `pcl::PassThrough<pcl::PointXY>::applyFilterIndices(std::vector<int, std::allocator<int> >&)'
collect2: error: ld returned 1 exit status
lidar/CMakeFiles/obstacleAvoidance.dir/build.make:1636: recipe for target '/home/joey/catkin_ws/devel/lib/lidar/obstacleAvoidance' failed
make[2]: *** [/home/joey/catkin_ws/devel/lib/lidar/obstacleAvoidance] Error 1
CMakeFiles/Makefile2:1299: recipe for target 'lidar/CMakeFiles/obstacleAvoidance.dir/all' failed
make[1]: *** [lidar/CMakeFiles/obstacleAvoidance.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by taketwo** [comment] 2018-02-19 13:43
Why do you have two times `find_package(PCL ...`? The second time you do not search for filters component, so maybe this is the problem.
