### ISSUE TITLE
function PointCloudXYZRGBAtoXYZHSV is never used.

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2477] opened 2018-09-26 13:04 UTC
## Your Environment

* PCL Version: the master branch

## Context

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L138-L146

the alpha value is not used during the conversion.
In addition, this function duplicates the code from
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L101-L107

Since `PointXYZRGBAtoXYZHSV()` is used only by
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/point_types_conversion.h#L316-L322

But `PointCloudXYZRGBAtoXYZHSV()` is never used.
## Expected Behavior

Remove the above two functions `PointCloudXYZRGBAtoXYZHSV()`
and `PointXYZRGBAtoXYZHSV()`.

Are there any reason to introduce the above two functions?

## Code to Reproduce

See the code above.

## Possible Solution

Remove the two unsed functions.

**Comment by taketwo** [comment] 2018-10-07 05:56
We already have a ticket #1928. (Though there has been no progress on it). Can we merge this issue into it?

**Comment by csukuangfj** [comment] 2018-10-08 01:37
yes, I agree.

**Comment by SergioRAgostinho** [comment] 2018-10-08 08:28
Duplicate of #1928.

**Closed by SergioRAgostinho** 2018-10-08 08:28 UTC
