### ISSUE TITLE
Oppeni2 destructor stalls if a callback has been registered

### ISSUE THREAD

**Issue by patatahooligan** [PointCloudLibrary/pcl#1982] opened 2017-09-01 15:36 UTC
## Environment

* OS: Windows 7 Home Premium 64-bit
* Compiler: MSVC v14.1
* PCL Version: 1.8.0

I know that there is a more recent PCL version but I can't switch to it right now and I've checked that recorded changes after 1.8.0 have not addressed this.

## Description
If a callback has been registered to `OpenNI2Grabber`, the destructor stalls while waiting for a critical section to be unlocked in an XnLib call. However, the owner thread id is invalid. It seems to be the thread that calls the callback function. That thread does not exist anymore at this point, though. It appears that the thread is forcefully (but silently) killed while holding a lock.

I won't post the whole call stack because it's huge and most calls are not particularly enlightening. It does contain the following:

    ntdll.dll!_NtWaitForSingleObject@12()
    ntdll.dll!_RtlpWaitOnCriticalSection@8()
    ntdll.dll!_RtlEnterCriticalSection@4()
    OpenNI2.dll!xnOSEnterCriticalSection(_RTL_CRITICAL_SECTION * * pCriticalSectionHandle)
    ...
    pcl_io_debug.dll!pcl::io::openni2::OpenNI2Device::~OpenNI2Device()
    ....
    pcl_io_debug.dll!pcl::io::OpenNI2Grabber::~OpenNI2Grabber()

## Possible Solution
I'm not familiar enough with the code base to fix it myself. However, I noticed that waiting a few seconds after disconnecting my callback, but before calling `OpenNI2Grabber::stop()` or letting the object get destroyed, lets the program exit normally. As no synchronization mechanism is offered in the class API, I suggest `OpenNI2Grabber::stop()` signals the thread that calls the callback to exit normally and then blocks internally until it has joined and the object is in a valid and destructible state.

At the very least, the destructor could do the waiting for the thread to join, but I believe people writing multi-threaded applications would expect the device to have stopped streaming after a call to `stop()`. As I mentioned, no mechanism is offered to the user to enforce synchronization on their own. Thus, `stop()` waiting for the callback mechanism to stop seems appropriate.

EDIT: I should have mentioned that `OpenNI2Grabber::isRunning()`'s return value is dependent on calls to `OpenNI2Grabber::start()` and `OpenNI2Grabber::stop()` and does not in my tests indicate whether the object is safe to destroy.

## Code to Reproduce
oni2wrapper.h

    class Oni2Wrapper {
        public:
            void run();

            Oni2Wrapper():
                viewer("Viewer") {}

        private:
            pcl::visualization::CloudViewer viewer;

            void callback(const pcl::PointCloud<pcl::PointXYZ>::ConstPtr &cloud);
    };

oni2wrapper.cpp

    void Oni2Wrapper::run() {
        pcl::io::OpenNI2Grabber oni2_grabber;

        boost::function<void(const pcl::PointCloud<pcl::PointXYZ>::ConstPtr&)> cb =
         boost::bind(&Oni2Wrapper::callback, this, _1);
        auto connection = oni2_grabber.registerCallback(cb);
	
        oni2_grabber.start();
        while (!viewer.wasStopped())
            boost::this_thread::sleep_for(boost::chrono::milliseconds(100));

        connection.disconnect();
        // Uncommenting the following line fixes the problem
        // boost::this_thread::sleep_for(boost::chrono::seconds(5));
        oni2_grabber.stop();
    }

    void Oni2Wrapper::callback(const pcl::PointCloud<pcl::PointXYZ>::ConstPtr &cloud) {
        viewer.showCloud(cloud);
    }

main.cpp

    int main() {
        Oni2Wrapper oni2_wrapper;
        oni2_wrapper.run();
        return 0;
    }

**Comment by taketwo** [comment] 2017-09-04 15:21
FWIW, this is not reproducible on Ubuntu 16.04 with PCL master.

**Comment by SergioRAgostinho** [comment] 2017-11-26 01:59
@UnaNancyOwen can you test this?

**Comment by UnaNancyOwen** [comment] 2017-11-26 14:07
I could not confirm this problem on my environment.
It seems to be the reproduce code works correctly.
(PCL 1.8.1, Visual Studio 15 2017 Win64)

**Comment by SergioRAgostinho** [comment] 2017-11-26 14:14
Thanks. Closing it since it doesn't seem to affect current master. 

@patatahooligan Please reopen if needed or if you have any new updates.

**Closed by SergioRAgostinho** 2017-11-26 14:14 UTC
Labels: platform: windows, status: needs testing
