### ISSUE TITLE
Building time of a project which depends on PCL is too long

### ISSUE THREAD

**Issue by MBSadeghzadeh** [PointCloudLibrary/pcl#4690] opened 2021-04-04 15:00 UTC
I have created a project in visual studio 2015 and installed PCL 1-8-0. I have included 
```
#include <pcl/point_cloud.h>
#include <pcl/io/pcd_io.h>
#include <pcl/point_types.h>
#include <pcl/filters/passthrough.h>
#include <pcl/common/transforms.h>
#include <pcl/filters/crop_box.h>
#include <pcl/filters/voxel_grid.h>
```
and when I change any header file of mine, it takes a long time to build the project.  Rebuilding the project also gets a huge time.
Is there any way to get rid of this?

**Comment by mvieth** [comment] 2021-04-04 18:38
Yes, building a project that uses PCL takes a bit of time. How much time does it take for you (roughly)?
Keep in mind that when you change a header file, every file that includes that header file has to be rebuilt.
There are a few things you can try to reduce your build time:
- only include those files you really need. There is a cool tool that helps you identify unnecessary includes called "include-what-you-use". Not sure it runs under Windows though (assuming you use Windows)
- parallelize your builds (more than one build job). With `make` this works with `make -j2` for 2 jobs, for example. I don't know about visual studio, but there is probably a similar option there
- modularize your project. If you modify a file, that file and every file that depends on that file has to be rebuilt. If you split your project into several header and implementation (.cpp) files, less code has to be recompiled when you make a change. Your headers should be a small as possible
- switching to the newest PCL version, 1.11.1, _might_ save you some time during building
- if you turned the optimization in your compiler on, that will also make your build slower. Consider when you want a fast build and when you want an optimized program

**Comment by MBSadeghzadeh** [comment] 2021-04-22 08:57
I get more than 30 thousands of compiler warnings. May it lead to slowness?

**Comment by MBSadeghzadeh** [comment] 2021-04-22 09:03
The IntelliSense also gets ridiculously slow.

**Comment by kunaltyagi** [comment] 2021-04-22 09:06
Please submit questions and bug requests about IntelliSense to IntelliSense :)

**Comment by MBSadeghzadeh** [comment] 2021-04-22 09:10
But build also is slow. It takes me several minutes each time to build.

**Comment by kunaltyagi** [comment] 2021-04-22 09:26
Answered above by mvieth. Please feel free to contribute to reduce the build time. Closing the issue since it's:
* not a bug
* duplicate of #3414

**Closed by kunaltyagi** 2021-04-22 09:26 UTC
Labels: kind: question

**Comment by larshg** [comment] 2021-04-22 10:04
Visual studio is just slow, when working with projects like PCL, probably due to heavy use of templates, boost headers, eigen headers, optional qt etc. And the fact that its a huge library.

If my memory recalls me it parses more than 200.000 files.

You could try change this setting:
![image](https://user-images.githubusercontent.com/1165340/115695976-877a6500-a362-11eb-9d1c-3a957cb6721a.png)

That might help with intellisense, which is indeed awfully slow. I have just changed this setting myself and it seems more responsive, however as I understood, only to files you have included in the project. ie. not everyone available in additional include folders, so it cannot suggest you to include new header files, if you write a class name etc.

I don't know how easy it is to optimize the build times, except having mutiple .cpp files, so the entire app doesn't have to be recompiled, but only subparts of it.

**Comment by larshg** [comment] 2021-04-22 10:07
Ohh, I'm not sure if this setting is available in VS2015 though, I use VS2019.
